### ISSUE TITLE
Open Access to "Statements" und "Ontodia"

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#10]
Tab "Statements" und "Ontodia" auf die Notizen mussen in freie Zugang  für alle (auch ohne Login) sein.

**Comment by fkraeutli** [comment]
Deployed on Dev
@b2d3c can you check?

**Comment by b2d3c** [comment]
Perfect! Thanks @fkraeutli

**Comment by b2d3c** [comment]
Thanks!
