### ISSUE TITLE
Formular Record Set: Urheber---Error

### ISSUE THREAD

**Issue by katrinoettli** [sapa/performing-arts-ch-templates#102]
https://www.dev.performing-arts.ch/resource/sapa:createRecordSet

<img width="432" alt="Bildschirmfoto 2022-06-08 um 11 09 18" src="https://user-images.githubusercontent.com/36266394/172578708-d69ce76f-43a9-4e04-a9d4-688e6017cda6.png">

**Comment by fkraeutli** [comment]
fixed with latest update
