### ISSUE TITLE
form:Place Surrounding place

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#111]
ex: http://data.performing-arts.ch/p/9bed5e87-d0d8-4dee-b8e1-db5343888b68

![image](https://user-images.githubusercontent.com/8588224/172799935-f90548a7-c31d-4d10-b9a2-45d8356f01e1.png)

**Comment by fkraeutli** [comment]
Error is gone but field value says "Alger"
<img width="1064" alt="Screenshot 2022-06-10 at 13 35 04" src="https://user-images.githubusercontent.com/1564625/173056408-c067c548-7b6d-4dec-af9a-2bd93e0e5f95.png">

**Comment by b2d3c** [comment]
All right! It's Perfekt @fkraeutli
