### ISSUE TITLE
Start page : Access of all the results

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#119]
Is it a possibility to lauch a query from Start page to have access to all the results?

e.g. "*", "%"

**Comment by fkraeutli** [comment]
It's possible to use the `default-query` attribute to define a query that returns everything when no search input is specified. However, this would mean that it is executed every time the page is accessed, putting unnecessary strain on the database. Will look for a better solution.

**Comment by fkraeutli** [comment]
We could trigger the `default-query` for everything through a link:
<img width="890" alt="Screenshot 2022-06-10 at 15 03 09" src="https://user-images.githubusercontent.com/1564625/173070196-48f073b0-ca6c-4de6-88ab-9dbb9021ee91.png">
After clicking 'Show everything':
<img width="1287" alt="Screenshot 2022-06-10 at 15 03 50" src="https://user-images.githubusercontent.com/1564625/173070348-fce1afcd-c16f-4ad0-8d2e-f954d5afdc43.png">

**Comment by b2d3c** [comment]
@fkraeutli It's Perfekt! Thanks. 

Show everthings@en
Voir tous les résultats@fr
[deutch]@
mostra tutti i risultati@it

**Comment by fkraeutli** [comment]
done
