### ISSUE TITLE
To be deleted (I)

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#126]
We want to delete the following Entities:
- ToBDel_014   http://data.performing-arts.ch/a/ee1f0f7e-bca5-4836-8b32-259b960b0d3a
- ToBDel_015   http://data.performing-arts.ch/a/03d58131-93b3-41f5-bd9c-8f58701cad6d
- ToBDel_020	http://data.performing-arts.ch/o/66e64551-972d-452e-8aed-0232565e5124
- ToBDel_021	http://data.performing-arts.ch/a/9f676a03-c463-43cf-a265-7ac9ae5c0cf9
- ToBDel_022	http://data.performing-arts.ch/a/70cd9976-3d5e-4844-92d3-f51516e3d2f3
- ToBDel_023	http://data.performing-arts.ch/a/c67c2d32-0743-4327-98ad-974aa81f3c41
- ToBDel_024	http://data.performing-arts.ch/a/203e10da-6d7a-427b-8353-ec1401f487f4
- ToBDel_025	http://data.performing-arts.ch/a/5c838393-65dd-43c5-8b01-7147dcb1c887
- ToBDel_026	http://data.performing-arts.ch/a/333de1c5-eed2-4e62-9747-4563314bb5a5
- ToBDel_027	http://data.performing-arts.ch/a/74765127-4dbe-4574-bb3e-cb41c602bfd8
- ToBDel_028	http://data.performing-arts.ch/a/a226b498-c448-4785-b571-f5922a42528f
- ToBDel_029	http://data.performing-arts.ch/a/74442fca-43b1-474d-b28b-7790c16ca657
- ToBDel_030	http://data.performing-arts.ch/r/ba7a4e51-c031-4d22-b6c9-1bec94543598
- ToBDel_031	http://data.performing-arts.ch/r/d0361a93-d3fb-4a1a-8c45-d58341799ca2
- http://data.performing-arts.ch/a/2d6e3450-522e-4be8-803f-94f389ed081e
- http://data.performing-arts.ch/r/6858bf70-ba77-40d6-9d5f-808d62fcf9a0

See also : #127

**Comment by b2d3c** [comment]
Great!! I will check it start next Week.

**Comment by b2d3c** [comment]
It's look like perfekt!

Two notes:
1) Perhaps the text must not only be  "Delete..." but "click to Delete this Entity"

![image](https://user-images.githubusercontent.com/8588224/194889805-fcb82b89-6639-484a-aca2-c9d637d6ea52.png)

2) Is it possible to have a log extract from all the entity deleted and by who, once the Month, you think?

**Comment by b2d3c** [comment]
Thanks a lot @fkraeutli !

3 questions : 

1. Wenn you said "Deployed" could you precise if it's on dev or prod? 
2. On this case, it's on dev. What the planning for Deployed on prod?
3. It have open a new issue to deploy this Function on all Template. See #216

**Comment by fkraeutli** [comment]
1. Yes, sorry, deployed to Dev
2. We can deploy it without restarting the platform. I'll do it next Wednesday
3. If I can manage, I can also implement those next Wednesday and deploy to prod

**Comment by b2d3c** [comment]
Perfekt!
