### ISSUE TITLE
Form:Person, Group, Place : Replaced by

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#127]
In Form:
- Person
- Group
- Place

We need a fonctionnality to remplace a entity by a other.

Data to remplace have be moved to #458

See also : #126

**Comment by b2d3c** [comment]
URI 1 redirect URI 2

**Comment by fkraeutli** [comment]
```sparql
VALUES (?delete ?replace) {
    (<http://data.performing-arts.ch/a/04fad2e6-72f2-4abe-9595-124c8bf1d63c>) (<http://data.performing-arts.ch/a/19892bc3-47f4-4d81-8b52-acb186c978df>)
    (<http://data.performing-arts.ch/a/2a15b229-e98b-4944-ae51-da4baeb91be5>) (<http://data.performing-arts.ch/a/34abeb10-d11b-42be-931f-b9f95c82a989>)
    (<http://data.performing-arts.ch/a/9ed9f4c9-3248-41e7-ac4d-ccaa4f64f704>) (<http://data.performing-arts.ch/a/3e5add7d-13c9-46b4-857a-3f6abb9347dd>)
    (<http://data.performing-arts.ch/a/c22f213a-bd3b-41f0-a12e-a521f3b0ff6d>) (<http://data.performing-arts.ch/a/47a4d536-e543-469b-834f-e5fa1d65b8f5>)
    (<http://data.performing-arts.ch/a/6b7994dc-21c9-4f85-8aec-93340ff534ee>) (<http://data.performing-arts.ch/a/7633b693-dad7-46d7-b002-db6c49df9e75>)
    (<http://data.performing-arts.ch/a/189d3357-64bb-4ef0-b222-5f706a458f7d>) (<http://data.performing-arts.ch/a/78aa0454-9266-4919-be62-6080c78addcf>)
    (<http://data.performing-arts.ch/a/189d3357-64bb-4ef0-b222-5f706a458f7d>) (<http://data.performing-arts.ch/a/78aa0454-9266-4919-be62-6080c78addcf>)
    (<http://data.performing-arts.ch/a/302ea0cf-3299-4c86-8e2e-d29f18485cdf>) (<http://data.performing-arts.ch/a/8ba5f493-e0d1-44c3-abb3-9f5fdefb01c6>)
    (<http://data.performing-arts.ch/a/c11364d3-49d1-4216-99a0-293a31d021c9>) (<http://data.performing-arts.ch/a/a25e37fc-1217-47f9-9ea3-67f77e9dc518>)
    (<http://data.performing-arts.ch/a/95d4250c-35ce-464d-a985-d757b1ed998a>) (<http://data.performing-arts.ch/a/c51cce9f-453d-41f8-a149-a2bde633f806>)
    (<http://data.performing-arts.ch/a/cf5136d5-c2b9-485f-8af9-5aa87764e7d1>) (<http://data.performing-arts.ch/a/cae7f22f-ff57-4574-82ba-d10509876f96>)
    (<http://data.performing-arts.ch/a/7090744c-aaf0-464f-9c7e-de862c1ff802>) (<http://data.performing-arts.ch/a/d1a60ab8-d35f-475f-8820-c655fb79b15d>)
    (<http://data.performing-arts.ch/a/b2c95d1d-534d-440a-a4b6-01c666dd2c08>) (<http://data.performing-arts.ch/a/d429a719-4ce1-4292-895f-5c1f58c9dc43>)
    (<http://data.performing-arts.ch/p/886a850f-31d9-48ad-8c24-e038e14d1d9c>) (<http://data.performing-arts.ch/p/e580a451-c043-4c0e-8c39-c2effebfc224>)
    (<http://data.performing-arts.ch/a/d09e02aa-888c-4b47-9dbc-157f4abd4a68>) (<http://data.performing-arts.ch/r/5c6945ab-299b-4d61-9f3b-968791f7d26b>)
}
```

**Comment by fkraeutli** [comment]
There are two ways we can do this:
Delete the entity and...
1. ...only move the incoming statements to the replacing entity (so that e.g. performances carried out by the old entity are then linked the new entity)
2. ...move all statements to the new entity

2. Could cause some unintended side effects, such as duplicate or conflicting information. However I also noticed that there is some information that is only on the entities to be deleted (e.g. http://data.performing-arts.ch/a/2a15b229-e98b-4944-ae51-da4baeb91be5 has several external resources while http://data.performing-arts.ch/a/34abeb10-d11b-42be-931f-b9f95c82a989 has only wikidata).

There is also a third option, which is relinking the incoming statements and not (yet) delete the entity so that information can be transferred manually if required.

**Comment by b2d3c** [comment]
1. We will use the delete Function (see #126 ) and make all the change manually
2. We need only a URL redirection function. 
- Perhaps we can add a property : spao:remplaceBy. In this case the notice will not be delete but only act a redirection to the rigth Entity. We need in any case clean the notice before.

**Comment by fkraeutli** [comment]
It's tricky to do an automated redirect. What I could try is to display a screen filling notice with a link to the new entity if there is a spao:replacedBy statement. Would that be an option?

**Comment by b2d3c** [comment]
spao:replacedBy is Perfekt!

**Comment by fkraeutli** [comment]
Need: Multilingual labels for new form fields and messages

| id | en | de | fr | it |
| --- | --- | --- | --- | --- |
| FormSectionReplacedBy | Replaced
| FormSectionReplacedByDescription | Replace this entity with a new one. A redirect notice will be displayed when accessing this entity.
| ReplaceEntityReplaced | This entity has been replaced by another one. Please use the following link to access the new entity:

**Comment by fkraeutli** [comment]
Should I deploy to prod?

**Comment by b2d3c** [comment]
Yes! You can deploy in prod. Thanks

**Comment by fkraeutli** [comment]
Deployed

**Comment by b2d3c** [comment]
Thanks!

**Comment by b2d3c** [comment]
One question :

What append with in Incomming Statements after a "Replace" ?

ex : [A](http://data.performing-arts.ch/a/04fad2e6-72f2-4abe-9595-124c8bf1d63c) remplace with [B](http://data.performing-arts.ch/a/19892bc3-47f4-4d81-8b52-acb186c978df) but [C](https://www.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fw%2F238dd1e8-c3a3-4619-bab7-f5a40a9e4caa) link to A and [D](https://www.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fw%2F7838faa3-576e-41c3-988f-80b15e04d33a) to B.

**Comment by b2d3c** [comment]
Data to remplace have be moved to https://github.com/sapa/performing-arts-ch-templates/issues/458
