### ISSUE TITLE
Beschriftung der Felder

### ISSUE THREAD

**Issue by katrinoettli** [sapa/performing-arts-ch-templates#132]
[https://www.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2Fe66923eb-67fe-4a39-aefa-ec30442a05ce](url)
Beschriftung der Felder:  in der Ansicht wird "recordRsource" vor der Beschriftung sichtbar.
Ist mir erst heute morgen auch in dev aufgefallen, sorry.

![Bildschirmfoto 2022-06-23 um 12 09 54](https://user-images.githubusercontent.com/36266394/175275623-4bc4e9da-616f-47a1-8479-fc3fa803e734.png)

**Comment by fkraeutli** [comment]
Some field visualisation query the assets for the label. With inline field definitions these do not exist so we have to replace those with `[[i18n ...]]` statements

(search templates for `VALUES (?label) { (<http://performing-arts.ch/ldp-assets/fieldDefinitionContainer/`)
