### ISSUE TITLE
Place label to display

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#137]
The Label of the Place must be displayed : 
- in the liste of the Start Page
- In the Entity Page

StartPage list : 
![image](https://user-images.githubusercontent.com/8588224/175807201-614b74cb-be27-47cb-8124-d7647c8c053d.png)

Page Entity:
![image](https://user-images.githubusercontent.com/8588224/175807342-31c845a8-bb5d-4185-be3c-51b9de37ad6d.png)

**Comment by fkraeutli** [comment]
Hi @b2d3c ,
these are places that are created when the location of an actor is defined. When selecting a location of an actor, the location is not assigned directly, but a place within that place is created where the actor resides. Your example is the location of [Têtes-de-Pioche](http://data.performing-arts.ch/a/015f81dc-be57-48cf-8239-e7e8d72e9864) within [Courtételle](http://data.performing-arts.ch/p/ba39f488-b35e-49b8-8006-240840cdbbfc). The model reflects that the group does not reside in all of Courtételle, but in a place within that place. This place however is not given a label.

I would solve this by giving preference to labelled places when displaying them in the browsing table.

For the insert pattern that creates these places, see: https://github.com/sapa/performing-arts-ch-templates/blob/master/src/fieldDefinitions.yml#L70

**Comment by fkraeutli** [comment]
Displaying only places with labels. Optimised query to check only for existence of labels but not retrieve them. Query time for all down from ~4 min to ~12s
