### ISSUE TITLE
Layout : display URI of F25_Performance_Plan and F31_Performance

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#142]
- F25_Performance_Plan <http://iflastandards.info/ns/fr/frbr/frbroo/F25_Performance_Plan>
-- [exemple 1](https://www.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fw%2Fd4053378-d0f7-49ed-9ca5-b2967a47e82d)
- F31_Performance <http://iflastandards.info/ns/fr/frbr/frbroo/F25_Performance_Plan> 
 -- [exemple 2](https://www.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fw%2Fd4053378-d0f7-49ed-9ca5-b2967a47e82d%2Fp)

**Comment by fkraeutli** [comment]
"URI not yet permanent"

**Comment by fkraeutli** [comment]
Deploved to Dev

**Comment by b2d3c** [comment]
Perfekt! You can deploy in Dev.
