### ISSUE TITLE
Template:RecordSet display rico:Instantation

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#148]
Example : 
* Record Set : http://data.performing-arts.ch/r/000726a2-8520-4050-ad7f-ad31698784e0
  * Instantation : http://data.performing-arts.ch/o/ce6bf500-7bc2-4b78-8d8e-d441b814e1ad

In the same way as in Template:Record display informations about Instantation. The same Informations must be displayed in Template:RecordSet.

Position :

![Screenshot 2022-07-07 at 16-55-58 Camenzind Stefan performing-arts ch](https://user-images.githubusercontent.com/8588224/177805973-50511212-672f-4080-a343-8d4479542575.png)

See also #149 

Copy from #332

As in Layout:Record : http://data.performing-arts.ch/r/829094e2-37b4-409e-8c21-1d97b195114a

Layout:RecordSet : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2Ff2cf9b61-8060-4237-ae2a-97569017f57a

must be able to display the same informations about his Instanciations :

* https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2Ff2cf9b61-8060-4237-ae2a-97569017f57a
* https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fo%2Fb187a791-bcd6-4a5d-9ed0-6b8581ac8f55

**Comment by b2d3c** [comment]
@fkraeutli This one have also a priority. Thanks!

**Comment by fkraeutli** [comment]
I moved the fields (#149) and added the instantiation view. It's on dev. I reused what was already there so can you check if it needs to be adjusted?

**Comment by fkraeutli** [comment]
sorry, change appears not to be on dev yet

**Comment by fkraeutli** [comment]
No, all good. But I only find three record sets with instantiations
```sparql
PREFIX spao: <http://ontology.performing-arts.ch/>
PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>
SELECT * WHERE {
  ?s a rico:RecordSet ;
  	rico:hasInstantiation ?instantiation .
  ?instantiation spao:hasArchivalStatus ?archivalstatus.    
  VALUES (?order ?archivalstatus) {
      ( 1 spav:asarm )
      ( 2 spav:asprc )
      ( 3 spav:aspcp )
      ( 4 spav:aspcd )
      ( 5 spav:asdsp )
      ( 6 spav:asdcp )
      ( 7 spav:asdcd )
  }
}
```
- http://data.performing-arts.ch/r/f2cf9b61-8060-4237-ae2a-97569017f57a
- http://data.performing-arts.ch/r/e5dc6391-3db2-40dd-95f4-68152e9027e7
- http://data.performing-arts.ch/r/f2cf9b61-8060-4237-ae2a-97569017f57a

**Comment by b2d3c** [comment]
Perfekt! Yes, there only few but with this visualisation the number will grow!

You can deploy in PROD.

The instantiation's informations displayed must be the same for loggued in users and guest, as in #407 

Thanks!

Baptiste

**Comment by fkraeutli** [comment]
Done
