### ISSUE TITLE
Template:Record : RecordPart sorting by technical Identifier

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#153]
?item a rico:RecordPart must be displayed in Template:Record in order of rico:hasOrHadIdentifier -> rico:Identifier crm:P2_has_type <http://vocab.performing-arts.ch/idtec>.

ex: http://data.performing-arts.ch/r/5f51b59d-7205-4044-b241-c33fe607d2e2

![image](https://user-images.githubusercontent.com/8588224/230310366-7b879ba8-8816-480f-b150-fcde76a2f7b4.png)

**Comment by fkraeutli** [comment]
changed and deployed to Dev

**Comment by b2d3c** [comment]
Perfekt. You can deploy in prod. Thanks
