### ISSUE TITLE
Template:RecordPart to create

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#159]
Copy template:Record for create a template:RecordPart.

ex: http://data.performing-arts.ch/r/79a755a4-6c45-4d97-9fb7-9b8eb815e775

Next : #351

**Comment by fkraeutli** [comment]
only for visualisation

**Comment by b2d3c** [comment]
Hello @fkraeutli . We would like to give a priority on this Issue. Thanks in advance!

**Comment by fkraeutli** [comment]
I copied the Record template for Record Parts. Let me know if it serves the purpose

**Comment by b2d3c** [comment]
Great !

Only : 
- Lack only the layout top Part with rico:name / rdf:type / URI.
- The link from the Recordpart on Record is not operative
- In Record layout, we need a way to go to the Record Part.

ex: Record Part https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F1758d5f8-13e5-40b7-a483-4d6c17e03947

![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/13928734-1298-4c49-ae94-f49da86fd0b6)

ex: Record : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F098ae1e9-f6df-4750-b926-cf7f97b2bf7f
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/c2cd5bcb-0416-40ec-9f9f-9624d23f51a7)

**Comment by b2d3c** [comment]
And Template:RecordPart must be the same of the new Template:Record. See #96

**Comment by fkraeutli** [comment]
Made the changes on Dev

re "The link from the Recordpart on Record is not operative": do you mean the link under _Record hierarchy_? I looked at the query and the way it is constructed, the RecordPart itself is returned as a result. Hence the link links to itself

**Comment by b2d3c** [comment]
Thanks!

Two notes : 

- header position
- link to the record.

## Header position
There is a change in the header position between DEV and PROD.
PROD: http://data.performing-arts.ch/r/098ae1e9-f6df-4750-b926-cf7f97b2bf7f
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/1387dd42-43e7-4042-b5d8-75bef162e291)
DEV: https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F1758d5f8-13e5-40b7-a483-4d6c17e03947
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/ee352a5e-2ba0-48fc-abd4-f27da47f8b9b)

## Link to the record
We need to have a link to the Record in the "Record hierarchy" section. It's seem we have to rewrite the code for Template:RecordPart...
Solution 1 : same as record (ex: https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F098ae1e9-f6df-4750-b926-cf7f97b2bf7f)
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/556f04f1-91e6-4fcc-aaac-c4f5ceaf867a)
Solution 2 : only the record (ex: https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fw%2F0e18548d-a43c-4d03-b7a7-202ed8fe93fd)
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/abcb9839-fc2c-4f43-a1aa-93c1fd02a1c9)

**Comment by fkraeutli** [comment]
Added link to record part

**Comment by b2d3c** [comment]
Great for the link to the Record! 
You can deploy the all in prod.  The header's questions will be fix in #328
