### ISSUE TITLE
Form: Research by URI

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#17]
See also : #90 #88 

Es muss möglich sein in alle Form durch URI suchen UND durch Text.

## form:Record Set
- Field:Parent*->URI: /r/
- Field:Creator ->rdf:type crm:E39_Actor (order under-class)
- Field:Provenienz->rdf:type crm:E39_Actor (order under-class) / or URI /u/UUID, /a/UUID
- Field:Subject -> =! URI /x/, /r/
- Field:See also -> URI: /r/

## form:Record
- Field:Parent*->URI: /r/
- Field:Creator ->rdf:type crm:E39_Actor (or under-class)
- Field:Provenienz->rdf:type crm:E39_Actor (order under-class) / or URI /u/UUID, /a/UUID
- Field:Subject -> =! URI /x/, /r/
- Field:See also -> URI: /r/

### Record parts
- Field:Subject-> =! URI /x/, /r/
- Field:See also ->URI: /r/

## form:InstantationPhysical
- Record (part)*->rdf:type <https://www.ica.org/standards/RiC/ontology#Record> OR <https://www.ica.org/standards/RiC/ontology#RecordPart>
- Derived instantation: rdf:type rico:Instantation

## form:InstantationVirtual
- Record (part)*->rdf:type <https://www.ica.org/standards/RiC/ontology#Record> OR <https://www.ica.org/standards/RiC/ontology#RecordPart>
- Derived instantation: rdf:type rico:Instantation

### File
- Field:See also -> URI: /r/

## form:Group
- Predecessor->rdf:type rico:CorporateBody
- Responsible body->rdf:type rico:CorporateBody
- Association membrerships->rdf:type rico:CorporateBody
- Membres->rdf:type crm:E39_Actor (or under-class)

**Comment by fkraeutli** [comment]
I implemented the change to the fields in the RecordSet form and deployed to Dev

@b2d3c can you check if it behaves as desired?

You can search by name:
<img width="412" alt="Screenshot 2022-11-10 at 17 17 55" src="https://user-images.githubusercontent.com/1564625/201149913-ce3d8cec-af9b-42d0-94d9-21ad6d7f2697.png">

And *full* URI:
<img width="537" alt="Screenshot 2022-11-10 at 17 19 25" src="https://user-images.githubusercontent.com/1564625/201149951-a4e4ad4f-5d12-4928-be06-af4a154c2c44.png">

**Comment by b2d3c** [comment]
Cool!
Only one Remarks : 
- Field "seeAlso" must be linked also with /x/ URI see #212

**Comment by fkraeutli** [comment]
I added the URI lookup for the remaining form fields and deployed to Dev

**Comment by b2d3c** [comment]
I will investigate the URI/x. We will fix it in futur. You can deployed the rest in prod already.

Thanks for the optional.
