### ISSUE TITLE
Concept must be directly adress through URI

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#173]
A entity with rdf:type <https://www.ica.org/standards/RiC/ontology#Concept> have to be display direct through is URI.

Ex : Hamlet http://data.performing-arts.ch/c/73907685-18e3-41ec-93aa-aeac97e560dd ([here](https://www.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fc%2F73907685-18e3-41ec-93aa-aeac97e560dd))

See also #62

**Comment by fkraeutli** [comment]
add /c/ redirect

**Comment by fkraeutli** [comment]
I added it, however this requires a restart of the platform. When would be a good time?

**Comment by b2d3c** [comment]
Now I think, when it's only a short (around 15 minutes) wainting time.

**Comment by fkraeutli** [comment]
Sorry, missed it, but I'll do it in the evening or weekend

**Comment by b2d3c** [comment]
Hello @fkraeutli, could you done the restart today?

**Comment by fkraeutli** [comment]
Yep!

**Comment by fkraeutli** [comment]
Restarted and /c/ redirect appears to be working

**Comment by b2d3c** [comment]
Perfekt. Thanks!
