### ISSUE TITLE
Template:Person display dates as 01.02.1960

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#175]
In template Person, we would like to display date as 01.02.1960 (not 1960-02-01).

Ex: http://data.performing-arts.ch/a/51cbc2c1-8969-4bdf-8c66-a120c0bf1c34

Notes SAPA intern : Informer Marcel Wymann

**Comment by fkraeutli** [comment]
check if date format helper (frontend template function) can be used

**Comment by fkraeutli** [comment]
deployed to Dev @b2d3c

**Comment by b2d3c** [comment]
Perfekt ! You can deploy in Prod. Thanks!

Documentation 
Prod: http://data.performing-arts.ch/a/49187985-04f9-4280-be72-dc316d9c1e01
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/84f37202-e6a1-48cc-bc26-392dddc8249a)
Dev : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fa%2F49187985-04f9-4280-be72-dc316d9c1e01
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/b6acf4f0-5e99-4b42-bc4b-084fdad8d3ba)
