### ISSUE TITLE
Add a API reconcile Service for OpenRefine

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#180]

**Comment by fkraeutli** [comment]
Predefined service is here: https://www.performing-arts.ch/rest/reconciliation
Check if already works out of the box

**Comment by b2d3c** [comment]
All right! We have the capacity to reconcily and to download the URI from SPAP. The issue is completed.

I have open a other one to extend this functionnality. See https://github.com/sapa/performing-arts-ch-templates/issues/509
