### ISSUE TITLE
Form:Group change Rules (crm:P107i_is_current_or_former_member_of statement)

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#182]
After #181 

In Form:Group, there are : 

Membership / Mitglied von / Adhérent à / Membro di

![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/902242d5-4d4b-4f0a-b1c9-068d92bde3d1)

Layout for logged people (in Group) : Association memberships / Mitglied von / Adhérent à / Membro di

ex: http://data.performing-arts.ch/a/138a6114-7bba-4ab7-bb43-ccd5ff3d7b77
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/ec2f8f07-0e63-470c-b4f4-81a63dbb690d)

Layout for logged people (in Veband) : Association members / Verbandsmitglieder / Membres de l’association / Membri dell’associazione

ex: http://data.performing-arts.ch/a/0afb069a-cd7e-4517-862e-fb607c4b5717
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/f30b5b66-270d-409d-bbf9-6e61d0811975)

Members / Mitglieder / Membres / Membri

![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/938a4251-c262-42ad-82c0-da81ffa56333)

For Membership the property is `?Group crm:P107i_is_current_or_former_member_of ?OtherGroup`. 

But there is a mandatory rule : `?OtherGroup crm:P2_has_type <http://vocab.performing-arts.ch/vrjhq> (verband) `

We want to remplace it with this ` ?OtherGroup rdf:type <https://www.ica.org/standards/RiC/ontology#CorporateBody>`

SPARQL : https://www.dev.performing-arts.ch/sparql?query=PREFIX+crm%3A+%3Chttp%3A%2F%2Fwww.cidoc-crm.org%2Fcidoc-crm%2F%3E%0APREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0ASELECT+%2A+WHERE+%7B%0A++%3FInst+a+%3Chttps%3A%2F%2Fwww.ica.org%2Fstandards%2FRiC%2Fontology%23CorporateBody%3E.%0A++MINUS+%7B%3FInst+crm%3AP2_has_type+%3Fqqch%7D.%0A%7D+LIMIT+10%0A

**Comment by b2d3c** [comment]
see also : #290

**Comment by fkraeutli** [comment]
changed and deployed to Dev

**Comment by b2d3c** [comment]
Great!

We need now just to change the layout.

## template:Group
ex: https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fa%2F0387974a-abfb-4d9c-9a11-f6c0f416c632
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/144141f1-60e8-4336-bc97-62a13f82cee4)

Association members and individual members have to be dispaly under the same label "Members".

## Form:Group

![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/2cf86669-6e87-4f64-9e33-65058bfc004e)
* Association memberships@en -> Memberships@en
* others linguages : ok

**Comment by fkraeutli** [comment]
changed and deployed to dev

**Comment by b2d3c** [comment]
Sorry, I want to go back and to maintain in the Layout 3 labels different for : 
- `?Group crm:P107i_is_current_or_former_member_of ?OtherGroup`
  - Layout in ?Group ex: http://data.performing-arts.ch/a/b7f5f7ea-78c6-43a5-aea7-1ecb1c49faa0
  - Layout in ?OtherGroup ex: http://data.performing-arts.ch/a/0afb069a-cd7e-4517-862e-fb607c4b5717
- `?Group crm:P107_has_current_or_former_member ?Person`

We need just a change in the Label.

## Layout ?Group
- Memberships@en instead of Association memberships@en
- Mitglied von@de | no change
- Adhérent à@fr | no change
- Membro di@it | no change
## Layout ?OtherGroup
- Group members@ instead of Association members@en
- Verbandsmitglieder@de instead of Mitglieder@
- Membres@fr instead of Membres de l’association@fr 
- Membri@it instead of Membri dell’associazione@it

**Comment by fkraeutli** [comment]
I think I reverted and changed it accordingly. Can you check on dev?

**Comment by b2d3c** [comment]
Thanks.

Just lack in Layout ?OtherGroup (`?Group crm:P107i_is_current_or_former_member_of ?OtherGroup`) the change label:

- Group members@ instead of Association members@en
- Mitglieder@de instead of VerbandsMitglieder@
- Membres@fr instead of Membres de l’association@fr 
- Membri@it instead of Membri dell’associazione@it

ex: DEV https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fa%2F0387974a-abfb-4d9c-9a11-f6c0f416c632
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/e5ce2464-5f09-41e7-91a7-cd3272a573a3)
