### ISSUE TITLE
ArchivPlan : research (5-1)

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#184]
Why in [ArchivPlan](https://www.performing-arts.ch/resource/sapa:ArchivePlan) with the research : 5-1 we don't find http://data.performing-arts.ch/r/a76490e9-3c49-481d-be68-e04716744bbb

**Comment by b2d3c** [comment]
hello @fkraeutli @olyanicolaeva, could you check this question Issue in priority?

**Comment by fkraeutli** [comment]
It's because the string "5-1" appears in many documents (e.g. 1027-5-10-11). I'll check if I can influence the prioritisation and get rid of some less relevant result. It also seems that t get's translated to "5-1*" which means the search includes even more results.

**Comment by b2d3c** [comment]
It's better! Thanks! We plan to deploy in prod?
