### ISSUE TITLE
Delete subection in section Archive

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#186]
First we have planed to create for each "Fonds" a "Subsection" with the same name : 

![image](https://user-images.githubusercontent.com/8588224/188566500-6c773103-a62d-404c-9808-1e29d4e8cc9f.png)

![image](https://user-images.githubusercontent.com/8588224/188569045-6a3100d2-c27a-4382-b953-5d496d0a5c4a.png)

But now we don't want anymore this subsections. We want that the "Fonds" are direct with Subsection "Privat person" or "Legal bodies" linked. 

Could you : 
* direct linked "Fonds" of Private persons with "Private persons"
* direct linked "Fonds" of Legal Bodies with "Legal Bodies"
* delete empty subsection

Here are the lists:
* [List of fonds of private persons](https://www.performing-arts.ch/sparql?query=%23Liste+des+fonds+%22Private+persons%22+%C3%A0+accrocher+directement+%C3%A0+la+subsection+%22Private+persons%22%0APREFIX+rico%3A+%3Chttps%3A%2F%2Fwww.ica.org%2Fstandards%2FRiC%2Fontology%23%3E%0ASELECT+DISTINCT+%3Ffonds%0AWHERE+%7B%3Fsubsection+rico%3AisOrWasIncludedIn+%3Chttp%3A%2F%2Fdata.performing-arts.ch%2Fr%2F0768692d-3731-4a18-b74f-a72ea39e5fee%3E.%0A++%3Ffonds+rico%3AisOrWasIncludedIn+%3Fsubsection.%0A++%7D)
* [list of subsections of private persons to delete](https://www.performing-arts.ch/sparql?query=%23Liste+des+subsections+%22Private+Persons%22+%28qui+incluent+un+fonds%29+%C3%A0+supprimer%0APREFIX+rico%3A+%3Chttps%3A%2F%2Fwww.ica.org%2Fstandards%2FRiC%2Fontology%23%3E%0ASELECT+DISTINCT+%3Fsubsection%0AWHERE+%7B%3Fsubsection+rico%3AisOrWasIncludedIn+%3Fsection.%0A++VALUES+%3Fsection+%7B%3Chttp%3A%2F%2Fdata.performing-arts.ch%2Fr%2F0768692d-3731-4a18-b74f-a72ea39e5fee%3E%7D%0A++%3Ffonds+rico%3AisOrWasIncludedIn+%3Fsubsection.%0A++%7D)
* [List of fonds of Legal Bodies](https://www.performing-arts.ch/sparql?query=%23Liste+des+fonds+%22Legal+bodies%22+%C3%A0+accrocher+directement+%C3%A0+la+subection+%22Legal+bodies%22%0APREFIX+rico%3A+%3Chttps%3A%2F%2Fwww.ica.org%2Fstandards%2FRiC%2Fontology%23%3E%0ASELECT+DISTINCT+%3Ffonds%0AWHERE+%7B%3Fsubsection+rico%3AisOrWasIncludedIn+%3Chttp%3A%2F%2Fdata.performing-arts.ch%2Fr%2F2bb94f6f-735c-4616-bff9-10660c3ff70c%3E.%0A++%3Ffonds+rico%3AisOrWasIncludedIn+%3Fsubsection.%0A++%7D)
* [List of subsections of legal bodies to delete](https://www.performing-arts.ch/sparql?query=%23Liste+des+subsections+%22Legal+Bodies%22+%28qui+incluent+un+fonds%29+%C3%A0+supprimer%0APREFIX+rico%3A+%3Chttps%3A%2F%2Fwww.ica.org%2Fstandards%2FRiC%2Fontology%23%3E%0ASELECT+DISTINCT+%3Fsubsection%0AWHERE+%7B%3Fsubsection+rico%3AisOrWasIncludedIn+%3Chttp%3A%2F%2Fdata.performing-arts.ch%2Fr%2F2bb94f6f-735c-4616-bff9-10660c3ff70c%3E.%0A++%3Ffonds+rico%3AisOrWasIncludedIn+%3Fsubsection.%0A++%7D)

**Comment by fkraeutli** [comment]
DRAFT Query
```sparql
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>
DELETE {
  ?subsection rico:isOrWasIncludedIn ?subsection_private_persons .
  ?fonds rico:isOrWasIncludedIn ?subsection .
} INSERT {
  ?subsection crm:P3_has_note "markForDeletion" .
  ?fonds rico:isOrWasIncluded ?subsection_private_persons .
}
WHERE {
  BIND(<http://data.performing-arts.ch/r/0768692d-3731-4a18-b74f-a72ea39e5fee> as ?subsection_private_persons)
  ?subsection rico:isOrWasIncludedIn ?subsection_private_persons.
  ?fonds rico:isOrWasIncludedIn ?subsection.
}
```

**Comment by b2d3c** [comment]
Great. Just at the end, I think we have to write :  
 <s>GRAPH ?gSubsection {?subsection rico:isOrWasIncludedIn ?subsection_private_persons.}</s>
  GRAPH ?gFonds {
      ?fonds rico:isOrWasIncludedIn **?subsection_private_persons**.}
No?

**Comment by b2d3c** [comment]
But there will be two values for rico:isOrWasIncludedIn in ?fonds. Or Function GRAPH overwrite the existing value?

**Comment by fkraeutli** [comment]
That’s what we add in the insert clause. In the where clause the Fonds will still be within the subsections

**Comment by b2d3c** [comment]
My SPARQL level is no high enough :-( but I will trust you!

**Comment by fkraeutli** [comment]
Ok, I'll sleep a night over it and then run it on dev ;)

**Comment by fkraeutli** [comment]
Executed on Dev and I think it did the trick (only persons). Can you check?

<img width="1168" alt="Screenshot 2022-10-21 at 13 41 15" src="https://user-images.githubusercontent.com/1564625/197188272-d64fd978-4a7b-40d3-8eab-5abb37d5504c.png">


<img width="1168" alt="Screenshot 2022-10-21 at 13 42 29" src="https://user-images.githubusercontent.com/1564625/197188261-feca1d2b-b2d5-483f-b008-67040dc0b6df.png">

**Comment by b2d3c** [comment]
I have check. It's Perfekt! You can deployed! Thanks

**Comment by fkraeutli** [comment]
Query for legal bodies:
```sparql
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>
DELETE {
  ?subsection rico:isOrWasIncludedIn ?subsection_legel_bodies .
  ?fonds rico:isOrWasIncludedIn ?subsection .
} INSERT {
  GRAPH ?gSubsection {
      ?subsection crm:P3_has_note "markForDeletion" .
  }
  GRAPH ?gFonds {
     ?fonds rico:isOrWasIncludedIn ?subsection_legel_bodies .
  }
} WHERE {
  BIND(<http://data.performing-arts.ch/r/2bb94f6f-735c-4616-bff9-10660c3ff70c> as ?subsection_legel_bodies)
  GRAPH ?gSubsection {
      ?subsection rico:isOrWasIncludedIn ?subsection_legel_bodies.
  }
  GRAPH ?gFonds {
      ?fonds rico:isOrWasIncludedIn ?subsection.
  }
}
```

**Comment by fkraeutli** [comment]
@b2d3c I executed also the query for legal bodies on Dev. Can you confirm?

**Comment by b2d3c** [comment]
Yes! Thanks.

**Comment by fkraeutli** [comment]
Great, the change has been done on Prod as well
