### ISSUE TITLE
add rico:descriptiveNote In Form:Instantation und Template:Instantation

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#188]
## A Field string with Property : rico:descriptiveNote have to be add to Form
* Form:VirtualInstantation
* Form:PhysicalInstatantion

Unter "History"
With the Labels:
* Présentation du contenu@fr
* Content description@en
* Inhaltsbeschreibung@de
* Descrizione dei contenuti@it

## value (string) of Property : rico:descriptiveNote have to be displayed on:
* Template:VirtualInstantation Unter "Integrity"
* Template:PhysicalInstatantion Unter "Copy Path"

With the Labels:
* Présentation du contenu@fr
* Content description@en
* Inhaltsbeschreibung@de
* Descrizione dei contenuti@it

**Comment by fkraeutli** [comment]
Implemented and deployed to Dev
Virtual and Physical Instantiation use the same template for display. Let me know if the position of the field display is ok in both

**Comment by b2d3c** [comment]
Great! You can deployed in Prod. Thanks
