### ISSUE TITLE
Backup Plateform

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#195]
We would like to have a backup (dump) pro Month of the Plateform.

Ex: prod20210904.nq.gz

How to organise in the easy way this transfert of data?

WikiSAPA : https://wiki.sapa.swiss/index.php?title=SPAP/Backup

**Comment by b2d3c** [comment]
I suggest a share File on your Switch account. It's a possible solution for you?

**Comment by fkraeutli** [comment]
Check Sphaera backup mechanism and if it is reusable with Switch

**Comment by b2d3c** [comment]
There is a backup each night of Switch and there are not delete. It's enough.
