### ISSUE TITLE
SARI (Test) : Start Page / Search Group

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#20]
mit "La troupe de Philippe de Broca" oder "Broca" die suchmachine findet kein Resultat.
Trotz: http://172.23.167.51:10214/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fa%2Fdc8d3da2-bea1-4249-8576-6a07c2444597

**Comment by fkraeutli** [comment]
Appears to be fixed with #30
