### ISSUE TITLE
Free Access to Page "Archiv Plan" and "Media Search" via Menu Quick Links

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#209]
We want to give a free access to the publics at Pages "Archive Plan" and "Media Search" via Quick Links.

![image](https://user-images.githubusercontent.com/8588224/194344029-b9f65baf-e60a-428c-952d-630875227f9f.png)

**Comment by fkraeutli** [comment]
Implemented and deployed to Dev and Prod

**Comment by b2d3c** [comment]
Thanks a lot !
