### ISSUE TITLE
Form:RecordSet add spao:seeAlso

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#212]
Field "See Also" (spao:seeAlso) in Form:RecordSet cloud done a link to Record Ressource Entities (rico:RecordSet, rico:Record, rico:RecordPart, rico:Instantation).

It's already exist this case : 

- http://data.performing-arts.ch/r/85b6dd24-6703-4577-88fe-74d186719267 (Cie. Marie-Jane Otth) link to RecordPart 
- http://data.performing-arts.ch/r/79a755a4-6c45-4d97-9fb7-9b8eb815e775 (En miroir (Marie-Jane Otth)) who is constitued of (rico:isOrWasConstituentOf) http://data.performing-arts.ch/r/89ae6aea-ced5-4f8b-8399-d4f87f899444 (En hauteur / En profondeur / En miroir / En attendant le taureau (Saveurs de l'autre - collectif du Bugnon)

![image](https://user-images.githubusercontent.com/8588224/195030873-3c750def-24cd-465a-996a-cd707d604aa7.png)

But it's impossible to do it through the Form...

Perhaps in reason of #159

**Comment by b2d3c** [comment]
Dear @fkraeutli ,

Could you add this fonctionnality in Form:RecordSet?

Thanks in advance

**Comment by fkraeutli** [comment]
It looks like the field query is expecting a `rdfs:label`, but those records have a `rico:name` instead. Will adjust the query.

**Comment by fkraeutli** [comment]
Changed and deployed to dev for @b2d3c to check

**Comment by b2d3c** [comment]
Perfekt! You can deployed in prod. 

I have done a check with a entity of level Fonds : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2Ff2cf9b61-8060-4237-ae2a-97569017f57a

I have done a link through "see also" to : 
* a person (already possible)
* a record set
* a record
* a record part
In futur, we will think about add : 
* Instantiation
* File

![image](https://user-images.githubusercontent.com/8588224/234272409-0c9c820d-8cd8-40c4-8734-c3702e68e0f0.png)
