### ISSUE TITLE
Form:RecordSet, Record, Instantation : comma (or point) in rico:quantity

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#213]
We want to be able to use a comma (or point) in rico:quantity in Form:RecordSet, Record, Instantation

See:  rico:hasExtent ->rico:RecordResourceExtent->rico:quantity

![image](https://user-images.githubusercontent.com/8588224/195034679-76081e53-07bd-42b5-bfc3-496188763e7e.png)

**Comment by fkraeutli** [comment]
deployed to Dev for @b2d3c to check

**Comment by b2d3c** [comment]
Perfekt for the comma. You can deployed in prod. Thanks!

But see also : #231

**Comment by fkraeutli** [comment]
It's deployed
