### ISSUE TITLE
Access for docuteam an IIIF server

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#217]
We need to give a access to our IIIF server to Raphaël Barman <r.barman@docuteam.ch>, in the scope that he import data inside.

**Comment by fkraeutli** [comment]
Emailed for SSH key

**Comment by b2d3c** [comment]
@fkraeutli could you give the access to [r.barman@docuteam.ch](mailto:r.barman@docuteam.ch) of IIIF server. He have send is SSH key apparently. Thanks in advance.

**Comment by fkraeutli** [comment]
Yes I'm on it! Currently have issues accessing the server myself, but hope to have it sorted soon

**Comment by fkraeutli** [comment]
Done
