### ISSUE TITLE
New Entity "World"

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#218]
1. Create entity 1 : 
- rdf:type crm:E53_Place, rico:Place
- rdfs:label : Welt@de, Monde@fr, Mondo@it, World@en
- owl:sameAS : http://www.wikidata.org/entity/Q2
2. Add,  in all the rico:Place without property crm:P89_falls_within. see [Liste](https://www.performing-arts.ch/sparql?query=PREFIX+spao%3A+%3Chttp%3A%2F%2Fontology.performing-arts.ch%2F%3E%0APREFIX+rico%3A+%3Chttps%3A%2F%2Fwww.ica.org%2Fstandards%2FRiC%2Fontology%23%3E%0APREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0APREFIX+crm%3A+%3Chttp%3A%2F%2Fwww.cidoc-crm.org%2Fcidoc-crm%2F%3E%0APREFIX+spav%3A+%3Chttp%3A%2F%2Fvocab.performing-arts.ch%2F%3E%0APREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX+frbroo%3A+%3Chttp%3A%2F%2Fiflastandards.info%2Fns%2Ffr%2Ffrbr%2Ffrbroo%2F%3E%0ASELECT+%2AWHERE+%7B%0A%3Fplace+a+rico%3APlace.%0A++MINUS+%7B%3Fplace+crm%3AP89_falls_within+%5B%5D%7D.%0A%7D%0A), property crm:P89_falls_within ->entity 1

**Comment by fkraeutli** [comment]
Add World entity:
```sparql
INSERT DATA {
    <http://data.performing-arts.ch/p/ac7e765b-7b06-4740-a180-72b5d62ce42c/container/context> {

        <http://www.metaphacts.com/ontologies/platform#formContainer> <http://www.w3.org/ns/ldp#contains>
            <http://data.performing-arts.ch/p/ac7e765b-7b06-4740-a180-72b5d62ce42c/container> .

        <http://data.performing-arts.ch/p/ac7e765b-7b06-4740-a180-72b5d62ce42c> a <http://www.cidoc-crm.org/cidoc-crm/E53_Place>,
            <https://www.ica.org/standards/RiC/ontology#Place>;
        <http://www.cidoc-crm.org/cidoc-crm/P87_is_identified_by> <http://data.performing-arts.ch/p/ac7e765b-7b06-4740-a180-72b5d62ce42c/a>;
        <http://www.w3.org/2000/01/rdf-schema#label> "Welt"@de, "World"@en, "Monde"@fr,
            "Mondo"@it;
        <http://www.w3.org/2002/07/owl#sameAs> <http://geonames.org/6295630/>,
            <http://viaf.org/viaf/6270149919445006650001>, <http://www.wikidata.org/entity/Q2> .

        <http://data.performing-arts.ch/p/ac7e765b-7b06-4740-a180-72b5d62ce42c/a> a <http://www.cidoc-crm.org/cidoc-crm/E48_Place_Name>;
        <http://www.w3.org/1999/02/22-rdf-syntax-ns#value> "Welt"@de, "World"@en,
            "Monde"@fr, "Mondo"@it .

        <http://data.performing-arts.ch/p/ac7e765b-7b06-4740-a180-72b5d62ce42c/container>
        a <http://www.w3.org/ns/ldp#Resource>, <http://www.w3.org/ns/prov#Entity>;
        <http://www.w3.org/ns/prov#generatedAtTime> "2022-11-23T12:15:25.388Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>;
        <http://www.w3.org/ns/prov#wasAttributedTo> <http://www.metaphacts.com/resource/user/admin> .

    }
}
```

**Comment by fkraeutli** [comment]
Implemented and deployed to Dev. Can you check @b2d3c ?

**Comment by b2d3c** [comment]
Perfekt! You can deploy in Prod.

**Comment by fkraeutli** [comment]
Deployed
