### ISSUE TITLE
Increase backup retention period to 7 days

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#219]
In 13.10.2022 around 11am the plateform start a backup who block the access to it for 1 hour.

Wo have start this backup? It's a automatic process?

**Comment by fkraeutli** [comment]
It's automated every day at 21h and backs up to an S3 bucket. I think the stalling of the platform was not caused by the backup, but by a Google bot (which I blocked now)

**Comment by b2d3c** [comment]
Thanks for the info.

how many time the daily backups are archived?

**Comment by fkraeutli** [comment]
Once per day

**Comment by b2d3c** [comment]
Sorry, I would ask : "How long the archived data will be storage?"

**Comment by fkraeutli** [comment]
ah, if I read the configuration correctly, it will only retain the 3 latest versions

**Comment by b2d3c** [comment]
Ok. 3 days. We have to be quick if we want to go back. If the storage is not a limit I would prefer to keep minimal 7 days.

**Comment by fkraeutli** [comment]
I think we should be fine storage wise. I can increase it

**Comment by fkraeutli** [comment]
It looks like the deletion routine was never implemented so backups are retained indefinitely

**Comment by b2d3c** [comment]
Ok! we can take also 1 year, It would be enough ;-)
