### ISSUE TITLE
SARI (test) : Katrin

### ISSUE THREAD

**Issue by katrinoettli** [sapa/performing-arts-ch-templates#22]
Formulare Record Set, Record

- Gegenstand/Subject: es erscheint eine Errormeldung
<img width="674" alt="image" src="https://user-images.githubusercontent.com/36266394/169229160-6ba39428-477e-43ef-ab34-8ed2eada7945.png">
g

Formular Physical instantiation
 
Auswahlfeld Material stimmt nicht. Es wurde das Auswahlfeld vom Feld  Trägertyp übernommen
![image](https://user-images.githubusercontent.com/36266394/169229356-f4cd0350-5f6c-4670-8bd2-889dc29842ee.png)

**Comment by olyanicolaeva** [comment]
fixed in testing environment

**Comment by fkraeutli** [comment]
> @fkraeutli fyi: can be integrated into inline field definitions

done: https://github.com/swiss-art-research-net/performing-arts-ch-templates/commit/e9d524c2d8ea73fc8a7a98f46e5145eb8a7b8128
