### ISSUE TITLE
crm:P4_has_time-span URL?

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#220]
Why https://www.performing-arts.ch/resource/?uri=http%3A%2F%2Fwww.cidoc-crm.org%2Fcidoc-crm%2FP4_has_time-span

and not : https://www.performing-arts.ch/resource/crm:P4_has_time-span wie https://www.performing-arts.ch/resource/crm:P9_consists_of

**Comment by fkraeutli** [comment]
the ?uri={{URI}} syntax is the default, but metaphactory tries to use the nicer namespace: syntax when it knows the namespace. However, it doesn't always get it right so you might see both
