### ISSUE TITLE
rico:RecordResourceExtent with GB as rico:hasUnitOfMeasurement not displayed

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#231]
Thanks for add "umgig" (GB) in ControlledTerms.xlsx for rico:hasExtent ->rico:RecordResourceExtent->rico:quantity

It's allright for all form : RecordSet, Record, Instantation

It's well displayed on Template:Instantation:  [exemple](https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fo%2F578aedaa-791f-4475-be5d-85b915b9faf2)

But It's not displayed on:
Template:RecordSet: http://data.performing-arts.ch/r/af100b33-56a1-4d40-8c0c-719a811e68ee
Template:Record: [exemple](https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2Fd6f3122e-9282-40ce-9c9d-6c4c48d5a680)

**Comment by fkraeutli** [comment]
I see, looks like the display is hardcoded. I'll get on it

**Comment by fkraeutli** [comment]
Fix is deployed to Dev

**Comment by b2d3c** [comment]
Top! You can deployed in Prod.

**Comment by fkraeutli** [comment]
Deploted
