### ISSUE TITLE
Archivplan : Research Field

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#235]
We want to extend the list of properties's values where the Field Research on [ArchivPlan Page](https://www.performing-arts.ch/resource/sapa:ArchivePlan) is connected:

- rico:descriptiveNote
- rico:history
- spao:deliveryNumber
- spao:hasNote

But First : which are the actually properties's values asked by a Request?

See also : #158

**Comment by olyanicolaeva** [comment]
@b2d3c currently the labels are fetched for rico:name and rico:identifier

**Comment by fkraeutli** [comment]
Deployed to Dev

**Comment by b2d3c** [comment]
Perfekt! You can deploy in prod! Thanks

**Comment by fkraeutli** [comment]
Deployed to prod
