### ISSUE TITLE
Template:Person ->Produktionen-> CSV download

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#239]
In Start Page, we find a "CSV dowload" Button

![image](https://user-images.githubusercontent.com/8588224/199665841-2a48bb55-b6ad-4fde-8036-31ba69cc1aa1.png)

It's possible to add it also in Template:Person ->Produktionen
Ex: http://data.performing-arts.ch/a/a19a2b23-02f8-4f56-acb2-d5bf338f4239
![image](https://user-images.githubusercontent.com/8588224/199665657-8e9b0489-5922-44a9-9151-4cda02f8925e.png)

**Comment by fkraeutli** [comment]
CSV download can mirror query for table (also if URI)
If easy to include, add label

**Comment by fkraeutli** [comment]
Added and deployed to Dev for @b2d3c

**Comment by b2d3c** [comment]
Perfekt. You can deploy in Prod.

**Comment by b2d3c** [comment]
It's apparently deploy in PROD. Thanks! I close the issue.
