### ISSUE TITLE
SARI (test) : Start Page / Text

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#24]
Text oben den Sucheintritt zu löschen : 
- fr "Chercher tout..."->"
- de "Alles durchsuchen ..."
- en "Search all..."
- it "Cerca in tutti i campi..."

**Comment by fkraeutli** [comment]
done. see https://github.com/swiss-art-research-net/performing-arts-ch-templates/commit/3c5975313cd922e9c0aea8ad7781cc72987c10eb
