### ISSUE TITLE
Form:Instantiation spao:hasArchivalStatus (mandatory)

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#243]
In Form:VirtualInstantiation and In Form:PhysicalInstantiation, 

Field "Archival Status" (spao:hasArchivalStatus) must be mandatory otherwise they are not displayed in Template:Record.

![image](https://user-images.githubusercontent.com/8588224/199705346-db10943e-6ce9-4871-907a-7438aad19940.png)

![image](https://user-images.githubusercontent.com/8588224/199705584-14a79225-9b53-4ef6-a6dc-bbd5f4ae9068.png)

**Comment by fkraeutli** [comment]
changed and deployed to dev @b2d3c
