### ISSUE TITLE
Bug : Form:Instantation -> rico:identifier erase by Form

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#245]
After : #75

See also : #253 

rico:identifier value (old version) is not displayed in Form:Instantation and after Submit erase.

ex: http://data.performing-arts.ch/o/ffbf2a57-86da-4092-8bd3-0cb0c41bbc55
![image](https://user-images.githubusercontent.com/8588224/199719811-83c6384d-2b02-42b8-97c0-e6aced946062.png)

![image](https://user-images.githubusercontent.com/8588224/199719981-eb1c82ae-2b64-431e-8558-6139f9bbf15d.png)

**Comment by b2d3c** [comment]
See http://data.performing-arts.ch/o/ce71c7ff-90a6-48e7-84a3-24756bd68e28

![image](https://user-images.githubusercontent.com/8588224/201645434-5dd1a0b5-36bd-4dd7-81a8-3f9a69b342fb.png)

![image](https://user-images.githubusercontent.com/8588224/201645597-f3f9794b-1b60-47a2-8e66-6081c10b8a2d.png)

**Comment by fkraeutli** [comment]
Old identifier gets overwritten when saving new form

**Comment by fkraeutli** [comment]
Fixed and deployed to Dev _and_ Prod
