### ISSUE TITLE
Add rico:isAssociatedWithEvent in Form:Instantation and dysplay the value

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#246]
in the same way as in Form:Record (ex: http://data.performing-arts.ch/r/0151dd97-538b-47e2-86ba-ae06b517f032)
![image](https://user-images.githubusercontent.com/8588224/199725007-b3b85995-14e2-4e54-89e3-37650e951f1e.png)

## Add
Add rico:isAssociatedWithEvent(->rico:Event avec rico:hasEventType = spav:et). in 

- Form:VirtualInstantation. Label "Mode of acquisition@en, Modalità d’acquisizione@it, Eingangsart@de, Mode d’acquisition@fr"
- Form:PhysicalInstantation.  Label "Mode of acquisition@en, Modalità d’acquisizione@it, Eingangsart@de, Mode d’acquisition@fr"
![image](https://user-images.githubusercontent.com/8588224/199725375-5bada116-0cfa-48b0-9cca-87f2c51d3847.png)

## Display
display the value In : 

- Template :VirtualInstantation.  Label "Mode of acquisition@en, Modalità d’acquisizione@it, Eingangsart@de, Mode d’acquisition@fr"
- Template:PhysicalInstantation.  Label "Mode of acquisition@en, Modalità d’acquisizione@it, Eingangsart@de, Mode d’acquisition@fr"
![image](https://user-images.githubusercontent.com/8588224/199727010-83f3039f-c809-4bf2-8723-159cc61ef1bc.png)

**Comment by fkraeutli** [comment]
Implemented and deployed to Dev

**Comment by b2d3c** [comment]
Great! You can deploy in Prod. Thanks!
