### ISSUE TITLE
Location not displayed for standard user

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#248]
Values from rico:hasOrHadLocation not displayed for unlogged users.

ex: http://data.performing-arts.ch/r/4f4144a9-3b01-4ce4-b408-ca0ce76090f3

see also : #306

**Comment by fkraeutli** [comment]
Location is hidden for anonymous users
Deployed to Dev for @b2d3c to check

**Comment by b2d3c** [comment]
Top! Thanks @fkraeutli Florian. You can deploy in Prod.

**Comment by fkraeutli** [comment]
Deployed to prod

**Comment by b2d3c** [comment]
Location not hidden here : http://data.performing-arts.ch/r/66cbd340-7bb8-4615-bfd0-951a77953fc3 

Could you see, why?

**Comment by fkraeutli** [comment]
Yes it's a different template (`rico:Record`). We can add the new location display there as well

**Comment by b2d3c** [comment]
Yes. Will be perfect to add to layout from rico:RecordSet also this specification. Thanks in advance

**Comment by b2d3c** [comment]
Great! Thanks.
