### ISSUE TITLE
Layout bug

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#250]
http://data.performing-arts.ch/w/f92b8d9a-82a6-4a00-a282-278379aa90dc

![image](https://user-images.githubusercontent.com/8588224/200309971-e78432bb-f645-49ea-95d8-ae3770b816f9.png)

**Comment by fkraeutli** [comment]
I fixed the bug (on dev and prod). It was caused by an unbound variable in the SPARQL Query:
```sparql
SELECT ?producer ?unidentified ?season WHERE {
                  ?? crm:P9_consists_of ?production .
                  ?production crm:P2_has_type spav:muwgo ;
                      crm:P14_carried_out_by ?producer .
                  OPTIONAL {
                      ?expressioncreation crm:P10_falls_within ?season .
                      FILTER(CONTAINS(STR(?season), "/s/"))
                  }
                  BIND(IF(CONTAINS(STR($producer), "/u/"), "true", "") AS ?unidentified)
              }
```
The `?expressioncreation` in the optional that queries the season is unbound. What is the path from `?production` to `?season`?

**Comment by b2d3c** [comment]
Perfekt ! Thanks
