### ISSUE TITLE
Template:Record -> values of rico:hasOrHadIdentifier von rico:Instantation must be displayed

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#253]
After #75 

see also : #245 

In Template:Record, values of rico:hasOrHadIdentifier von rico:Instantation must be displayed

Ex: http://data.performing-arts.ch/r/f7334439-ca5b-4299-91dd-5886ad252f90

![image](https://user-images.githubusercontent.com/8588224/201647987-b359ce92-3dda-4601-a1f7-7b2fa1224bb9.png)

![image](https://user-images.githubusercontent.com/8588224/201647829-fc2fd05b-8840-4744-ae59-b5e1bc29d2bd.png)

**Comment by b2d3c** [comment]
http://data.performing-arts.ch/r/8405e62a-8078-4778-b145-4767eef9dfd5

**Comment by b2d3c** [comment]
Thanks !

Only Ask : Identifier mutt be at the first place at the top, just down "Instantation".

ex: https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2Ff7334439-ca5b-4299-91dd-5886ad252f90

![image](https://user-images.githubusercontent.com/8588224/203555162-2fdfb55b-4324-46ef-a663-d73ed38583d7.png)

**Comment by fkraeutli** [comment]
Changed and deployed to Dev

**Comment by b2d3c** [comment]
Great! You can deployed in Prod. Thanks!
