### ISSUE TITLE
Property owl:sameAs (external ressources) : https (GND)

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#261]
Could we introduce the https possibility and not only the http in owl:sameAs ?

Ex: Carl Moos (http://data.performing-arts.ch/a/b1645f63-5383-4ff7-a917-173a7e2936db)
- https://d-nb.info/gnd/127086757 AND not only http://d-nb.info/gnd/127086757

Is It the same as #45 ?

See also : #162

**Comment by fkraeutli** [comment]
Similar to #45. It however is linked to the output. Only URIs that match what is expected are displayed. I added https for all of them and will deploy to dev

**Comment by b2d3c** [comment]
I can't access to dev but I propose to deploy in Prod.

**Comment by fkraeutli** [comment]
Deployed to prod

**Comment by b2d3c** [comment]
@fkraeutli It's work on dev [1] but not on prod [2].

Could you see why?

[1] https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fa%2F60736de8-ccfa-4ce7-8bfc-4aafab3c306a
[2] http://data.performing-arts.ch/a/4516147b-d101-4d3f-b28a-ed5e900d847d with GND https://d-nb.info/gnd/11855932X

**Comment by fkraeutli** [comment]
My bad, change has not been deployed to prod after all. Did it now

**Comment by b2d3c** [comment]
Thanks!
