### ISSUE TITLE
Template:Production displayed owl:sameAs (external ressources)

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#262]
We want that the Template:Production display owl:sameAs (external ressources) as Template:Person

Ex: [Person](https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fa%2F51cbc2c1-8969-4bdf-8c66-a120c0bf1c34)
![image](https://user-images.githubusercontent.com/8588224/202434215-409201d3-8a39-4e39-b017-febf960498fd.png)

Ex:[Production](https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fw%2F0e18548d-a43c-4d03-b7a7-202ed8fe93fd)

Same as : #18

Link with : #61

**Comment by fkraeutli** [comment]
@b2d3c Question: in #61 the field for External ID is specified with `crm:P1_is_identified_by`. Should it be `owl:sameAs` instead?

**Comment by b2d3c** [comment]
You you have right for URI owl:sameAs is best as crm:P1_is_identified_by (only string). 

Could you display the value in Template:Production and modify the Form:Production #61 in this way.

Thanks in advance!

**Comment by b2d3c** [comment]
Modification : the both are important !
-  owl:sameAs -> URL/URI
-  crm:P1_is_identified_by -> string with label "RepID". ex : http://data.performing-arts.ch/w/25be6f93-4f03-4441-a67f-a25819bba07e

I have modificate #61

**Comment by fkraeutli** [comment]
Deployed to Dev as part of #61

**Comment by b2d3c** [comment]
Ok! see : http://data.performing-arts.ch/w/3a2762f2-d69b-42cf-9cef-54c9742cb923
