### ISSUE TITLE
SARI (test) : Start Page / Search Corporate body

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#27]
In SARI Test plateforme mit "Lapzeson" finden wir nur die "Lapzeson, Noémie" (person) aber nicht "Vertical Dance" (corporate body) wie in die productive Plateforme. Die Suche muss auch in den "crm:P131_is_identified_by" Werten suchen.

**Comment by b2d3c** [comment]
Vielleicht die gleiche Probleme : Mit "Beauso*":
- SARI Test findet nur die Venue
- PRoductive Plateforme findet die Venue und die Corporate Body.

**Comment by fkraeutli** [comment]
Probably related to #30

**Comment by olyanicolaeva** [comment]
will be fixed with https://github.com/sapa/performing-arts-ch-templates/issues/30
