### ISSUE TITLE
Form:Instantiation / Research on "Record (part)*"

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#273]
In `Form:Instantiation `(virtual and Physical), in Field "Record (part)*", we want to be able to Research on ?identifier. 

?identifier =
A)  ?item rico:identifier ?identifier. ex: Record "1047-2-1-7-1" in [DEV](https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F5d34f00a-fedf-4926-8972-6d0636bfc16b)
B) ?item rico:hasOrHadIdentifier ?ItemIdentifier. ?ItemIdentifier <s>rdfs:label</s> rdf:value ?identifier ex: Record "Truc/VIDEO-20240522-1" in [DEV](https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F6312e712-001c-4713-afe1-ad77cb001a65)

Voir mail ae du 28.11.2022 "J'ai vu un truc"

**Comment by fkraeutli** [comment]
Added search by identifier. Note that the entire identifier needs to match. Is this what you need or do yo prefer a partial matching? It's deployed to Dev

**Comment by b2d3c** [comment]
I have update the first post.

For A) Great!
For B) I have make a mistake in my query. It isn't "rdfs:label" but "rdf:value". Could you implement the change?

**Comment by fkraeutli** [comment]
Changed and deployed to Dev

**Comment by b2d3c** [comment]
A + B ok in `Form:PhysicalInstantiation` but B must be implemented in `Form:VirtualInstantiation`

**Comment by fkraeutli** [comment]
Got it. I adjusted the query and deployed to Dev. Can you test again?

**Comment by b2d3c** [comment]
Done. Perfekt. You can deploy in PROD. Thanks!
