### ISSUE TITLE
SARI (Test) : encoding bug

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#28]
![image](https://user-images.githubusercontent.com/8588224/169775497-0c8fa121-ec82-46a3-b17b-83e16fe0b025.png)

**Comment by b2d3c** [comment]
![image](https://user-images.githubusercontent.com/8588224/169785648-3fd47cd3-51aa-4003-a696-2ead5a6c26e6.png)

**Comment by b2d3c** [comment]
![image](https://user-images.githubusercontent.com/8588224/169785751-e0a9e932-bccc-4f63-9389-bf66ef15de19.png)

**Comment by fkraeutli** [comment]
fixed. see https://github.com/swiss-art-research-net/performing-arts-ch-templates/commit/bc6c19dec5d207e6562b7a4d143953e85e5df158
