### ISSUE TITLE
Bug : vimeo video display

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#281]
@fkraeutli , the video vimeo with link https are not display in the Plateforme.

Ex: 

In http://data.performing-arts.ch/r/7a7bce46-a46f-49ba-8e79-1e823e7bd7fa

The link https://vimeo.com/303518555 is accepted but not displayed in the Tab "Video". The same link with http give no problem.

Could you done for the two form could be displayed?

Thanks in advance

See also : #45

**Comment by fkraeutli** [comment]
Should be fixed (dev and prod)

**Comment by b2d3c** [comment]
Great ! Thanks
