### ISSUE TITLE
Error : this.chartInstance is undefined

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#282]
ex: http://data.performing-arts.ch/o/2c4eef69-fd96-44e1-b869-4c29ddb65d8b

![image](https://user-images.githubusercontent.com/8588224/205583367-28946259-e3ef-4810-82b4-787ecbf37e5d.png)

Dear @fkraeutli, could you explain us where the error come from ?

**Comment by fkraeutli** [comment]
Is it still present? It looks like this at my end:
<img width="1079" alt="Screenshot 2022-12-07 at 13 26 15" src="https://user-images.githubusercontent.com/1564625/206179010-174537f5-9dfb-40ef-b36f-da50880ae434.png">

**Comment by b2d3c** [comment]
Indeed.
