### ISSUE TITLE
SARI (test) : Start Page / Ordnung

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#29]
Die Resultaten mussen in diese Ordnung sein : 
Produktionen / Personen / Gruppen und Institutionen / Bühnen / Orte
![image](https://user-images.githubusercontent.com/8588224/169777388-38c32d57-42e4-4fa7-82e0-d6742d5e2e50.png)

**Comment by fkraeutli** [comment]
fixed. see https://github.com/swiss-art-research-net/performing-arts-ch-templates/commit/1888cd1b6d2b639cee6f32cd49e8a55597d2acfb
