### ISSUE TITLE
bug : Form:Group -> crm:P107i_is_current_or_former_member_of

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#290]
Apparently, there is a bug in Form:Group in the Field "crm:P107i_is_current_or_former_member_of". We don't succeed to put in values (string oder URI).

exemple bug : http://data.performing-arts.ch/a/6a40f90d-2c52-483b-ab36-578685c42f7c with values : 
- "Bühnen der Hauptstadt" http://data.performing-arts.ch/a/2bb6a5e9-cee8-493a-906b-6193226c9808 

exemple normal : http://data.performing-arts.ch/a/ea0a3d0f-30e4-4ecf-82cc-8601099213ba with the values : 
- ASSITEJ Schweiz : http://data.performing-arts.ch/a/20f7ff80-106f-4bd3-b21b-de585eecd64f

**Comment by fkraeutli** [comment]
The query looks for E40 Legal Bodies that have type spav:vrjhq. Bühnen der Hauptstadt seems to lack this type. If I remove this condition it works. I implemted and deployed to Dev. Let me know if you want to deploy this change to prod or if you want to include another condition instead.

**Comment by b2d3c** [comment]
"Bühnen der Hauptstadt" have Type : "Fördergesellschaft".
 "Fördergesellschaft" is a undercategory of Verband (spav:vrjhq).
 
![image](https://user-images.githubusercontent.com/8588224/207875639-3b6368e3-f24f-4a75-8e5a-49835948bae1.png)

Is it possible to add simply "Fördergesellschaft" in the restriction?

After you can deploy to Prod.

**Comment by fkraeutli** [comment]
Ah I see. The query only asked for the Verband type. I'll change it so it includes Verband as well as its children

**Comment by fkraeutli** [comment]
Changed and deployed to Dev

**Comment by b2d3c** [comment]
I can't access to dev but I propose, here too, to deploy in prod.
