### ISSUE TITLE
SARI (test) : Zahl "Gruppen und Institutionen" (bug)

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#30]
Mit Gruppen : 3 Resultaten aber 9 Suchergebnisse
![image](https://user-images.githubusercontent.com/8588224/169778057-d631be6c-daea-417e-b483-a7272e826b60.png)

**Comment by fkraeutli** [comment]
Originates from the fact that Groups and Institution comprise both E74 Group and E40 Legal Body. The table queries for both, but the type query only for one. We'll fix.

**Comment by fkraeutli** [comment]
Fixed by mapping E40 to E74 in query. See also: https://github.com/swiss-art-research-net/performing-arts-ch-templates/commit/26c1edd41fa1c26785519db0deb3266ab6e0f536
