### ISSUE TITLE
premis:File must be directly adress through URI

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#303]
Like : #173 but for File /0/

Ex: 
- URI : http://data.performing-arts.ch/0/481a7dc6-a710-4e8e-b9fc-f4db4c4ff9a6
- URL : https://www.performing-arts.ch/resource/?view=statements&uri=http%3A%2F%2Fdata.performing-arts.ch%2F0%2F481a7dc6-a710-4e8e-b9fc-f4db4c4ff9a6

**Comment by fkraeutli** [comment]
In which form and field(s) are files assigned @b2d3c ?

**Comment by b2d3c** [comment]
premis:File are created through Form:Virtual Instantiation

![image](https://user-images.githubusercontent.com/8588224/234269570-4ff0f7cb-77ab-4696-8329-1f02acd32568.png)

The data model of premis:File is : 

* Composition level* : premis:compositionLevel ->string
* Fixity : premis:fixity -> string qui crée un UUDI de type Fixity.
* Video damage : spao:hasVideoDamage -> vocabulaire contrôlé
* History : rico:history ->string
* Integrity : rico:integrity ->string
* Last control : spao:lastControl -> date
* See also : spao:seeAlso -> URI
* Original name*  : ebucore:fileName -> premis:originalName
* Size: ebucore:fileSize -> premis:size
* Duration :ebucore:duration -> string : (vérifier le format)
* Container Format (ebucore:hasFormat) -> idem : spav:cf
* Video Format (ebucore:hasFormat) -> idem : spav:vf
* Audio Format (ebucore:hasFormat) -> idem : spav:af
* Color: <ebucore:technicalAttributeString typeLabel="ColorSpace"> ->rdau:P60558 à vérifier!
* Width:ebucore:width -> idem : string
* Height:ebucore:height -> idem : string
* Standard : <ebucore:technicalAttributeString typeLabel="Standard">->ebucore:hasStandard : vocabulaire contrôlé
* Aspect ratio: ebucore:aspectRatio -> à vérifier le transfert vers le vocabulaire contrôlé!
* Scanning format : ebucore:scanningFormat -> idem : vocabulaire contrôlé
* Scanning order : ebucore:scanningOrder -> idem : vocabulaire contrôlé
* Channels : ebucore:channels -> idem : string
* Sampling rate : <ebucore:technicalAttributeString typeLabel="ChromaSubsampling"> -> ebucore:samplingRate

But @fkraeutli  : uri /0/ must not have a layout. They need only to be open on the by default layout directly through the URI.

**Comment by fkraeutli** [comment]
We probably need to add an extra fields to add files that already exist. Otherwise we risk adding data twice, i.e. when a file is created within an instantiation form, added to another, and edited there. Because the file lives in the named graph of the instantiation it was originally created, the file would then exist twice.

I will try to add a second field for adding existing files, with a link to the instantiation where the file was originally created and where it can be edited.

**Comment by fkraeutli** [comment]
I implemented a solution and deployed it to Dev for @b2d3c to check

**Comment by fkraeutli** [comment]
> Thanks @fkraeutli . I don't have imagine it's will be so complex. Perhaps we have to stop here this developpement and wait to talk about on our next meeting.
> 
> My question :
> 
> * It's rico:RecordPart embeded also in rico:Record (because they are create through the Form:Record)?

yes

example query to verify:
```sparql
PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
SELECT ?recordPart ?parent ?parentType WHERE {
  GRAPH ?g {
    ?recordPart a rico:RecordPart
  }
  BIND(URI(STRBEFORE(STR(?g), "/container")) as ?parent)
  ?parent a ?parentType .
} LIMIT 10
```

> * There are two formats for URI of premis:File, Why? It's a difference between them?
>   
>   * /o/ (like rico:Instantiation) : http://data.performing-arts.ch/o/00b9636c-6bf7-4f4a-aeb1-e5c89b30d21c
>   * /0/ : https://www.performing-arts.ch/resource/?view=statements&uri=http%3A%2F%2Fdata.performing-arts.ch%2F0%2F481a7dc6-a710-4e8e-b9fc-f4db4c4ff9a6

I'm not sure, though I noticed it too

>   * The Files with the URI with the first format are directly accessible via URI, the second not. Why?

Because there is only a rewrite in place for `/o/` (we can add `/0/` though)

<img width="657" alt="Screenshot 2023-04-27 at 10 56 39" src="https://user-images.githubusercontent.com/1564625/234812456-96fa0b1e-1626-494e-808b-49d39ee27d47.png">

**Comment by b2d3c** [comment]
If pathstoRewrite allow to put the URI in navigator and to find the page : Prima! It's exactly what we want.

We need for File no Layout and no specific Form to Edit (we make change through Form:Instantiation).

**Comment by fkraeutli** [comment]
Reverted change in Dev

**Comment by fkraeutli** [comment]
Adding the rewrite will cause 1 min of downtime. Is there a good time to do that @b2d3c ?

**Comment by b2d3c** [comment]
No problem! You can do it. Thanks

**Comment by fkraeutli** [comment]
Done
