### ISSUE TITLE
Bug : Edit File data (via Form:Instantiation)

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#304]
We are no more able to edit File data via Form:Instantiation.
ex: http://data.performing-arts.ch/o/50745ed1-8488-4fce-90df-bb72c0ab4d04

**Comment by fkraeutli** [comment]
The visualisation template displays the form for the Virtual or Physical instantiation based on the type `ebucore:MediaResource` or `premis:Representation`
```html
        [[#if (ask "ASK { ?? a ebucore:MediaResource . }")]]
        <bs-tab event-key='editing physical' title='[[i18n "TabEdit" bundle="performing-arts-ch"]]'>
            [[> sapaModule:InstantiationFormPhysical]]
        </bs-tab>
        [[/if]]
        
        [[#if (ask "ASK { ?? a premis:Representation . }")]]
        <bs-tab event-key='editing virtual' title='[[i18n "TabEdit" bundle="performing-arts-ch"]]'>
            [[> sapaModule:InstantiationFormVirtual]]
        </bs-tab>
        [[/if]]
```
however the form for virtual instantiations assigns ebucore:MediaResource:
https://github.com/sapa/performing-arts-ch-templates/blob/b60071b6694819062eadeb1cb1b145b46c65df6c/data/templates/http%253A%252F%252Fpage-module.performing-arts.ch%252FInstantiationFormVirtual.html#L49

Therefore the file input is not displayed. Virtual Instantiation are edited using the Physical form.

Should I change the type for virtual instantiations to premis:Representation?

(the form also contains a TODO which I don't understand)

**Comment by b2d3c** [comment]
Thanks for the answer!

If I good understand there was never a possibility to edit File after is creation, indeed? It's not a bug?

If it was never this possibility, also I propose to think about it in 2023. It's not a easy Issue, I can imagine ?

**Comment by fkraeutli** [comment]
Yes I checked the file history and this appears to have always been there.

I can deploy the change so that the form inserts the correct type, but entries that have the incorrect type will have to be changed manually.

**Comment by b2d3c** [comment]
Yes. We would like to the form Virtual inserts the correct type. Thanks!

**Comment by fkraeutli** [comment]
Changed and deployed to dev. Can we deploy to Prod @b2d3c ?

**Comment by b2d3c** [comment]
Prima! Es klapprt. You can deploy in prod.

Only "See also" in File is not funktionnal (mit URI and string) but we can done for it perhaps a other Issue.
