### ISSUE TITLE
Layout : Location in Template:Instantation und Template:Record

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#306]
rico:hasOrHadLocation : "Reihe 1" -> "SAPA, Bern, Hallerstrasse 6 (3012 Bern), Reihe 1"

WikiSAPA : https://wiki.sapa.swiss/index.php?title=Cotes/topo/SAPA

See also :  #248

**Comment by fkraeutli** [comment]
Example: "Cours de danse collectif"
Location: Boîte PLV/1 -> this should display the entire hierarchy (either as tree or with slashes)

**Comment by fkraeutli** [comment]
Changed and deployed to Dev. @b2d3c can you let me know in which other templates this should be displayed? (added to rico:Record)

**Comment by b2d3c** [comment]
@fkraeutli :

- For Record mit 1 value : ok (https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F9ebba1c1-6e38-4e20-8eeb-aac405422145)
- For Record mit 2 values : Problems (https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F301fb406-ee65-4d1c-b59d-ea168d9b3e9a) the hierarchy is mix. Diplay on two separate lines.
- For Instantiation (virtual and physical) : to add (https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fo%2F6d05fc5c-9ec2-4933-9dd4-fa58edb20d96)

**Comment by fkraeutli** [comment]
Thanks @b2d3c!
I changed it so it can display several locations and added it to instantiation. It's deployed to Dev

**Comment by b2d3c** [comment]
Perfekt @fkraeutli ! You can deploy in prod. Thanks

**Comment by fkraeutli** [comment]
Deployed to prod
