### ISSUE TITLE
Template:Instantation 2*"Carrier Type"

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#316]
ex : 
* dev : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fo%2F78f261b4-c339-40af-9edc-23437473ffbe
![image](https://user-images.githubusercontent.com/8588224/230363946-568c2765-0552-4530-b78b-221204e82ebb.png)

* prod : http://data.performing-arts.ch/o/088a5cee-8be1-4964-ab46-d24f0f4e2446

**Comment by olyanicolaeva** [comment]
carrier type field is displayed double

**Comment by olyanicolaeva** [comment]
the component is listed twice in the code, will fix in the next session

**Comment by b2d3c** [comment]
Dear @olyanicolaeva : is it possible to deploy this modifications next week also? 

For information : @fkraeutli

**Comment by olyanicolaeva** [comment]
@b2d3c yes, I will add it to the dev branch

**Comment by b2d3c** [comment]
Already deploy in PROD.

Thanks! I Close the Issue.
