### ISSUE TITLE
Date(s)Cannot choose an switch case for set of types 

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#320]
ex: http://data.performing-arts.ch/r/8405e62a-8078-4778-b145-4767eef9dfd5

Edit ->  Warning : Parties de document - Date(s)Cannot choose an switch case for set of types 

We don't understand what to do?

Voir WikiSAPA: https://wiki.sapa.swiss/index.php?title=Vimeo/SAPA#Liens_SPAP

**Comment by olyanicolaeva** [comment]
@b2d3c Hi, I cannot reproduce the issue locally, could you please provide screenshots with examples. Thank you!

**Comment by b2d3c** [comment]
Hallo @olyanicolaeva,

If you go in the page http://data.performing-arts.ch/r/8405e62a-8078-4778-b145-4767eef9dfd5 and select  "Edit", you will find this warning at the bottom : 
![image](https://user-images.githubusercontent.com/8588224/221513396-13294311-912b-4691-b720-5187622f6ced.png)

The problem come that Record Part have 2 Singel Date : 
![image](https://user-images.githubusercontent.com/8588224/221513815-c35b15cc-7475-4cea-ad76-f9fba054af58.png)
This come from the migration.

We try through the Form, to delete all the doublon Date, but we don't succed. The warning in always there. This situation block all others modifications. 

Thanks in advance for your help.

**Comment by b2d3c** [comment]
The same problem happen in many other entities : 
http://data.performing-arts.ch/r/8405e62a-8078-4778-b145-4767eef9dfd5

http://data.performing-arts.ch/r/48fd92d0-1751-48bf-8ccd-3a60bd500eb3

http://data.performing-arts.ch/r/0a34525f-7f42-4810-b29c-f99747e306c3

http://data.performing-arts.ch/r/a2895e4f-c282-480a-aa41-070009716e7b

http://data.performing-arts.ch/r/bab6242d-8bec-4f68-8b75-c55b960c8df0

http://data.performing-arts.ch/r/fee7e714-5176-4d2c-939a-7433dbc91fa0

http://data.performing-arts.ch/r/8a98a65f-3bdf-43bc-8b96-83ea9316c285

http://data.performing-arts.ch/r/19892a2e-685e-4b14-b8c0-b73fce66ff9a

http://data.performing-arts.ch/r/5ddfebce-f864-405e-988d-eab3049dd390

http://data.performing-arts.ch/r/7da18da5-2192-45f6-bfc7-e086a058784f

**Comment by olyanicolaeva** [comment]
@b2d3c thank you! That's very helpful

**Comment by olyanicolaeva** [comment]
the issue comes from [FormSwitch Component](https://github.com/swiss-art-research-net/metaphacts-community/blob/f243053e302e260fb45c41f874b929182ddc506c/metaphacts-platform/web/src/main/components/forms/inputs/FormSwitch.tsx) lines 202-207

@fkraeutli can you please check if you can reproduce it locally? I don't seem to have this issue on my machine.

**Comment by fkraeutli** [comment]
Weirdly enough I can't reproduce it locally either. Maybe with a more recent Blazegraph dump?

**Comment by olyanicolaeva** [comment]
@fkraeutli yes, that's what I thought to do next too

**Comment by olyanicolaeva** [comment]
NB: blazegraph journal needs chmod 644 surprisingly and not 999

**Comment by olyanicolaeva** [comment]
**Field Definition**
```
[[#*inline "RecordResourceDateType"]]
    {
        "id" : "RecordResourceDateType",

            "label": "[[i18n "field_date_type" bundle="sapa-fields"]]",
            "minOccurs" : "1",
            "maxOccurs" : "1",
            "xsdDatatype" : "http://www.w3.org/2001/XMLSchema#anyURI",
            "domain" : "https://www.ica.org/standards/RiC/ontology#RecordResource",
                "selectPattern" : "SELECT $value WHERE { $subject a $value . }",
                "insertPattern" : "INSERT { $subject a $value . } WHERE { }",
                "deletePattern" : "DELETE { $subject a $value . } WHERE {}",
        "iri" : "RecordResourceDateType"
    }
[[/inline]]
```
**Template**
```
<semantic-form-switch-case label='Single Date'>
                <semantic-form-composite-input for="RecordResourceProcessingDate" new-subject-template='http://data.performing-arts.ch/x/{{UUID}}' fields='[
                  [[> RecordResourceDateType]],
                  [[> RecordResourceDateValue]],
                  [[> RecordResourceDateQualifier]],
                  [[> RecordResourceDateCertainty]]
                ]'>
                  <semantic-form-hidden-input for="RecordResourceDateType" default-value='[[resolvePrefix "rico:SingleDate"]]'></semantic-form-hidden-input>
                  <semantic-form-text-input for="RecordResourceDateValue"></semantic-form-text-input>
                  <semantic-form-checklist-input row=true for="RecordResourceDateQualifier"></semantic-form-checklist-input>
                  <semantic-form-checklist-input row=true for="RecordResourceDateCertainty"></semantic-form-checklist-input>
                </semantic-form-composite-input>
              </semantic-form-switch-case> 
```

**Comment by fkraeutli** [comment]
It seems that there are dates without a type. The forms use the type to determine which of the forms to use. Here is an example query:
```SPARQL
SELECT * WHERE {
  BIND(<http://data.performing-arts.ch/r/8405e62a-8078-4778-b145-4767eef9dfd5> as ?subject)
  $recordPart rico:isOrWasConstituentOf $subject .
   $recordPart rico:isAssociatedWithDate $recordResourceDate .
  OPTIONAL {
    $recordResourceDate a $recordResourceDateType .
  }
}
```

You can see in the result that one date misses the type:
![Uploading Screenshot 2023-03-14 at 15.53.16.png…]()

**Comment by fkraeutli** [comment]
Upon further inspection, the date that misses a type does not have any triples attached. So my guess is we can delete those empty date URIs.

**Comment by fkraeutli** [comment]
This query should give us all the empty dates:
```SPARQL
PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>
SELECT * WHERE {
  $recordPart rico:isOrWasConstituentOf $subject ; 
              rico:isAssociatedWithDate $recordResourceDate .
  FILTER NOT EXISTS {
      ?recordResourceDate ?p ?o
  }
}
    
```

**Comment by fkraeutli** [comment]
The delete query appears to be working.

@olyanicolaeva Can I hand this back to you to verify and test on the dev instance? Since this is a destructive query, we want to make sure it does what we want it to.

**Comment by olyanicolaeva** [comment]
Yes, will do, thank you for looking into it.

On Mar 14, 2023 3:57 PM, Florian Kräutli ***@***.***> wrote:

The delete query appears to be working.

@olyanicolaeva<https://github.com/olyanicolaeva> Can I hand this back to you to verify and test on the dev instance? Since this is a destructive query, we want to make sure it does what we want it to.

**Comment by b2d3c** [comment]
Dear @olyanicolaeva , Dear @fkraeutli ,

Could we ask you to just clean the data in the items in purpose we can update the notices?

The origin of the bug could we see perhaps in a second time if it's arrive again.

Thanks in advance

**Comment by olyanicolaeva** [comment]
@fkraeutli it is not possible to check it on the dev instance since there are no faulty dates there. 
@b2d3c ok, I am executing queries on the production server now.

**Comment by olyanicolaeva** [comment]
@b2d3c all done, you can test it on prod server.

**Comment by b2d3c** [comment]
Thanks a lot @olyanicolaeva ! I will test it.
