### ISSUE TITLE
rico:physicalCharacteristics Layout:Record/RecordSet

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#331]
The value from the property rico:physicalCharacteristics is not display at this time.

In Layout:Record (ex: http://data.performing-arts.ch/r/0ef0124f-16b1-4ea9-986b-af19e95f975a)
In Layout:RecordSet (ex: http://data.performing-arts.ch/r/0ecfbdae-e25a-4986-b555-81ff17b61752)

Could you introduce it ? Like in Layout:Instanciation (ex: http://data.performing-arts.ch/o/90eca16f-b883-4a9a-87d8-10d7272c433f)

**Comment by fkraeutli** [comment]
added and deployed to dev

can you check @b2d3c ?

**Comment by b2d3c** [comment]
Perfekt! You can deploy in prod. Thanks!
