### ISSUE TITLE
Github : explanation

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#333]
Hi @fkraeutli 

Could we ask you to explain us the mining of all our respositories on Gitub : https://github.com/orgs/sapa/repositories?type=all

All are always needed?

And we would like to know if we could exclude the outside collaborators : https://github.com/orgs/sapa/outside-collaborators

Thanks in advance

**Comment by fkraeutli** [comment]
Hi Baptiste,
I don't seem to have access to the outside-collaborators one.

I also don't know all the repos, but the ones we mainly use are:
- https://github.com/sapa/performing-arts-ch-templates: Contains all templates and code for the platform. This is where we mainly work and develop things
- https://github.com/sapa/performing-arts-ch-users: Private repo to store user accounts.
- https://github.com/sapa/performing-arts-ch-ansible: Private repo containing deploy scripts. We use this to update the platform.
- https://github.com/sapa/spa-vocabulary: Contains the custom vocabularies as Excel sheets and scripts to convert it to RDF

**Comment by b2d3c** [comment]
Thanks a lot !

Could you take time to read cickly this other Repositories and informe us about their content?
* performing-arts-ch-data-model Public 
* performing-arts-ch-docker-compose Public 
* swiss-performing-arts Public archive
* performing-arts-ch-media Private 
* data-management Private 
* data-migration Private 
* performing-arts-ch-i18n Private

Thanks in advance!

**Comment by fkraeutli** [comment]
- performing-arts-ch-data-model Public
Intended for documenting data model, but currently empty. 
- performing-arts-ch-docker-compose Public
The configuration for deploying the platform. Appears to be based on the Metaphactory setup and is likely obsolete and superseded by https://github.com/sapa/performing-arts-ch-ansible
- swiss-performing-arts Public archive
Looks like scripts that have been used to convert data into RDF. It's a fork of a repo done by Zazuko
- performing-arts-ch-media Private
Ansible configuration for setup of IIIF server. Possibly by now integrated into https://github.com/sapa/performing-arts-ch-ansible
- data-management Private
Scripts and queries for extracting certain data and for backup of the platform. The current platform uses a different backup mechanism however
- data-migration Private
Scripts to convert data obtained from the Swiss Dance Collection to the SAPA RDF model
- performing-arts-ch-i18n Private
Scripts for generating language files (multilingual labels for fields, etc) for the metaphacts platform based on an Excel sheet. We haven't used this but edited the language files manually.

**Comment by b2d3c** [comment]
Great! Thanks!

**Comment by fkraeutli** [comment]
Indicate which ones could be archived

**Comment by b2d3c** [comment]
Thanks a lot @fkraeutli !
