### ISSUE TITLE
Layout:Record color RecordPart

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#337]
It's possible to change te color of the RecordPart section in Layout:Record?

![image](https://user-images.githubusercontent.com/8588224/225032259-78b3f0c1-192d-4e4b-9a45-71a1262eaa1f.png)

**Comment by fkraeutli** [comment]
Make it easier to distinguish data coming from the record that is viewed from data that comes from associated entities (e.g. record parts).

**Comment by olyanicolaeva** [comment]
query to identify records, which have Parts:
```
PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
prefix wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?subject WHERE {?subject <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://www.ica.org/standards/RiC/ontology#Record>  .
  ?part rico:isOrWasConstituentOf ?subject .
 } LIMIT 100
```
Templates affected: Record (data/templates/Template%3Ahttps%3A%2F%2Fwww.ica.org%2Fstandards%2FRiC%2Fontology%23Record.html), RecordParts (data/templates/http%3A%2F%2Fpage-module.performing-arts.ch%2FRecordParts.html)

**Comment by olyanicolaeva** [comment]
@b2d3c I currently changed the colour of RecordPart to grey, but we can always pick up a different colour or a gradient. 
![Screenshot 2023-03-29 at 16 00 24](https://user-images.githubusercontent.com/86773892/228562576-efd5687b-9914-4c98-a0b5-71e325fe82a3.png)

**Comment by b2d3c** [comment]
Geat @olyanicolaeva !You can delpoy in Dev und Prod. Thanks!

**Comment by b2d3c** [comment]
@olyanicolaeva,

Thanks ! It's ok mit Bing and Chrome but not mit Firefox. 

It's my cache or something else?

http://data.performing-arts.ch/r/037fd072-230d-45eb-a5e8-e7ed61893007

![grafik](https://user-images.githubusercontent.com/8588224/234867158-3fe40719-dc9d-479b-a1ca-b295d38dd13e.png)

**Comment by olyanicolaeva** [comment]
I just double checked for me, it works in all browsers. Please, try clearing cache and cookies.

**Comment by b2d3c** [comment]
You are right! Sorry for the disturbing! Many Thanks.
