### ISSUE TITLE
dev offline (bug)

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#349]
Hello @olyanicolaeva ,

https://www.dev.performing-arts.ch/resource/sapa:Search is offline.

Cloud you check it?

Thanks in advance

**Comment by olyanicolaeva** [comment]
@b2d3c yes, looking into it straight away

**Comment by b2d3c** [comment]
@olyanicolaeva in Switch IT Infrastructure you mean? 

There is something to do? Someone to ask?

![image](https://user-images.githubusercontent.com/8588224/230324161-74620d89-97a1-44fd-9405-83d6016a10c0.png)

**Comment by olyanicolaeva** [comment]
I am looking now into the general infrastructure in switch and I will let you know if I can restart the machine

**Comment by olyanicolaeva** [comment]
@b2d3c I have put the dev server back up.

**Comment by b2d3c** [comment]
Merci beaucoup @olyanicolaeva !
