### ISSUE TITLE
?item a rico:Identifier (bug)

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#350]
rico:Identifier was introduce via #75

But in Form:Record, in the section RecordPart (Teildokument), the Feld create a entity without rdf:type rico:Identifier.

ex: http://data.performing-arts.ch/x/b1938b83-f2de-450a-bb81-2ce6ce45b2a4 (via http://data.performing-arts.ch/r/b634c0b1-12d3-4a21-8ca7-c2bcf4ab7d95)

Could you fix it?

**Comment by fkraeutli** [comment]
Step 1: Add RDF type via SPARQL update
Step 2: Add RDF type in sub forms

**Comment by fkraeutli** [comment]
```sparql
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>
INSERT {
  GRAPH ?g {
    ?identifier a rico:Identifier .
  }
} WHERE {
  GRAPH ?g {
    ?record rico:hasOrHadIdentifier ?identifier .
  }
  FILTER NOT EXISTS {
    ?identifier a ?type .
  }
} ```

**Comment by fkraeutli** [comment]
Fixed and deployed to dev.
Can you check @b2d3c ?

**Comment by b2d3c** [comment]
Perfekt. Thanks! You can deploy in prod.
