### ISSUE TITLE
Form:Instantiation (virtual) add Field

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#354]
# add in Form:InstantiationVirtual (no in File section):
- Video damage : spao:hasVideoDamage -> vocabulaire contrôlé (
- Integrity : rico:integrity ->string
- Last control : spao:lastControl -> date
- duration : ebucore:duration -> string (format validation)

# add in Form:InstantiationVirtual (no in File section) and Physical :
- See also : spao:seeAlso -> URI

# display in Template:Instantiation (as in Template:File):
- all witout Intergrity already displayed (http://data.performing-arts.ch/o/081b9d23-9e95-464c-b6c0-a252d1ce9015)
# change the label in Template:File and in Form:File :
- all with "(deprecated)"

Voir WikiSAPA : https://wiki.sapa.swiss/index.php?title=Metaphactory/Form:Instantation#Propri.C3.A9t.C3.A9s_non_import.C3.A9es

**Comment by katrinoettli** [comment]
![Virtual_20230412](https://user-images.githubusercontent.com/36266394/231690452-c497a505-6401-4f2f-a37a-4c402173eda2.jpg)

**Comment by katrinoettli** [comment]
the field history already exists

**Comment by fkraeutli** [comment]
re duration and validation. We have a field SchemaDuration that uses `schema:duration` and validates the duration to be `HH:MM:SS`. Do you want to copy this for `ebucore:duration`?

**Comment by b2d3c** [comment]
If it's not too complex, it's better for us to continue to use `ebucore:duration`

**Comment by fkraeutli** [comment]
No problem. I added the fields and deployed to prod. Can you check if the data created by the new fields is correct?

**Comment by b2d3c** [comment]
Great !

Only : 

- lack mention "deprecated" on "History" Feld in File Part.

After you can deploy in Prod!

Ex : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fo%2F16e72dbc-b6b8-4c8c-9b86-2808d936e427

![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/e79aa1dd-0369-4aea-a1db-edf79d6cf86e)
