### ISSUE TITLE
Batch upload : Erismann / archivalPlace (csv)

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#360]
Thanks to create this entities

[Erismann_Container_20230412-2_bdc.xlsx](https://github.com/sapa/performing-arts-ch-templates/files/11209267/Erismann_Container_20230412-2_bdc.xlsx)

**Comment by fkraeutli** [comment]
Create a new entity with a UUID that represents a box, the box is contained by rico:containedBy and has the label rdfs:label

**Comment by fkraeutli** [comment]
Produce python script, keep in account that in the future more imports like this might be made

**Comment by fkraeutli** [comment]
The type should be `http://ontology.performing-arts.ch/ArchivalPlace`. I think all the information, except the UUID should be in the Excel sheet. 
e.g. he first row
```ttl
<http://data.performing-arts.ch/p/{{UUID}}> a <http://ontology.performing-arts.ch/ArchivalPlace>;
   rico:containedBy <http://data.performing-arts.ch/p/6d18f6f2-169b-40e1-8a2b-455f969fb029> ;
   rdfs:label "Erismann-08" .
```

**Comment by olyanicolaeva** [comment]
@b2d3c Hi Baptiste, I have produced the .trig file (https://github.com/sapa/data-migration/tree/360-batch-upload-erismann). Is it ok for you if I ingest it into staging and you can have a look if it is as you expected?

**Comment by b2d3c** [comment]
Perfekt! Thanks

Le 26 avril 2023 14:23:58 GMT+02:00, olyanicolaeva ***@***.***> a écrit :

**Comment by olyanicolaeva** [comment]
a query to find all graphs with the data for this import 
`PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?graph
WHERE {
  GRAPH ?graph {
    ?s rdfs:label ?o .
    FILTER(CONTAINS(str(?o), "Erismann-"))
  }
}`

**Comment by b2d3c** [comment]
Liebe @olyanicolaeva 

I don't succed to see the results. Do I something wrong?

![image](https://user-images.githubusercontent.com/8588224/235419992-3ce38156-e584-46c1-bae5-de20ff7c4350.png)

**Comment by olyanicolaeva** [comment]
Dear Baptiste,

I found an error in the mapping, will be fixed by noon, sorry!

On May 1, 2023 9:00 AM, Baptiste de Coulon ***@***.***> wrote:

Liebe @olyanicolaeva<https://github.com/olyanicolaeva>

I don't succed to see the results. Do I something wrong?

[image]<https://user-images.githubusercontent.com/8588224/235419992-3ce38156-e584-46c1-bae5-de20ff7c4350.png>

**Comment by olyanicolaeva** [comment]
hi @b2d3c I have fixed the error: easiest way to find entities is here: https://www.dev.performing-arts.ch/resource/sapa:ArchivalLocations .

**Comment by b2d3c** [comment]
Thanks !

I notice it was a mistake on my data... Sorry...All the entities must be <rico:containedBy> in <http://data.performing-arts.ch/p/283a3c18-a524-4099-9649-c405d9436128> 

After to correct this statement, you can deploy in DEV and PROD.

Thanks in advance!

**Comment by olyanicolaeva** [comment]
@b2d3c ah ok, I will double check locally and deploy on dev first

**Comment by olyanicolaeva** [comment]
@b2d3c deployed to staging and production

**Comment by b2d3c** [comment]
Perfekt! Thanks.

PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT * 
WHERE
{
 ?carton a <http://ontology.performing-arts.ch/ArchivalPlace>;
   rdfs:label ?cartonLabel .
  FILTER regex(str(?cartonLabel), "Erismann")
}
