### ISSUE TITLE
Form:Group date (single to range)

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#363]
in Form:Group,

When we change `date:single` to `date:range` if the existing date Single (ex:2022) could be transfert to date Range Beginning would be great!

![image](https://user-images.githubusercontent.com/8588224/231740293-ab1db470-e336-472d-bbcd-e26f4d56ec29.png)

![image](https://user-images.githubusercontent.com/8588224/231740383-0c85be98-b7bc-467a-95eb-cbb0320da9d8.png)

Inverse : see #585 

Contact Person : Andri

**Comment by fkraeutli** [comment]
I looked into it and I don't think it is possible without a lot of effort since internally the single date and date range fields are completely separate fields.

**Comment by b2d3c** [comment]
Thanks to have look. Therefore, we have to let it down.
