### ISSUE TITLE
Form:Instantiation add spao:hasNote

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#364]
The property spao:hasNote is use as Statement in rico:Instantiation and displayed in Template:Instantiation but there is no Field in Form for it. Could you add it?

Ex: http://data.performing-arts.ch/o/0178f148-c3a3-42dd-836b-404b31e2e15c

![grafik](https://user-images.githubusercontent.com/8588224/232000189-080b56b9-581b-4204-a8b8-6299ddd96c8f.png)

![grafik](https://user-images.githubusercontent.com/8588224/231999971-4a2e9624-883c-44a8-a7ab-1527c7e3962b.png)

**Comment by fkraeutli** [comment]
Added field (above internal note) and deployed to Dev

**Comment by b2d3c** [comment]
Perfekt! You can deploy in PROD.

Thanks!
