### ISSUE TITLE
ArchivPlan -> delete sub-section (bug)

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#368]
Apparently, after #186, the sub-section to delete are always here.

![image](https://user-images.githubusercontent.com/8588224/234275628-c20c90c2-b76d-4d31-8deb-7ec5474dff63.png)

Could you delete them?

Thanks !

**Comment by fkraeutli** [comment]
Sorry, just to refresh my brain. I think what we did in #186 is to only mark them for deletion. Should we now delete them (i.e. their named graphs)?

The subsections marked to delete are:
```sparql
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
SELECT * WHERE {
  ?subsection crm:P3_has_note "markForDeletion" .
}
```

**Comment by b2d3c** [comment]
I have control they are not linked with entities uo and down.

PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
SELECT * WHERE {
  ?subsection crm:P3_has_note "markForDeletion".
  OPTIONAL {?subsection rico:isOrWasIncludedIn ?sursection}.
  OPTIONAL {?sousection rico:isOrWasIncludedIn ?subsection}
}

 It's no more the case. You can also delete them now. Thanks.

**Comment by fkraeutli** [comment]
Check content
```sparql
SELECT DISTINCT ?subsection (COUNT(?s) as ?num_statements) WHERE {
  GRAPH ?g {
    ?subsection crm:P3_has_note "markForDeletion" .
    ?s ?p ?o .
  }
} GROUP BY ?subsection
ORDER BY DESC(?num_statements)
```

**Comment by b2d3c** [comment]
It's fine. You can deployed in prod. Thanks!

**Comment by fkraeutli** [comment]
deployed
