### ISSUE TITLE
Start Page : Weitere Namen (why?)

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#382]
Why some alternative names are displayed in Start Page list and other not?

Example : 

![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/ed854180-3694-400c-8243-edb5d73a36f7)
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/e3f2881c-5893-4729-9cb4-ea3c43f4a25c)
URI : http://data.performing-arts.ch/a/5a64e6dc-436b-42ff-b289-65416018fac4

![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/b6c2875b-b4e6-44c2-ba2c-ba27fc123cc8)
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/13589379-c483-4da6-aa5b-1fbb40742a35)
URI : http://data.performing-arts.ch/a/a915280a-1b7f-4454-814c-a2f522f7a33a

Réponse à donner à Marcel.

**Comment by fkraeutli** [comment]
The query for the alternative names expects them to have a type defined using `crm:P2_has_type`. The alternative names for Niculin do not have types.
