### ISSUE TITLE
Bug : Template:Person/date

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#397]
We would like that in the layout of Person, the uncompleted date are not completed by default.

ex: 
2000->01.01.2000 despite 2000 as we want.
11.2000->01.11.2000 despite 11.2000 as we want.

ex: http://data.performing-arts.ch/a/7883f3fe-be91-45b1-964c-88c44ff9a6c6 

![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/7bb07118-42ee-4f0a-a214-3a9d8331a406)

![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/16904590-5e68-4f34-88d8-6ca2f7c93005)

**Comment by fkraeutli** [comment]
implemented and deployed to dev

**Comment by b2d3c** [comment]
Perfekt. You can deploy to prod. Thanks!
