### ISSUE TITLE
Layout:Instantiation display "Derived Instantiation"

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#398]
Display in "Layout:Instantiation" under "Derived instantiation" like "Instantiation" in Layout:Record and Record:Part

Record ex: https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F93d42226-045f-45ff-a6b9-40b1a2262161
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/9a5324fb-a297-4753-ab33-e53f6d6799bb)

Instantiation with Derived Instantiation ex: https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fo%2F74f416ba-863a-486d-b6d2-0e49a18482b7
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/3950bfa8-5197-42a8-bef0-dc697c7b9b43)

**Comment by fkraeutli** [comment]
Implemented and deployed to Dev

**Comment by b2d3c** [comment]
There a mistake on the direction of the relation.

We want to display the entities derived from the one, as this is display on this diagram

![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/51c39b7e-bfcb-4b49-97a8-5b09e83f2378)

Also in the layout of A (54-37-VHS-4065), we want to display a resume of B (54-37-DVD-1-Teil1) and C (54-37-DVD-1-Teil3).

A : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fo%2F74f416ba-863a-486d-b6d2-0e49a18482b7
B : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fo%2F000e63d0-caa4-4182-a1de-d5ac8c27f186
C : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fo%2Fcf8c3db6-3456-4eff-8a49-71ee93260239

## RDF
`?A rico:hasDerivedInstantiation ?B`
`?A rico:hasDerivedInstantiation ?C`

**Comment by fkraeutli** [comment]
Not sure I understood the second part, but I adjusted the query and deployed to Dev

**Comment by b2d3c** [comment]
Perfekt ! You can deploy in PROD.

[DEV](https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fo%2F74f416ba-863a-486d-b6d2-0e49a18482b7) : 
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/a43c362d-2cb1-4d1b-a4e2-318ac3732beb)
