### ISSUE TITLE
Bug ? Template: Record / thumbnail (IIIF) 

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#399]
Apparently, there is a modification of the size of the thumbnail in Template:Record between DEV and PROD.

They are more small in DEV. It's also the same if you click on.

We would like to keep in DEV and PROD the bigest size as in PROD.

Thanks in advance

PROD ex: http://data.performing-arts.ch/r/cdd58828-be0d-451f-b398-fd7b8cca0869
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/e701812f-5be9-4857-8fc0-a8749fc70178)

DEV ex: https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2Fc0055cfe-c74d-40ae-a516-e7c9ea3d2c38
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/e68ca8d4-7f6d-4a43-9f57-783162836e82)

**Comment by fkraeutli** [comment]
fixed. was side effect of #328
