### ISSUE TITLE
Bug? Template:RecordPart layout fix (Instantiation)

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#407]
Dear @fkraeutli 

After #159 just a layout fix : Instantiations must be displayed in central column as in Template:Record.

ex: DEV https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2Fffbbf497-a48a-4cf0-a770-5db2fbdd3fac
![grafik](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/f0b0cb69-a87d-4dcd-a96c-39a119906536)

**Comment by fkraeutli** [comment]
changed and deployed to dev @b2d3c

**Comment by b2d3c** [comment]
Perfekt.

DEV : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2Fffbbf497-a48a-4cf0-a770-5db2fbdd3fac
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/bdcdce50-f016-4cf4-95bf-fd3bc02eb84a)

Now, just a linked bug, if we are not log: no information display for Instantitations in Record Part Layout : 
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/c6c98da2-e8a7-4275-bac5-e85d62142211)

But it the case in Record Layout : 

ex: DEV https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F03ce7b3c-86e2-445a-ad7f-3deda03f6861
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/aeabda83-4863-418c-b5a6-ea86eeaae83c)

**Comment by fkraeutli** [comment]
There are two different displays for logged in users and guests. Guests only see information with `spao:hasArchivalStatus spav:asarm`. I added a link to the instantiation in the guest view. However, I can also make the view the same for logged in users and guests. How would you like to proceed?

**Comment by b2d3c** [comment]
Dear Florian,

I choose to let see the same for logged in users and guests. That is fall in our strategy of openness.

You can direct deploy it in PROD.

Thanks in advance!

Baptiste

**Comment by b2d3c** [comment]
In the same way, can I ask you to display the same instantiation's Informations for logged in users and guests in Template:Record?

I already ask it for RecordSet, see #148 

Thanks!

**Comment by fkraeutli** [comment]
Done
