### ISSUE TITLE
URI vocabulary has to be redirect

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#408]
The URI http://vocab.performing-arts.ch/fvrtb : 
-  must be automaticaly redirect on URL <s>https://www.performing-arts.ch/resource/spav:fvrtb</s> vocab.performing-arts.ch/fr#rtb (Sparna will don it)
- The certificat must be valid.

Use : https://www.wikidata.org/wiki/Q209020#P2888

**Comment by fkraeutli** [comment]
I'm afraid this might be a bigger issue. The configuration currently uses the platform itself to resolve http://data.performing-arts/... IRIs. The platform can only resolve one base URL, therefore we would need to implement a proxy that listens on http://vocab.performing-arts.ch and redirects to the platform.

**Comment by b2d3c** [comment]
Ok. No problem. I move it in Sprint 4 and plan it for 2024.

**Comment by fkraeutli** [comment]
I have changed the config for dev but I might have to change the DNS configuration to resolve http://vocab.performing-arts.ch (and http://vocab.dev.performing-arts.ch). Do you know where these are defined?

**Comment by b2d3c** [comment]
DNS are defined by the Compagny Hostpoint (Schweiz). I give you the access tomorrow.

**Comment by b2d3c** [comment]
I don't have had the time today... I will done it at my return from holidays in 19 February. Sorry.

**Comment by b2d3c** [comment]
Dear @fkraeutli,
to be able to give you a access to manage our DNS, you need first at all to have a custumer account by our Register : https://admin.hostpoint.ch/customer/HostpointId/NewId

**Comment by fkraeutli** [comment]
Thanks! I already have a Hostpoint account and it appears I have been added to SAPA there

**Comment by b2d3c** [comment]
Perfect! Do you need something else from our side to manage our DNS?

**Comment by fkraeutli** [comment]
I added the entry, but I need a certificate for the subdomain. I'll see if I can find out how they have been obtained for the other domains

**Comment by b2d3c** [comment]
Our website manager Compagny (Raptus) do it for us. I will ask them.

**Comment by b2d3c** [comment]
... Raptus don't do nothing with performing-arts domain...

Perhaps, it will better if you see first what was done in Past for certificate this domain.

We can always ask them after with more informations. Thanks!

**Comment by fkraeutli** [comment]
There is a task that renews the certificates automatically. I added vocab to it, but it seems that it only renews once the certificates expire (once a month). Maybe we wait for it to update the certificates automatically before I break something

**Comment by b2d3c** [comment]
We can wait. All right.

**Comment by fkraeutli** [comment]
It seems the certificate is now ok, but the redirect doesn't work. I'll have to revisit this issue

**Comment by b2d3c** [comment]
Dear @fkraeutli ,

Could you try to analyse the problem befor our next metting on Thursday ?

Thanks in advance !

**Comment by fkraeutli** [comment]
Certificate appears still to be incorrect

**Comment by b2d3c** [comment]
By my side, the warning alert is remaining.

But perhaps will be easyer to fix this certificat question through the new Apache server? We can wait on it.

**Comment by b2d3c** [comment]
Dear Florian, @tfrancart  will introduce the redirection of the URI to the new Apache server. 

Could you fix the certificat problem?

Thanks in advance!
