### ISSUE TITLE
Layout:Recording link to the Record Part

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#415]
The Link under "Record (Set)" must go on Record Part not on Record if existing.

Recording : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fw%2F05a9505b-2125-415e-bc0c-ae1b458be46b

Record Part : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F29aaa6f6-5b60-40d9-aa3e-dc9985825a98

See : #414 , #432

**Comment by fkraeutli** [comment]
![Image](https://github.com/sapa/performing-arts-ch-templates/assets/1564625/a8c6e0ba-1b42-49a7-b840-817a153280f9)

**Comment by fkraeutli** [comment]
I added RecordPart. It now displays both Record and RecordPart. Do you want to give priority and only display one? Also, should we change the label from "Record (Set)" to something else?

**Comment by b2d3c** [comment]
Thanks !
I propose :
- to change the label to : "Record Resource"
- to display only the link to the Record Part if it's existing (otherwise which of the Record)

**Comment by fkraeutli** [comment]
Changed and deployed to Dev

**Comment by b2d3c** [comment]
Perfekt! You can deploy in PROD. Thanks
