### ISSUE TITLE
Viewer IIIF Installation

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#439]
Replace Thumdbail IIIF with a real viewer IIIF 

by example : 
- Clover : https://samvera-labs.github.io/clover-iiif/

## Priorités
- Image fixe
- Son

Les fonctionnalités d'affichage de la vidéo qui fonctionne avec Vimeo ne sera pas remplacer dans une premier temps

### SPAP Record : 

- Image fixe : http://data.performing-arts.ch/r/1cf90dcf-62fe-4b07-99e9-9d863f6ee9ca
- Video : http://data.performing-arts.ch/r/aca1dc0e-3e28-4efb-8be1-a5c388ebec79
  - Recording de la video : http://data.performing-arts.ch/w/ff44bc75-ba1e-499a-8883-260bdcde5eb0
- Son (à venir, voir https://github.com/sapa/performing-arts-ch-import/issues/8) fonctionnera aussi avec une entité liée Recording.

### Memobase : 
- Son (SAPA) : https://memobase.ch/fr/search?filter[institution][0]=Fondation%20SAPA%2C%20Archives%20suisses%20des%20arts%20de%20la%20sc%C3%A8ne&filter[objectType][0]=Son&filter[access][0]=1~En%20ligne
- Video (SAPA) . https://memobase.ch/fr/search?filter[institution][0]=Fondation%20SAPA%2C%20Archives%20suisses%20des%20arts%20de%20la%20sc%C3%A8ne&filter[objectType][0]=Vid%C3%A9o&filter[access][0]=1~En%20ligne
- Image (non SAPA) : https://memobase.ch/fr/object/zbs-001-3_16_3_19 

## Documentation
Cloud SAPA : https://cloud.sapa.swiss/f/4708

**Comment by b2d3c** [comment]
@bardocuteam  : premier post mis à jour avec les informations discutées aujourd'hui.

**Comment by fkraeutli** [comment]
![Uploading Screenshot 2024-02-15 at 17.08.44.png…]()

**Comment by b2d3c** [comment]
Thanks you Florian,

In your first Exemple, I see with Clover intergration, already several advantages from the actually Situation : 

- The logo IIIF
- The Metadata Information via "More Information" (could you give me a screenshot from them?)
- The visualisation of a set of images (we have to to build a Manifest with severals images to test it)
- The display of sound (and perhaps videos).

Could you go forward the tests?

**Comment by b2d3c** [comment]
Zuerst : new Manifest für all bilder.
