### ISSUE TITLE
Bug : ebucore:duration In Form:Instantiation

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#443]
## Form:Instantiation Physical (ebucore:MediaResource)
Field : duration must `ebucore:duration` not `schema:duration`
## Form:Instantiation Virtual (premis:Representation)
In File Part, Field  : duration must `ebucore:duration` not `schema:duration`

WikiSAPA : https://wiki.sapa.swiss/index.php?title=Duration#Bugs_Form

**Comment by bardocuteam** [comment]
@b2d3c Le change a été déployé sur DEV.

**Comment by b2d3c** [comment]
Merci @bardocuteam ! Mais je n'ai pas vu de changement sur DEV ...

J'ai testé le formulaire Instantiation Physical mais la propriété utilisée pour duration est toujours schema et non ebucore comme attendu : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fo%2F6d05fc5c-9ec2-4933-9dd4-fa58edb20d96

Même chose dans le formulaire File, mais ici je dirais que comme c'est une propriété qu'on ne va plus utiliser dans ce contexte, on peut renoncer à la modification. Test https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fo%2F02a34f34-2cd9-477f-a912-16f6aaa2ad9b

**Comment by bardocuteam** [comment]
Alors le problème, est que, comme apparemment beaucoup de chose sur votre plateforme, le changement a été effacé la nuit d'après... J'ai remis le change temporairement, je te laisse valider aujourd'hui si possible et si c'est OK, je le rajoute de manière permanente à DEV et PROD.

**Comment by b2d3c** [comment]
Merci d'avoir corrigé mais j'ai toujours une déclaration schema:duration dans le formulaire physical Instantiation...

Ex: https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fo%2F9232d027-6031-4404-833a-4353f80bd0fd

Je propose de renoncer à faire ces modifications pour l'instant. Il me faut préserver tes heures(et ta patience!). Je vais en rediscuter avec les équipes. Merci de tout façon de tes efforts. On va se concentrer ensemble sur les imports.

**Comment by b2d3c** [comment]
Lieber Florian,

Wir wunschen Priorität geben an diese Issue. Danke in voraus.

See : https://github.com/sapa/performing-arts-ch-import/issues/40#issuecomment-1993919852

**Comment by b2d3c** [comment]
Thanks!

Ask for modifications:
- in `Layout:PhysicalInstantiation`  ([exemple](https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fo%2F3e760920-e498-48e8-8a74-07e80f1206de)) and in `Layout:VirtualInstantiation`  ([exemple](https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fo%2F0159811b-90c4-4225-b750-dc945ddc0106)) duration is display two time. We want to keep only that one under `Carrier type`

![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/8f6412af-7f78-498e-97f7-8de92a525431)

**Comment by fkraeutli** [comment]
I removed one of the durations

**Comment by b2d3c** [comment]
Perfekt! Thanks.

You can deploy in PROD.

**Comment by fkraeutli** [comment]
Done
