### ISSUE TITLE
IIIF in Form/Template:RecordPart

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#447]
IIIF declaration (rico:hasInstantiation) must be possible in RecordPart

Now In Record Part (section):
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/46b0155d-295f-4b59-a790-defe273714a3)
Must be : 
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/b88bd0c5-b851-419a-b662-0bb89a403ee7)

Layout must be adapted

Ex: DEV : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F27336558-111a-40de-9412-695827e5f5f1

**Comment by b2d3c** [comment]
Great. It''s working good. ex: https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F27336558-111a-40de-9412-695827e5f5f1 

You can deploy in PROD.

**Comment by fkraeutli** [comment]
Done
