### ISSUE TITLE
Bug Layout:Instantiation Location

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#448]
We don't need tow times the location informations (rico:hasOrHadLocation) in Layout:Instantitation.

ex: http://data.performing-arts.ch/o/05cdab7d-d36f-4831-b9bd-e76c1d54d447

![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/78150e91-7121-41c0-8973-57538d500514)

"Localisation" at right is enough.

**Comment by fkraeutli** [comment]
Removed and deployed to Dev

**Comment by b2d3c** [comment]
Perfekt. You can deploy in PROD.
