### ISSUE TITLE
Form:Record : Link Vimeo (bug)

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#45]
First to do : #60 

Link to Vimeo ist durch rico:hasInstantiation (in Record) aber nicht fonktionniert durch Form:Record.

Ex: http://data.performing-arts.ch/r/c88c1e73-72a3-46c5-a3de-0ba7bacfa52c

Test Vimeolink: https://vimeo.com/303518555
Test formulaire: http://data.performing-arts.ch/r/a7a8739c-f274-4749-9c7c-598789eed2be

**Comment by fkraeutli** [comment]
Issue appears to be with SPARQL test

<img width="493" alt="Screenshot 2022-10-26 at 11 32 33" src="https://user-images.githubusercontent.com/1564625/197991055-d126901b-aab2-45ea-acb4-94fdd871f109.png">

**Comment by fkraeutli** [comment]
ASK query expects http. Adjusting to accept both http and https

**Comment by fkraeutli** [comment]
Is deployed on Dev for @b2d3c to check

**Comment by b2d3c** [comment]
Great ! Can be deployed on Prod!
