### ISSUE TITLE
Layout:Person Image (Commons) / TIFF

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#450]
In link with : #328 

Script to display image from Commons don't support TIFF format.

exemple : 

- Commons : https://commons.wikimedia.org/wiki/File:Tanzpuren_Fritz_L%C3%BCdin.tif
- Wikidata : https://www.wikidata.org/wiki/Q113317983
 - SPAP : http://data.performing-arts.ch/a/406205e1-916e-479b-bec0-01659d5c4819
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/fe12e29c-6867-4eb0-8d4e-82b0e2a1c075)

**Comment by fkraeutli** [comment]
Try using `special:` Wikimedia image API

**Comment by fkraeutli** [comment]
I changed the query to use the Wikimedia Commons API for Tif images. Can you check if it works and that the other images are still displayed correctly?

**Comment by b2d3c** [comment]
Great! 
Ex: https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fa%2F406205e1-916e-479b-bec0-01659d5c4819
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/31f1e19b-4bc8-41a7-822e-78dfc2305f40)

But : 
- Could you give the link to the image on Wikimedia Common (https://commons.wikimedia.org/wiki/File:Tanzpuren_Fritz_L%C3%BCdin.tif) and not the Special Path of it (http://commons.wikimedia.org/wiki/Special:FilePath/Tanzpuren%20Fritz%20L%C3%BCdin.tif) ?
- Could you give the link to Wikimedia Commons diret in the "Wikimidia Commons" label?
- Could you display the image bigger ?
DEV : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fa%2F75d656c7-4b56-4c98-8f89-7e350829c72e
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/e85090c5-8069-4bb2-abd4-8966ad779abf)
PROD: http://data.performing-arts.ch/a/75d656c7-4b56-4c98-8f89-7e350829c72e
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/3de5359d-c91b-4d08-956a-0ed170ccc1eb)

One solution for the Size, could be to display it bigger on the right of the Page, overhead of the "External Ressource". Is it easy to do ?

**Comment by fkraeutli** [comment]
I had to do some magic in order to link to the Wikimedia page, since the image links are retrieved directly from Wikidata and they are not consistent there. Deployed the changes to Dev

**Comment by b2d3c** [comment]
Thanks! You can deploy in PROD. I have open a new Issue to display bigger the image. See #506 

If it's make sense, you can also take time in our mandat to open a request in https://phabricator.wikimedia.org/ to ask for a more consistent link between Wikidata and Wikimedia Commons.
