### ISSUE TITLE
Treeview : Limit ?

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#451]
## Problem

Apparently there is a limit of 300 to the display of the subentities of a entity in the treeview.

By example : Erismann

We have uplaod 755 Records Set: 
```
PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>
SELECT (count(*) as ?count)
WHERE {
  ?RS rico:isOrWasIncludedIn <http://data.performing-arts.ch/r/9636965d-b8e7-4009-950a-8a1f39f89456> .
} ORDER by ?identifier
```
but only teh 300 first RR are displayed in the treeview : 
- PROD : http://data.performing-arts.ch/r/9636965d-b8e7-4009-950a-8a1f39f89456 
- DEV : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F5bbf728b-7472-4864-bb94-f95fc57151f1

![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/29fc77e5-7e4c-415e-bfce-774720082c03)

## Solutions 

- Solution A : we delete this limitations but for the charging timing it's perhaps not a good option.
- Solution B : we display at the end of the list somtehing like "to see more, click here" ans this display 200 subentities more.

**Comment by fkraeutli** [comment]
Increase limit to 1000

**Comment by fkraeutli** [comment]
Deployed to dev (sorry, took me a while to revive my local SAPA development setup)

**Comment by b2d3c** [comment]
Perfect! You can deploy in PROD.
