### ISSUE TITLE
IIIF Manifest (new)

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#455]
After : #447 
## Form
In Form:RR (RecordSet, Record, RecordPart), the IIIF Field 
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/278fc42f-fcc9-4083-9de7-5b5070419b32)
must accept Manifest IIIF URI: https://media.performing-arts.ch/iiif/manifest/1553-FO-325-1.json 

## Layout
And display in Layout:RR : 
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/31da0651-6a28-4e80-9fff-6bc68bd3fdce)

The Image must be also also be display as now : http://data.performing-arts.ch/r/1cf90dcf-62fe-4b07-99e9-9d863f6ee9ca
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/e7fd297b-206b-405e-b762-28c2c13acc88)

**Comment by fkraeutli** [comment]
We need a way to distinguish IIIF (Image) URLs from IIIF Manifests. e.g. through a vocabulary.

Currently, the IIIF Image URLs are retrieved with the following query:
```
$subject rico:hasInstantiation $value .
FILTER(CONTAINS(STR($value), "media.performing-arts.ch/iiif"))
```

In addition, the INSERT query adds the following types to the IIIF Image URL
```

**Comment by b2d3c** [comment]
Dear Florian, we have indeed add last Year, with @bardocuteam, a new vocabulary Entity for Manifest : https://www.performing-arts.ch/resource/spav:fvman

Sorry to have forgotten to said it to you.

**Comment by fkraeutli** [comment]
I'm adding the input form and will visualise it as a link. For the actual Image, it will probably make sense to use #439

**Comment by b2d3c** [comment]
Perfect for me.

**Comment by fkraeutli** [comment]
I added it preliminary to the Record form. Can you have a look before I add it to the others?

**Comment by b2d3c** [comment]
It's great.

ex: https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F242724e6-bec6-41a9-95ec-0fabd3f90491

![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/9c011133-275a-4984-836f-6e279a152ea4)

Only, if we edit the notice, the IIIF Image Link is completed automatically and display a Error.

![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/2928acfd-542e-4d9f-9f07-d234548ca0bc)

![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/64fa1249-1d24-4178-a6e9-73cedc49d8dd)

**Comment by fkraeutli** [comment]
Ah I see. The select statement of the IIIF fields queries not by carrier type, but filters based on the URI. I'll change it

**Comment by fkraeutli** [comment]
It's fixed on Dev

**Comment by b2d3c** [comment]
Great. You can deploy in PROD. Thanks !

**Comment by b2d3c** [comment]
I have seen that the entity "Manifest" created through the form have no type.

ex: https://www.dev.performing-arts.ch/resource/?uri=https%3A%2F%2Fmedia.performing-arts.ch%2Fiiif%2Fmanifest%2F1553-FO-325-1.json

Could you add in the workflow this statement :
`?item a rico:Instantiation`

As for image : https://www.performing-arts.ch/resource/?uri=http%3A%2F%2Fmedia.performing-arts.ch%2Fiiif%2F3%2Fimage%252F1004-8-13

**Comment by fkraeutli** [comment]
Deployed to Prod
