### ISSUE TITLE
Layout:Instantiation display spao:lastControl

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#472]
Display valu of `spao:LastControl` : only with loging

Label : "Last Control"

Localisation in Layout : left bottom

**Physical**

```
PREFIX ebucore: <https://www.ebu.ch/metadata/ontologies/ebucore#>
PREFIX spao: <http://ontology.performing-arts.ch/>
SELECT * WHERE {
  ?sub spao:lastControl ?obj. a ebucore:MediaResource.
} LIMIT 100
```
**Virtual**
```
PREFIX ebucore: <https://www.ebu.ch/metadata/ontologies/ebucore#>
PREFIX spao: <http://ontology.performing-arts.ch/>
SELECT * WHERE {
  ?sub spao:lastControl ?obj.
  MINUS {?sub a ebucore:MediaResource}.
} LIMIT 100
```

ex: http://data.performing-arts.ch/o/63c524f5-f59b-45e1-b382-e0021b13a7ad

**Comment by fkraeutli** [comment]
Only for logged in users

**Comment by fkraeutli** [comment]
Deployed to dev

**Comment by fkraeutli** [comment]
deployed to Dev

**Comment by b2d3c** [comment]
Sound good! 

Could you only check the invalid date format message. Ex; https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fo%2Fc54cbd59-0977-4e0d-9150-e16566a7c020

**Comment by fkraeutli** [comment]
Invalid dates are now displayed in the unformatted format. Would you like to display an indicator, that it is invalid?

<img width="184" alt="Screenshot 2024-02-08 at 10 27 34" src="https://github.com/sapa/performing-arts-ch-templates/assets/1564625/110192e7-190b-4cc4-871e-7a4efee62f3c">

**Comment by b2d3c** [comment]
Thanks! You can deployed like this in PROD. I will done a Issue on transform the data under valid format.
