### ISSUE TITLE
Layout:Group ->Produktionen-> CSV download

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#478]
In the same way as #239 

We want to add a CVS dowload button on the Tab "Productions" of Layout:Group

Ex: [DEV](https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fa%2F7520b91c-cc0c-446c-b507-63d89806efb1&semanticSearch=N4IgziBcoNZQrAGhAEwPZRAMwE4CMc01IAxAJngH0AFAUxyzRwFsBDAOwGNaaAbDkAF9kWKAG0AuoKA)

**Comment by fkraeutli** [comment]
Added and deployed to Dev

**Comment by b2d3c** [comment]
Ok !
Could I ask you tow things more :
- add the name of the group in the name of the file csv (and if isn't too complex YYYYMMDDHHMMSS)
- in export CSV add one column with the URI of `frbroo:F25_Performance_Plan` who is linked on the title in the Plateforme list

Thanks in advance

**Comment by fkraeutli** [comment]
Changed and deployed to Dev. Can you check if it is the right URI for the performance plans?

**Comment by b2d3c** [comment]
Perfekt! You can deploy in PROD. Thanks.
