### ISSUE TITLE
Bug "Bearbeitung"

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#479]
Nach einem neuen Import von docuteam, wir haben ein bug mit einigen Instantiationen. Wir schaffen nicht mehr zu bearbeiten.

Könntest du es analysieren und uns Empfehlungen geben ?

Danke sehr in voraus

Baptiste

Ex: http://data.performing-arts.ch/o/983531af-effe-4d57-8140-00c7e7abfb36

![Bug_Bearbeitung](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/503d381f-3518-4f6f-8bd0-f7486df3810b)

**Comment by b2d3c** [comment]
Pour information : @bardocuteam @bilvin

**Comment by fkraeutli** [comment]
Possibly related to field `RecordResourceDateType`

**Comment by fkraeutli** [comment]
<img width="782" alt="Screenshot 2023-12-08 at 11 13 04" src="https://github.com/sapa/performing-arts-ch-templates/assets/1564625/6ac51672-f68d-4e83-a55b-b9fb924527ba">

This seems to be the issue. preparationDate should be a URI, not a string. See for example http://data.performing-arts.ch/o/0b9677bb-9425-450d-b208-0951bed7aadb:

<img width="477" alt="Screenshot 2023-12-08 at 11 14 07" src="https://github.com/sapa/performing-arts-ch-templates/assets/1564625/7d34a7e4-f917-4fa4-b41b-a44740b3fdfb">
