### ISSUE TITLE
Bug : Vimeo URL

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#480]
Lieber @fkraeutli ,

Vimeo hat seine URL geändert und es passt nicht mehr mit die embeded display in unsere Plateforme.

Er hat zu tun mit 1* / oder 2* //

Zuerst war nur ein / : https://vimeo.com/796986143

![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/772392a0-90b0-4d95-8041-07cbcddb1635)

https://www.performing-arts.ch/resource/?uri=https%3A%2F%2Fvimeo.com%2F796986143

Jetzt zwei : https://vimeo.com/829431017/049bce635c

![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/6606d6fd-8102-44a1-a640-8170569171d5)

https://www.performing-arts.ch/resource/?uri=https%3A%2F%2Fvimeo.com%2F829431017%2F049bce635c

Ex:  
Record : http://data.performing-arts.ch/r/590a2584-af98-4a60-b2b5-432990e3c921

![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/39300f4a-f237-44ec-b4ec-2a6414646b2b)

![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/12f1068f-f2de-4cad-8796-5de19f6b7685)

Instantiation : https://www.performing-arts.ch/resource/?uri=https%3A%2F%2Fvimeo.com%2F829431017%2F049bce635c

Recording : http://data.performing-arts.ch/w/911fb2d3-7d1c-437e-8b1e-cf030447c189

![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/55a1ee31-3b82-4ef7-8071-f95d8b0cf7dd)

**Comment by fkraeutli** [comment]
Hi @b2d3c,

kann ich machen, aber der zweite Teil scheint ein Tracking Code zu sein, den ihr evtl. nicht in eurer Datenbank haben möchtet.

Link mit Tracking: https://vimeo.com/829431017/049bce635c

Link ohne, funktioniert auch: https://vimeo.com/829431017

**Comment by b2d3c** [comment]
Danke sehr @fkraeutli ! Es ist Perfekt.

Wir probieren ohne Tracking. Kein Änderung benusst denn.
