### ISSUE TITLE
Bug : Record -> Instantiation

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#481]
Lieber @fkraeutli 

Wir haben ein Problem nach ein Import von docuteam : [#sapa/performing-arts-ch-import/issues/18](https://github.com/sapa/performing-arts-ch-import/issues/18)

When wir korrigieren etwas in rico:Record durch Formular (ex: Vimeo link), den Link an die Instantiation sind verloren...

Zu Biespiel : 
Record : http://data.performing-arts.ch/r/909c7900-ec55-4428-85c9-fc2a804ac0aa
Instanciation AM : http://data.performing-arts.ch/o/ba85c8d3-aeb2-44ff-9286-c90c0e8567b0
Instanciation DC : http://data.performing-arts.ch/o/346bcf07-2ea7-4f38-b7c9-72674d510e5b
Instanciation Vimeo : https://vimeo.com/829444160/11c2293154 -> https://www.performing-arts.ch/resource/?uri=https%3A%2F%2Fvimeo.com%2F829444160%2F11c2293154
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/3983463d-47aa-42f1-a98c-9833c0326f78)

After Bearbeitung durch Formular über Vimeo link : 
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/45b18346-d788-4144-b60e-7a3a84515853)

Könntest du uns helfen zu verstanden wo ist den Problemen?

Du kannst versuchen mit : http://data.performing-arts.ch/r/c4e80ca7-af5f-41ff-992c-3578f5761016

**Comment by fkraeutli** [comment]
Hi @b2d3c , ich sehe im Formular kein Feld, welches die `rico:hasInstantiation` links macht. d.h. wenn man auf Edit klickt werden die Instantiations nicht geladen und beim speichern gelöscht. Wurden die Instantiations über die Formulare verlinkt oder auf anderem Weg?

**Comment by fkraeutli** [comment]
Hi @b2d3c , ich sehe im Formular kein Feld, welches die `rico:hasInstantiation` links macht. d.h. wenn man auf Edit klickt werden die Instantiations nicht geladen und beim speichern gelöscht. Wurden die Instantiations über die Formulare verlinkt oder auf anderem Weg?

**Comment by b2d3c** [comment]
Hi @fkraeutli : die `rico:hasInstantiation` sind in Form:Instantiation (unten "Record (part)*) seebar, aber das Statement ist in Record.

Beispiel : 
 - Instantiation : http://data.performing-arts.ch/o/173ddad5-0a77-4a42-b193-de09817eb475
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/48f9e61a-f6b4-41f9-b9fc-e0f303b306f5)
  - Record : http://data.performing-arts.ch/r/c4e80ca7-af5f-41ff-992c-3578f5761016
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/bf30ee7b-d7bf-46dc-adcf-045df870c904)

**Comment by fkraeutli** [comment]
Ah, das Problem scheint mir, dass die Information im Named Graph für den Record ist, aber im Instantiation Form bearbeitet wird. Wie wurde der Datensatz erzeugt?

<img width="1496" alt="Screenshot 2023-12-14 at 15 10 06" src="https://github.com/sapa/performing-arts-ch-templates/assets/1564625/39c478ca-8538-40dc-a518-a0e5cd6a9f97">

**Comment by b2d3c** [comment]
Danke @fkraeutli ! 

Ich habe die Informationen weiterflogen an docuteam : https://github.com/sapa/performing-arts-ch-import/issues/18#issuecomment-1858789615
