### ISSUE TITLE
Link to a externe Resource : RDF?

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#492]
In the Record Resource statements, we want to add a hyperlink to allow to have access to a document (like PDF) hosting on a external Server.

ex:  hosting on our Nextcloud serveur : https://cloud.sapa.swiss/s/Bpoo56qtRyjtWdA

Which RDF property could we use for that?

Ex: http://data.performing-arts.ch/r/6b53d907-7f61-4b03-84d5-7e334ab849f2

**Comment by tfrancart** [comment]
To answer, I need to understand on which type of object you want to assert this ?
And the type of document you want to point to. It is a "representation" of the described resource ? is it a document that explains something about it ? is it a kind of "see also" link ?

You also mentionned you wanted to _"Ajouter un texte explicatif, soit sur le lien, soit en plus."_

**Comment by b2d3c** [comment]
We want to add a link to a "Inventaire" in Format PDF. 

Something like : https://archives.bge-geneve.ch/archive/fonds/chaponniere_francis

![grafik](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/addbf7ab-e11e-4db7-963c-2578d06b24e5)

**Comment by b2d3c** [comment]
C'est une très bonne question. 

Deux options s'offre à nous j'ai l'impression :

version A : le plus propre sémantiquement serait en effet de décrire l'inventaire comme Record (dans la série des inventaires créés par l'institution) et alors sa version numérique serait une de ses instanciations.

version B : utiliser rdfs:seeAlso pour renvoyer vers une ressource externe lamda depuis la notice du fonds. Mais quelle est la valeur attendu de cette propriété? Est-ce que l'on peut imaginer une entité riche de type lien URL + texte?

**Comment by tfrancart** [comment]
On veut relier un rico:RecordSet qui est un fonds vers un PDF qui donne la description détaillée de ce fonds. Voir si dans RiC-O il y aurait une propriété adéquate.

**Comment by fkraeutli** [comment]
maybe `crm:P70i_is_documented_in`

**Comment by b2d3c** [comment]
Cher @bilvin  ,

Comme tu le verras plus haut nous cherchons une propriété RDF RiC pour faire un lien depuis une notice de fonds vers une version PDF de l'inventaire.

Florian de SARI a proposé `crm:P70i_is_documented_in` mais n'y aurait-il pas quelque chose dans RiC pour exprimer cela?

Merci d'avance de tes lumières!

**Comment by bilvin** [comment]
Cher @b2d3c ,

Il a (au moins) trois possibilités:

1. rico:isOrWasDescribedBy qui doit pointer vers un rico:RercordRessource dont l'inventaire est une rico:Instantiation.
2. approche similiare mais en utilisant la relation-objet rico:RecordResourceToRecordResourceRelation , qui a l'avantage de pouvoir être qualifée avec un type p.ex. ex:hasInventory
3. si l'on veut s'éviter la création d'un rico:RecordRessource pour l'inventaire et pointer directement vers un rico:Instantiation on peut utiliser la relation objet rico:RecordResourceToInstantiationRelation (que l'on peut également qualifier avec un type)

A dispo au besoin pour discuter la question plus en détail.

**Comment by b2d3c** [comment]
Merci beaucoup @bilvin !

Nous allons explorer cela!

**Comment by b2d3c** [comment]
Cher @bilvin 

J'y avais renoncé mais, en suivant ton conseil, je vais créer une instantiation (et peut-être son Record) pour nos anciens inventaires PDF.

Toutefois, ma question initiale demeure simplement en la déplaçant dans la rico:Instantiation, à savoir : 

Quelle propriété utiliser dans une rico:Instantiation pour permettre au public d'accéder à un version PDF du document hébergé sur une serveur distant (ex: https://cloud.sapa.swiss/s/Bpoo56qtRyjtWdA)

Merci encore d'avance de tes conseils

**Comment by b2d3c** [comment]
Visiblement la question se gère plutôt au niveau du layout de la plateforme à travers un URI spécifique (ex : IIIF) et pas vraiment à travers une propriété RDF spécifique.

J'ai ouvert un ticket en ce sens : https://github.com/sapa/performing-arts-ch-templates/issues/555

Exemple : https://www.performing-arts.ch/resource/?uri=http%3A%2F%2Fmedia.performing-arts.ch%2Fiiif%2F3%2Fimage%252F181-10-1_001
