### ISSUE TITLE
SPARQL EndPoint : CORS

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#493]
We have plan to use : https://sparnatural.eu/demos/demo-sapa/ (demo)

We need to fix the CORS : http://docs.sparnatural.eu/SPARQL-proxy.html

**Comment by fkraeutli** [comment]
@b2d3c I did the adjustments in dev.performing-arts.ch. Do you have the ability to test it?

**Comment by tfrancart** [comment]
Unfortunately this is not correct. The CORS responses headers are duplicated (`Access-Control-Allow-Headers`, `Access-Control-Allow-Methods`, `Access-Control-Allow-Origin`,`Access-Control-Max-Age`)

![image](https://github.com/sapa/performing-arts-ch-templates/assets/2728945/cea3871e-0ade-4770-83b1-f2ac1aacc7d4)

This is triggerring an error:

![image](https://github.com/sapa/performing-arts-ch-templates/assets/2728945/51647691-36f4-4e90-a4c9-bae43268117c)

Let me know when I can make further tests

**Comment by tfrancart** [comment]
If it helps, you can test yourself by issuing the following request and make sure the CORS headers in the response are correct (= not duplicated, and allowing queries from other domains):

`https://www.dev.performing-arts.ch/sparql?query=PREFIX%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0ASELECT%20DISTINCT%20%3Furi%20%3Flabel%20WHERE%20%7B%0A%20%20%3Fdomain%20rdf%3Atype%20%3Chttps%3A%2F%2Fwww.ica.org%2Fstandards%2FRiC%2Fontology%23Record%3E%3B%0A%20%20%20%20%3Chttps%3A%2F%2Fwww.ica.org%2Fstandards%2FRiC%2Fontology%23hasOrHadLocation%3E%20%3Furi.%0A%20%20%3Furi%20rdfs%3Alabel%20%3Flabel.%0A%20%20FILTER(((LANG(%3Flabel))%20%3D%20%22%22)%20%7C%7C%20((LANG(%3Flabel))%20%3D%20%22en%22))%0A%20%20FILTER(ISIRI(%3Furi))%0A%7D%0AORDER%20BY%20(UCASE(%3Flabel))%0ALIMIT%20500&format=json`

**Comment by tfrancart** [comment]
Dear @fkraeutli 

To test : 

1. go to https://sparnatural.eu/demos/demo-sapa/
2. Click on "switch to dev" on the upper right of the query editor. This will switch the query editor to your dev server.
![image](https://github.com/sapa/performing-arts-ch-templates/assets/2728945/78dd4895-fc27-485f-b772-7850ade1c444)

3. Make a dummy query, like Record > see also > Record = any"
![image](https://github.com/sapa/performing-arts-ch-templates/assets/2728945/0dcb28df-b7a5-4035-a158-59234a0467f6)

![image](https://github.com/sapa/performing-arts-ch-templates/assets/2728945/eabad083-4b12-4d7c-b6a6-c8c3740ec682)


4. Click on the green play button to execute the query
5. See your browser console where the error happens
![image](https://github.com/sapa/performing-arts-ch-templates/assets/2728945/dc6f33b7-4e15-44bf-883d-b7ea7eff2d43)

I however acknowledge that I have the same behavior as you using curl.

Best Regards
Thomas

**Comment by fkraeutli** [comment]
Thank you Thomas! I can see the CORS error now. In my case it is not present at all rather than twice, but either way I will try to fix the issue

**Comment by fkraeutli** [comment]
Hmm I haven't changed anything but now it seems to work. Can you verify?

<img width="1392" alt="Screenshot 2024-02-15 at 10 08 48" src="https://github.com/sapa/performing-arts-ch-templates/assets/1564625/4d2e25df-63b9-4884-8db8-9757644df759">

**Comment by fkraeutli** [comment]
Appears to be working now

<img width="1392" alt="Screenshot 2024-02-15 at 10 16 23" src="https://github.com/sapa/performing-arts-ch-templates/assets/1564625/019b41ad-8b9d-4ea4-9512-8ada0371080d">

**Comment by tfrancart** [comment]
Yes, good for me !

**Comment by b2d3c** [comment]
Thanks Florian !
