### ISSUE TITLE
Form:Record Ressource / rico:hasOrHadSubject (bug)

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#513]
We succed not to do the link through the Form between Seewen (SZ) `rico:hasOrHadSubject` Kabarett-Tour

`<http://data.performing-arts.ch/r/800008d6-0b2a-436e-a164-7cc83bbe3052> rico:hasOrHadSubject <http://data.performing-arts.ch/a/6db53e38-e549-407b-bb3b-cf190691ca64>`

Otherwise, we have other exemples of link between a Record Resource and a Festival : 

`<http://data.performing-arts.ch/r/a1d957dc-feee-445f-af3b-1468afc3bc17> rico:hasOrHadSubject <http://data.performing-arts.ch/a/8a72398a-325c-4fc8-acaa-41ab228c2d66>`

See also : #174

Demande : Andri

**Comment by fkraeutli** [comment]
The search results were filtered based on the language of their place label. The _Kabarett-Tour_ entity had a place label but without a language. Since the place label isn't actually used, I removed the filter. The entity now shows up when I try it locally.
I deployed the changes to Dev.

**Comment by b2d3c** [comment]
Great. You can deploy in PROD. 

What's our advise : we need to specified always the language label in place? It will be a good pratices, isn't it?

**Comment by fkraeutli** [comment]
Yes it would be good practice. I'm not sure why the above search used it, but it did expect it to be there

**Comment by fkraeutli** [comment]
deployed to Prod
