### ISSUE TITLE
introduce ebucore:frameRate in Form and Layout

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#518]
value of property `ebucore:frameRate` in `premis:File` is already displayed in `Layout:VirtualInstantiation`. ex: http://data.performing-arts.ch/o/97526076-92d1-466e-bb0f-6b00e17c480f

values : literals

We want to : 
- add it in `Form:VirtualInstantiation` under File ([exemple](https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fo%2F983531af-effe-4d57-8140-00c7e7abfb36))
- add it in `Form:PhysicalInstantiation` ([exemple](https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fo%2F3e760920-e498-48e8-8a74-07e80f1206de))
- display value in `Layout:PhysicalInstantiation` under "Frame rate" label.

**Comment by b2d3c** [comment]
Diese Issue hat  eine Höhe Priorität für uns. Danke in voraus.

See : https://github.com/sapa/performing-arts-ch-import/issues/40#issuecomment-1993919852

**Comment by fkraeutli** [comment]
added and deployed to Dev

**Comment by b2d3c** [comment]
Thanks !

One modification : 
- in  `Layout:PhysicalInstantiation` display the label and the value under `Carrier type`. [Exemple](https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fo%2F3e760920-e498-48e8-8a74-07e80f1206de)

**Comment by fkraeutli** [comment]
Done (dev)

**Comment by b2d3c** [comment]
Perfekt! You can deploy in PROD.

**Comment by fkraeutli** [comment]
Done
