### ISSUE TITLE
Viewer IIIF Clover in Layout:RecordResource

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#528]
After #455 and  the analyse https://github.com/sapa/performing-arts-ch-templates/issues/439

We would like to implement it in Layout:RecordResource

Test : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F242724e6-bec6-41a9-95ec-0fabd3f90491

See also :  implementation viewer IIIF Clover in Layout:Instantiation https://github.com/sapa/performing-arts-ch-templates/issues/527 

SAPAwiki : https://wiki.sapa.swiss/index.php?title=IIIF/Clover/SAPA

**Comment by b2d3c** [comment]
First https://github.com/sapa/performing-arts-ch-import/issues/27

**Comment by b2d3c** [comment]
Dear @fkraeutli 

Could be possible to publish Clover viewer only for Record with Manifest IIIF declaration ?

ex: https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F242724e6-bec6-41a9-95ec-0fabd3f90491

**Comment by fkraeutli** [comment]
Implemented and deployed to Dev

**Comment by b2d3c** [comment]
Great!

I have done a try with a multiimages Manifest : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2Fed561d97-f759-4acc-8aaa-e314ad745cd6

Just two asks:
- is it possible to display the IIIF logo?
- could we have the botton to modificated and to display in full screen ([demo](url))

![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/73b4be9d-8d44-414c-a532-a8cf48cb93a2)
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/c8009548-0195-4f4e-a572-1c0a57d8485e)

**Comment by fkraeutli** [comment]
Done (dev)

**Comment by b2d3c** [comment]
Great! Thanks for the full screen mode.

The fonction "More information" is not adated for our layout (see examples). I would propose to disable it but to keep the logo "IIIF" and to add the infobubble fonctionnality as in the demo

Demo : https://samvera-labs.github.io/clover-iiif/docs/viewer/demo
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/4cac82a9-ecd2-4545-8977-d1c1f49a955b)

## "More information" problems
[exemple 1](https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2Fed561d97-f759-4acc-8aaa-e314ad745cd6)
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/9c0f3de5-b58b-41d1-b9d9-69bc2dccfbc9)
[exemple 2](https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F590a2584-af98-4a60-b2b5-432990e3c921)
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/4e09eea6-64db-4932-80e4-a077f281c820)

**Comment by b2d3c** [comment]
I have notice also a probleme with the title. It to big and it's display on serverals lines.

exemple : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2Fb659ff99-38b1-4bd8-ae4c-f6da42c67391
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/f0b094b6-9238-4917-ba34-eb07fe07f473)

Cloud you hack it to choice a smaller typo?

**Comment by fkraeutli** [comment]
I removed the more information toggle and I think that also improved the rendering of the title

**Comment by b2d3c** [comment]
Great!

Title is ok! Thanks.

The last thing missing is the infobubble with Manifest's link to copy

![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/4cac82a9-ecd2-4545-8977-d1c1f49a955b)

**Comment by b2d3c** [comment]
Dear @fkraeutli ,

Could you give a priority to this Issue?

We need this tool to publish our sound files. ex: https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2Fb659ff99-38b1-4bd8-ae4c-f6da42c67391 

Thanks in advance!

**Comment by fkraeutli** [comment]
Take current version to prod

**Comment by fkraeutli** [comment]
Deployed to prod

**Comment by b2d3c** [comment]
Geat !

Can you remove the label "IIIF Manifest" who come from #455 ?
Dev: https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F2f1db9d4-4b0d-4133-870a-d5a76a439074
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/3bfe70dc-be84-47a2-8c2f-2aa0bc52f0c9)

**Comment by b2d3c** [comment]
Florian lack only this change to close the Issue : 
> 
> Can you remove the text "IIIF Manifest" who come from #455 ? Dev: https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F2f1db9d4-4b0d-4133-870a-d5a76a439074

**Comment by fkraeutli** [comment]
Done (Dev)
