### ISSUE TITLE
Layout:RecordResource change french label of spao:hasCopyrightDeclaration

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#545]
After #544 

In `Layout:RecordResource`, we would like to change the French label of : `spao:hasCopyrightDeclaration`

<s>Déclaration sur les droits d’auteur</s> -> Clarification des droits d'auteur par SAPA

**Comment by fkraeutli** [comment]
changed and deployed to Dev and Prod

**Comment by fkraeutli** [comment]
sorry, reverted change on Prod since it caused an error. Will fix error and deploy to Dev only

**Comment by fkraeutli** [comment]
It's on Dev (sorry, forgot to notify)

**Comment by b2d3c** [comment]
Perfekt ([DEV](https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F10a5fee2-335e-46ef-857c-8bde7c1f6829)) . You can deploy in PROD. Thanks
