### ISSUE TITLE
Form:RecordPart add IIIF Manifest + display in Layout:RecordPart

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#546]
In `Form:Record->Record Part` we want to add the `IIIF Manifest` Field, as in Form:Record and to display the value in `Layout:RecordPart` (see #455 )

Exemple

Record : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2Ff30f1788-3258-439b-b249-cc1ab39033a9
Record Part : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F79051131-2070-4426-8283-0bec1a1ae009

![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/ef7b0345-cb70-4f93-bccf-aa1f79de3b45)

**Comment by fkraeutli** [comment]
Add viewer to Record part template

**Comment by fkraeutli** [comment]
Added and deployed to Dev

**Comment by b2d3c** [comment]
Great ! You can deploy in PROD. Thanks
