### ISSUE TITLE
Layout:Group (bug)

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#547]
in Group Entities if many values of `crm:P2_has_type` ->`spav:vr`

ex: https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fa%2F0480d10a-cf95-49e2-b193-c6c854a3a912

We want to display them with a comma : <s>AgenturVeranstalter</s> Agentur, Veranstalter

![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/4ac3bc6b-6266-4ac0-a9fc-c405a7908e65)

Demande : uk

**Comment by fkraeutli** [comment]
Fixed and deployed to Dev and Prod.

**Comment by b2d3c** [comment]
Perfekt! Thanks
