### ISSUE TITLE
Create page https://ontology.performing-arts.ch

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#554]
We want to publish our own ontology SPAO as OWL.

We choice to done it under the pages with URL : https://ontology.performing-arts.ch

Cloud we ask you to : 
- open the folder on our server
- configure our DNS
- publish the content you will find here : https://github.com/sapa/swiss-performing-arts-documentation/issues/1#issuecomment-2016973212

For any questions, ask @tfrancart 

Thanks in advance !

**Comment by b2d3c** [comment]
Dear @fkraeutli ,

could you see this Issue before our Metting tomorrow, to be aeble to say us if it's complex to do? Or if we could give this work to do to docuteam because there is no nessecity to be done by you.

Thanks in advance!

**Comment by fkraeutli** [comment]
Created new VM

**Comment by b2d3c** [comment]
For information @tfrancart, Florian created a new VM With Apache server. You will have soon access on it.

**Comment by b2d3c** [comment]
Laks only the certificat (see https://github.com/sapa/swiss-performing-arts-documentation/issues/1#issuecomment-2110608666) and then we can close this Issue

**Comment by b2d3c** [comment]
Ok. I can also close the Issue!
