### ISSUE TITLE
PDF preview in Plateforme

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#555]
After #532 #492 ,

We choice to use <s>nextcloud serveur of SAPA (https://cloud.sapa.swiss) </s>  S3 to store PDF. Voir https://github.com/sapa/performing-arts-ch-import/issues/51

We want to add : 
-  in `Form:RecordResource`, a Feld to be able to add the link to a PDF document hosting on <s>SAPA cloud (ex: https://cloud.sapa.swiss/s/Bpoo56qtRyjtWdA)</s> S3 ->create a rico:InstanTiation. As for IIIF (https://www.performing-arts.ch/resource/?uri=http%3A%2F%2Fmedia.performing-arts.ch%2Fiiif%2F3%2Fimage%252F181-10-1_001)
- In `Layout:RecordResource`, add a preview from PDF and a link to the resource on SAPA cloud.

**Comment by fkraeutli** [comment]
update: I have started including a PDF viewer but need to make some server configuration changes to make it work. Test here: https://www.dev.performing-arts.ch/resource/sapa:pdfTest

**Comment by b2d3c** [comment]
> Do we have a type for the PDF? Assuming the PDF should be added through
> 
> ```sparql
> $subject rico:hasInstantiation $value .
> $value rico:hasCarrierType spav:<carrierTypeForPDF>
> ```

I have ask for it Sparna : https://github.com/sapa/swiss-performing-arts-documentation/issues/3#issuecomment-2093117351

**Comment by b2d3c** [comment]
> @b2d3c I managed to adjust the configuration at our end, however the PDFs are not loading from the SAPA cloud due to CORS errors. Is it possible to adjust the CORS headers on the cloud?
> 
> ![Image](https://private-user-images.githubusercontent.com/1564625/327743850-77cb97c3-2b7b-4a67-ba2f-49de37f2f276.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3NDQxODEsIm5iZiI6MTcxNDc0Mzg4MSwicGF0aCI6Ii8xNTY0NjI1LzMyNzc0Mzg1MC03N2NiOTdjMy0yYjdiLTRhNjctYmEyZi00OWRlMzdmMmYyNzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDNUMTM0NDQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmQ3ZDQ5Y2ZlMzU2YTk0Nzg2NmVjZDM1MjFlOGVlYjFhY2E5MDdkNDBiYWQ4ZWJmMzc1MjQyNDM0ZTZhMDYyOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._OUpPrFRFh-H0AkJIIG6Hm6udDGbLdNeb5Znrtj0QRk)

I have send a mail today to oriented.net who host our cloud. They will contact you or make directly the changes.

**Comment by b2d3c** [comment]
Answer from Oriented.net : 

> There is an app "WebAppPassword" that you can enable on your wölkli private installation (cloud.sapa.swiss) that sets allowed origins for your installation:
> 
>     https://apps.nextcloud.com/apps/webapppassword
> 
> Could you try installing this app and configure it to allow your application and see if that works?

It seems to me a little complex. I would propose to display in a first time only the link. See #595

**Comment by b2d3c** [comment]
It should be a solution through our server (via S3). @bardocuteam will send you, Florian, a new URL to check.

**Comment by bardocuteam** [comment]
Hey @fkraeutli, here is an URL to a PDF on the media server:
https://media.performing-arts.ch/document/SAPA_Jahresbericht_2022_FR-1-1.pdf

**Comment by fkraeutli** [comment]
@bardocuteam Perfect, that is working

**Comment by b2d3c** [comment]
Dear @fkraeutli could you give us the link to the exemple ?

**Comment by fkraeutli** [comment]
I update the test link and it works: https://www.dev.performing-arts.ch/resource/sapa:pdfTest
Where do you want to add the viewer in the template(s)?

**Comment by b2d3c** [comment]
You can display it in the same place of Viewer IIIF in Layout:Record.

In Form:Record, you can add the Feld in IIIF zone. Label "PDF/S3".

Test : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F24028542-e5e5-4821-b05d-4b86dfbe9ad4

**Comment by fkraeutli** [comment]
Preview added and deployed to Dev

<img width="1912" alt="Screenshot 2024-06-20 at 12 37 50" src="https://github.com/sapa/performing-arts-ch-templates/assets/1564625/e7de3c24-2653-41dd-8743-dff5d126aa1c">

**Comment by b2d3c** [comment]
Great! 

3 Remarks :  
1) You choose to use in Form the same box as SAPA Cloud. It's good but we have to change label. I propose "Related Documents (SAPA Cloud, S3)"
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/7f722224-2a22-483d-a3f7-cef8ac096147)
2) We don't need a label in Layout. No "PDF/S3"
3) Could we have a size of the Viewer more in A4 proportions?

**Comment by fkraeutli** [comment]
Changed and deployed to Dev

**Comment by fkraeutli** [comment]
Done

**Comment by b2d3c** [comment]
I see that the viewer in a empty form, come too in case of no declaration.

DEV : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F9ebba1c1-6e38-4e20-8eeb-aac405422145
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/1d978f44-73e6-48f2-89ea-36345756009f)

PROD : http://data.performing-arts.ch/r/7831486c-8693-4d46-aedc-7b89fb13c0d7
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/f6503ab7-852b-4f86-9692-fe29d84fa503)

**Comment by fkraeutli** [comment]
The issue is that the carrier type we use for PDF (`spav:fvonl`) is also used for other things. I added a filter that queries for the extension `.pdf` to account for this.

Changed and deployed to Dev and Prod

**Comment by b2d3c** [comment]
Thanks a lot !
