### ISSUE TITLE
Form:Instantiation(File) disconnect ebucore:aspectRatio with spav:ar

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#575]
After #514  and https://github.com/sapa/performing-arts-ch-import/issues/37

Disconnect `ebucore:aspectRatio` with `spav:ar` :

- in `Form:PhysicalInstantiation `([DEV](https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fo%2F0a40c922-206b-4ea2-9def-e0124b7311d7))
- In `Form:VitualInstantiation/File`  ([DEV](https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fo%2F107ca518-87f7-4aba-9c4f-d0b7815f799e))
 
`ebucore:aspectRatio` must have a `string` value.

**Comment by fkraeutli** [comment]
I deployed the change to Dev. Can you check if it is correct?

**Comment by b2d3c** [comment]
I have add exemples in first post,

The modification must be done in `Form:PhysicalInstantiation`  and in `Form:VitualInstantiation/File`

In my test, the property is well disconneted but I can be succed to add string value through the Field.

**Comment by fkraeutli** [comment]
Got it, changed and deployed to dev

**Comment by b2d3c** [comment]
Only the layout is strange : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fo%2F0a40c922-206b-4ea2-9def-e0124b7311d7

Form : 
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/1c43c162-6ce9-4e2f-b57e-561e754878cd)
Layout:
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/5fbac20d-3985-4edf-b33e-0d261e380dce)

**Comment by fkraeutli** [comment]
Thanks! It's fixed now

**Comment by b2d3c** [comment]
Perfekt! You can deploy in PROD. Thanks

**Comment by fkraeutli** [comment]
Done

**Comment by b2d3c** [comment]
Dear @fkraeutli 

> Only the layout is strange : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fo%2F0a40c922-206b-4ea2-9def-e0124b7311d7
> 
> Form : ![image](https://private-user-images.githubusercontent.com/8588224/327395552-1c43c162-6ce9-4e2f-b57e-561e754878cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwOTAxMTMsIm5iZiI6MTcxNTA4OTgxMywicGF0aCI6Ii84NTg4MjI0LzMyNzM5NTU1Mi0xYzQzYzE2Mi02Y2U5LTRlMmYtYjU3ZS01NjFlNzU0ODc4Y2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDdUMTM1MDEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDU5ZDQ5ZjU5OGNlZjNlNjEzYjhkNjNjMTI2Mjg4NWQxOGUzOWMzNjRlNzRkZTVjNzU0YjEzMmUxZWE0M2Y0MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QefJNy0CoJmc2wuFA2eB16ALH9Uc8U32nOVHgO7D9Vc) Layout: ![image](https://private-user-images.githubusercontent.com/8588224/327395700-5fbac20d-3985-4edf-b33e-0d261e380dce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwOTAxMTMsIm5iZiI6MTcxNTA4OTgxMywicGF0aCI6Ii84NTg4MjI0LzMyNzM5NTcwMC01ZmJhYzIwZC0zOTg1LTRlZGYtYjMzZS0wZDI2MWUzODBkY2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDdUMTM1MDEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODRjZDlmNjk2ZTgzZDdkZjAxMzc3ZGMwYjMyMmNlMjk2ZGU5YmMxZWY0ZjRmZmNkYzM2ZWY5ZWUxZTEyOWJiYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xSPOY-yN2D7WSC5g2S7ey-pYVlRMvjoDYk3dME8Ve2c)

The display bug is always there apparently..

http://data.performing-arts.ch/o/5253fea9-ed20-4daf-bbdd-1b38f55268d2

**Comment by fkraeutli** [comment]
Ah yes, there are two places where it is displayed

**Comment by fkraeutli** [comment]
Done

**Comment by b2d3c** [comment]
Thanks !
