### ISSUE TITLE
Bug Layout:Instantiation premis:File

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#586]
Informations from `premis:File` are no more displayed in `Layout:Instantiation`

```
?a a premis:File; premis:isIncludedIn ?b. 
?b a rico:Instantiation.
```
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/bd63c383-78aa-4cdf-8acb-4aca3a3140c7)

Exemple [DEV](https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fo%2Fc54cbd59-0977-4e0d-9150-e16566a7c020)

Could be link with #398

**Comment by fkraeutli** [comment]
fixed and deployed to Dev

**Comment by b2d3c** [comment]
Perfekt ! You can deploy in PROD. Thanks!

**Comment by fkraeutli** [comment]
Done
