### ISSUE TITLE
Layout:RecordResource : display Link to PDF on SAPA cloud

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#595]
After to have seen the complexity to display a PDF (host on our cloud) in the Plateform #555 

We would like to propose to implement in a first time the mechanism to display only the activ link to the any kind of file host on SAPA Cloud.
## Forms

Add in : 
* Form:RecordSet ([DEV](https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F191e5351-7bb4-41cf-8596-6d513af1fdf9))
* Form:Record ([DEV](https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F75d4a651-6de4-4af2-97cb-55f333922311))
* Form:Record/RecordPart ([DEV](https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F75d4a651-6de4-4af2-97cb-55f333922311))

The informations will be add under a label "SAPA Cloud", next to "IIIF Manifest".

![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/04f2965d-26b7-4283-ac31-01873644bc49)

Sereval statements have to be able to be introduce. 

Each statement have two mandatory Fields : 
* Link ?OnlineFile
* Descriptive note (string) ?OnlineFileValue

The link follow the format : https://cloud.sapa.swiss/s/[...] 

Exemple : https://cloud.sapa.swiss/s/Bpoo56qtRyjtWdA

The Field would create a statement : 

```
?RecordResource rico:hasInstantiation ?OnlineFile.
?OnlineFile rdf:type rico:Instantiation; rico:hasCarrierType <http://vocab.performing-arts.ch/fvonl>; rico:hasRepresentationType <http://vocab.performing-arts.ch/rttx>; rico:descriptiveNote ?OnlineFileValue.
```

## Layout 

This statement have to be display in : 
- `Layout:RecordSet` ([DEV](https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F191e5351-7bb4-41cf-8596-6d513af1fdf9))
- `Layout:Record` ([DEV](https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F75d4a651-6de4-4af2-97cb-55f333922311))
- `Layout:RecordPart` ([DEV](https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F729d3f71-da48-407d-8632-b3562a9a75df))

add on the top of the Central column.

Under the label "Related documents"

The string of ?OnlineFileValue will display with the active link to the File catch in.

**Comment by b2d3c** [comment]
We try a new way : see https://github.com/sapa/performing-arts-ch-templates/issues/555#issuecomment-2126567849

**Comment by fkraeutli** [comment]
Implemented in Dev and added to Record form. Where should the field appear in the Record Set and Record Part forms?

**Comment by b2d3c** [comment]
Questions : 
-  I don't see any statement for it. It's only in the Layout?
- We need to edit in the Form `?OnlineFile rico:descriptiveNote ?string` and to display it in state of the URL but with the hyperlink inside. Could you add a box in the Form. In the same way of `rico:hasOrHadIdentifier`

**Comment by fkraeutli** [comment]
Ah so `?OnlineFile` should be the URL of the PDF and `rico:descriptiveNote ?OnlineFileValue` a title for the PDF? That means two input fields?

**Comment by b2d3c** [comment]
> Ah so `?OnlineFile` should be the URL of the PDF and `rico:descriptiveNote ?OnlineFileValue` a title for the PDF? That means two input fields?

I have in mind something like this, a box with to Field URL + DescriptiveNote: 
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/ff0770c6-3e8a-4b2c-9fe9-d0c6cfe74272)

In Layout only the DescriptiveNote is displayed with the link under.

**Comment by fkraeutli** [comment]
There is one issue with these sort of composite forms. The form represents a single URI and there is currently no good mechanism for defining the URI in the form field. In this case, the first form field would take the URI and the second one the  description, which will be linked to the URI. This works when creating the statements for the first time, but it gets tricky to edit.

I will try to find a workaround. The alternative would be to have an in-between entity, e.g. 
```ttl
  ?RecordResource rico:hasInstantiation ?entity .
  ?entity rdf:type rico:Instantiation ; 
    rico:hasCarrierType <http://vocab.performing-arts.ch/fvonl> ; 
    rico:hasRepresentationType <http://vocab.performing-arts.ch/rttx>;
    rico:descriptiveNote ?OnlineFileValue.
 ?entity owl:sameAs ?OnlineFile .
```

**Comment by b2d3c** [comment]
Reminder : URI Instantiation are modelling following .../o/....

**Comment by fkraeutli** [comment]
I found an experimental field that allows editing the URI. The downside is that it does not (yet) have any checks implemented, so it currently does not verify that the URL entered is correct and corresponds to a SAPA cloud URL. Have a go, it's on DEV.

**Comment by b2d3c** [comment]
Interresting ! For me it's OK only some little modifications (see below).

## Test
I have done a try.

Record [DEV](https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F75d4a651-6de4-4af2-97cb-55f333922311)
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/18f24f00-163d-4990-9580-e05aa6ffa415)

Instantiation [DEV](https://www.dev.performing-arts.ch/resource/?uri=https%3A%2F%2Fcloud.sapa.swiss%2Fs%2FBpoo56qtRyjtWdA)
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/5f19fad2-f50c-4053-97bd-331c05072b52)

## Modifications
Just some tinny modifications :

1. Label in Layout : 
- en : Related documents
- fr : documents liés
- de : Verwandte Dokumente
- it : Documenti correlati

2. Declaration postion in Layout : in column 3 under the Treeview (Record hierarchy)
3. to add in Layout:RecordSet, Record and RecordPart.
4. In Form:RecordSet, add the SAPA Cloud box in "Additional Sources" section
5. In Form:RecordPart add the SAPA Cloud box with IIIF and Vimeo Section.

**Comment by fkraeutli** [comment]
Changed and deployed to Dev

**Comment by b2d3c** [comment]
Es ist toll !

Es fehlt nur noch : 
 
- In `Layout:Record` Label in @fr and @de
- In `Form:Record/RecordPart` the SAPA Cloud box in IIIF and Vimeo Section.

**Comment by fkraeutli** [comment]
Done and deployed to Dev

**Comment by b2d3c** [comment]
Perfekt! You can deploy in PROD.
