### ISSUE TITLE
Bug : Archivplan

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#599]
In a item 1047-2-1-18 (http://data.performing-arts.ch/r/33574739-be18-484c-80bb-41e0ace14230), there are a declaration with this string ([SPARQL](https://www.performing-arts.ch/sparql?query=PREFIX+skos%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23%3E%0APREFIX+frbroo%3A+%3Chttp%3A%2F%2Fiflastandards.info%2Fns%2Ffr%2Ffrbr%2Ffrbroo%2F%3E%0APREFIX+crm%3A+%3Chttp%3A%2F%2Fwww.cidoc-crm.org%2Fcidoc-crm%2F%3E%0APREFIX+spav%3A+%3Chttp%3A%2F%2Fvocab.performing-arts.ch%2F%3E%0APREFIX+rico%3A+%3Chttps%3A%2F%2Fwww.ica.org%2Fstandards%2FRiC%2Fontology%23%3E%0APREFIX+rdau%3A+%3Chttp%3A%2F%2Frdaregistry.info%2FElements%2Fu%2F%3E%0APREFIX+ebucore%3A+%3Chttps%3A%2F%2Fwww.ebu.ch%2Fmetadata%2Fontologies%2Febucore%23%3E%0APREFIX+spao%3A+%3Chttp%3A%2F%2Fontology.performing-arts.ch%2F%3E%0APREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0ASELECT+%2A+%0AWHERE+%7B%0A%3Chttp%3A%2F%2Fdata.performing-arts.ch%2Fr%2F33574739-be18-484c-80bb-41e0ace14230%3E+spao%3AhasNote+%3Fnote.%0A%7D+%0A)) with inside the value "Prince Alexandre Schervachidzé".

We want to fund it through Archivplan : https://www.performing-arts.ch/resource/sapa:ArchivePlan

But with the string "Schervachidzé" or "Schervachidz*" we have no result et we don't understand why.

With "Prince Alexandre" is no problem.

Cloud you find from where come the problem ?

See also : https://github.com/sapa/performing-arts-ch-templates/issues/235

**Comment by fkraeutli** [comment]
The term appears in a longer text and is therefore assigned a low score, below the cutoff. I have lowered the cutoff so it now appears. There will likely be other results that now appear due to the lower cutoff. It's deployed to Dev

**Comment by b2d3c** [comment]
Perfekt! You can deploy in PROD.

Which is the sign number cutoff know? Could we need a cutoff?

**Comment by fkraeutli** [comment]
I adjusted the minimum Relevance from 0.1 to 0.06. The lower it is, the more results that are irrelevant appear, so it's something that needs to be tuned (i.e. a minimum relevance of 0 would include also totally irrelevant results)

**Comment by b2d3c** [comment]
Dear @tfrancart, you will find in this discussion, a short presentation of the "Relevance" option in the Information Retrevial / full text search in Metaphactory. Feel free to ask Florian directly for more Informations.
