### ISSUE TITLE
(new) minimal Form:Recording

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#60]
ex: http://data.performing-arts.ch/w/a422c501-a281-4ca3-a29b-3785266eef06

## Form:Recording
- rdf:type = frbroo:F26_Recording
- UUID/x
- rdfs:label = string (Titre*@fr Title*@en Titel*@de)
- BOX : crm:P102_has_title (Add Titel*@en) :
 -- rdf:type = crm:E35_Title
 -- crm:P2_has_type (Type@en) = https://www.performing-arts.ch/resource/spav:go
 -- rdf:value (Title@en)  = string
- frbroo:R14_incorporates (Production*@en)  = URI (rdf:type) frbroo:F25_Performance_Plan (production)
- crm:P70_documents (Performance@en) =URI rd:type frbroo:F31_Performance (specific performance)
- crm:P2_has_type (Type*@en)  = https://www.performing-arts.ch/resource/spav:rg
- schema:duration (Duration@en)  = string
- spao:seeAlso (See also@en)  = URI (Warning: the information could coming from form:Virtual Instantation/File)
- BOX : crm:P67_is_referred_to_by (Add Note@en) :
 -- rdf:type = crm:E33_Linguistic_Object
 -- crm:P2_has_type (Type@en) = DROP-DOWN LIST (https://www.performing-arts.ch/resource/spav:eo)
 -- rdf:value (Note@en) = string

## See also
#61 
#118 

## WikiSapa
- https://wiki.sapa.swiss/index.php?title=Frbroo#frbroo:F26_Recording
- https://wiki.sapa.swiss/index.php?title=Crm#crm:E35_Title

**Comment by fkraeutli** [comment]
@b2d3c can you give me access to the sapa wiki?

**Comment by b2d3c** [comment]
Good question @fkraeutli !

There is already Production's Notices in the plateforme (ex: http://data.performing-arts.ch/w/2b465dc1-46d4-46a1-8982-ad8bf5149cb4) with more Fields as in the minimal Recording Form but in the Futur we will not use all this, only those from minimal Form.

The question is for the already existing Production's Notices, it's there a possibility to block the editable fonctionality with the minimal Form?

Thanks in advance!

**Comment by fkraeutli** [comment]
@b2d3c are frbroo:R14_Incorporates and crm:P70_documents pointing to the same entity? Or what is the datatype that P70 points to?

**Comment by b2d3c** [comment]
1. I renonce at the property P70_documents. We need it only to have the date (see the drawio schema "Video_SAPA_RDF")
2. I propose to simplify and to add P4_has_time-span in this Form
3. We need also to display P4_has_time-span in Template:Recording

**Comment by b2d3c** [comment]
We need also a Delete Fonction on the Template of this type of Entity. See #126

**Comment by fkraeutli** [comment]
1. Where do I find the drawio schema? I don't have access to the Wiki, in case it's there
2. F26 Recording is a subclass of E73 Information Object and cannot have a P4 has time span (which needs an Event). See acceptable properties at https://ontome.net/class/242/namespace/6#properties
3. see 2

**Comment by b2d3c** [comment]
Thanks for the info.
1. I send you an Invitation on diagrams.net Schema
2. Indeed It's not a easy question (see below 4). Befor to make it, we need to take the time to thing together about it. 
3. See 2
4. We need also : 
 - **F29 Recording Event**->frbroo:R21 created ->F26 Recording
 - F29 Recording Event->frbroo:R20 recorded-> **crm:E2 Temporal Entity**
 - crm:E2 Temporal Entity->crm:P4 has time-span->E52 Time-Span
5.  Also, I propose to stop the Work on this Issue and to give priority on #61

**Comment by b2d3c** [comment]
Dear @fkraeutli , I propose to deploy this form like this in Dev and Prod. 

For the date, we can put it on a Note Field. We don't need a F29 Recording Event already.

Thanks in advance!

**Comment by fkraeutli** [comment]
Hi @b2d3c , I deployed it as it is to Dev. Let me know if anything needs to be changed. I lost a bit track on what needs still to be integrated from our conversation above.

**Comment by b2d3c** [comment]
Hi Florian,

I don't find the Form under "quick links" in dev and nether under https://www.dev.performing-arts.ch/resource/sapa:createRecording .

Could you check it?

**Comment by b2d3c** [comment]
For the version 1 of the Form : https://www.dev.performing-arts.ch/resource/sapa:createRecording

Exemple 1 (with the new Form) : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fw%2Fe501cee5-4b86-4798-a51d-0669527a12e5 
Exemple 2 (already existing) : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fw%2Fff44bc75-ba1e-499a-8883-260bdcde5eb0

Here my notes:

Form : 

- Name of the Form : "New Recording@all"
- rdfs:label : add neutral (-) option (same as in [Form:Production](https://www.dev.performing-arts.ch/resource/sapa:createProduction))
- Name of field frbroo:R14_incorporates : "Performance Plan@all"
- Field frbroo:R14_incorporates : URI must be searchable
- lack BOX : crm:P67_is_referred_to_by (Add Note@en)  (see on the top specification)

Template : 

- Publish (before "production") "Performance Plan@all" with the label+link of value of frbroo:R14_incorporates
- Publish at the bottom "Note@all" information (crm:P67_is_referred_to_by)
- lack "Delete" Fonctionnality

**Comment by fkraeutli** [comment]
Thanks for the feedback @b2d3c !

I implemented all except the Delete function and put it on Dev.

Delete is tricky because we use forms in SPARQL mode here, so we can't use the same delete mechanism as elsewhere. I'll have a think on how to solve this

**Comment by b2d3c** [comment]
Great! 

Lack only in Template (Layout) after publishing : 
- Before "production", add text/header "Performance Plan@all" with value : the label of value of frbroo:R14_incorporates +link to this entity.

Thanks in advance!

**Comment by b2d3c** [comment]
Lack also : the link under menu "Create Entities". Label "Recording@all"

**Comment by fkraeutli** [comment]
Thanks! I implemented the changes and deployed them to Dev

**Comment by b2d3c** [comment]
Perfekt ! You can deploy in Prod @fkraeutli 

Thanks a lot

**Comment by fkraeutli** [comment]
Deployed
