### ISSUE TITLE
Form:RecordPart add Manifest IIIF

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#605]
Add in `Form:Record->RecordPart`, the **Manifest IIIF Field**.

![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/9949225c-c445-498f-863d-b05a7d26b25e)

As in `Form:Record` (see #455)

![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/54dee7e1-5a6e-4bd9-aa46-93a1ba3e0506)

**Comment by fkraeutli** [comment]
I think I have already implemented this as part of an earlier issue. Can you check?

**Comment by b2d3c** [comment]
In Form it's allright.

In Layout, it's something strange but we will see it next Year! https://github.com/sapa/performing-arts-ch-templates/issues/666
