### ISSUE TITLE
(new) minimal Form:Performance (production) 

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#61]
ex: http://data.performing-arts.ch/w/0de20e73-1327-4f62-8f0e-6819c3525066

## Form:Production 
- URI : .../w/UUID
- rdf:type -> frbroo:F25_Performance_Plan (https://www.performing-arts.ch/resource/frbroo:F25_Performance_Plan)
- rdfs:label (Title*@en) ->string
- crm:P2_has_type (Genre*@en) ->https://www.performing-arts.ch/resource/spav:mn
- owl:sameAs (Same as@en)-> URL
- BOX : crm:P67_is_referred_to_by (Add Note@en) :
 -- rdf:type = crm:E33_Linguistic_Object
 -- crm:P2_has_type (Type@en)->DROP-DOWN LIST (https://www.performing-arts.ch/resource/spav:eo)
 -- rdf:value (Note@en)->string
- BOX : crm:P102_has_title (Add Titel*@en) :
 -- rdf:type = crm:E35_Title
 -- crm:P2_has_type(Type@en) = https://www.performing-arts.ch/resource/spav:go
 -- rdf:value (Title@en) = string
- frbroo:R14_incorporates = URI
- crm:P1_is_identified_by  (RepID@en) = URI
- [hasMusicTitle](https://www.performing-arts.ch/resource/?uri=http%3A%2F%2Ftemp.performing-arts.ch%2FhasMusicTitle) (Music Title@en) = string
- rdfs:comment  (Comment@en) = string
- owl:sameAs  (External ID@en)  -> URL/URI

## Note
Entites frbroo:F31_Performance (URI:/w/../p) and frbroo:F31_Performance (URI:/w/.../p/...) are no fonctionaly need to be manualy describe

## WikiSAPA : 
- https://wiki.sapa.swiss/index.php?title=Works#Productions
- https://wiki.sapa.swiss/index.php?title=Crm#crm:E35_Title

**Comment by b2d3c** [comment]
Form:Production
- URI : .../w/UUID
- rdf:type frbroo:F25_Performance_Plan (https://www.performing-arts.ch/resource/frbroo:F25_Performance_Plan)
- rdfs:label string
- 

WikiSAPA : https://wiki.sapa.swiss/index.php?title=Works#Productions

**Comment by b2d3c** [comment]
We need also a Delete Fonction on the Template of this type of Entity. See #126

**Comment by b2d3c** [comment]
@fkraeutli If it's too complex or too time demanding, we can also image that the Form it's only accessible for frbroo:F25_Performance_Plan with a new property (ex: spao:noticeStatus) wich value is "new".
What do you think about?

**Comment by fkraeutli** [comment]
Not sure that helps. It’s the same effort to implement the form for some record as it is for all

**Comment by fkraeutli** [comment]
What label do we use for the field frbroo:R14_incorporates?

**Comment by fkraeutli** [comment]
I deployed a first version of the form to dev.
e.g. https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fw%2F0de20e73-1327-4f62-8f0e-6819c3525066
@b2d3c, can you provide feedback?

**Comment by b2d3c** [comment]
Sound Good ! 
First Questions:
- We need also a empty Form : https://www.performing-arts.ch/resource/sapa:createProduction
- Form don't be fit for https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fw%2F1677d2e7-2120-4f47-8844-6c5ee8491f57 why?
- Why the type of Linguistic Object are not display in different language?
- By the way : you know why spav:eo have no representation on Github ? https://sapa.github.io/spa-vocabulary/#eo

**Comment by fkraeutli** [comment]
ValueSet queries return labels in all languages

**Comment by fkraeutli** [comment]
> Sound Good ! First Questions:
> 
> * We need also a empty Form : https://www.performing-arts.ch/resource/sapa:createProduction

- [ ] Todo

> * Form don't be fit for https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fw%2F1677d2e7-2120-4f47-8844-6c5ee8491f57 why?

It has to do with this being a temporary item that is placed in a Named Graph that follows a different pattern than the normal ones: [http://data.performing-arts.ch/w/1677d2e7-2120-4f47-8844-6c5ee8491f57/container/temp-context](http://localhost:5010/resource/Assets:NamedGraph?graph=http%3A%2F%2Fdata.performing-arts.ch%2Fw%2F1677d2e7-2120-4f47-8844-6c5ee8491f57%2Fcontainer%2Ftemp-context). We would need to move/rename the named graph of those temporary items

> * Why the type of Linguistic Object are not display in different language?

- [ ] To check

> * By the way : you know why spav:eo have no representation on Github ? https://sapa.github.io/spa-vocabulary/#eo

- [ ] To check

**Comment by fkraeutli** [comment]
Implemented changes and deployed to Dev

**Comment by b2d3c** [comment]
Great!
to do please : #262
After : we will test!

**Comment by b2d3c** [comment]
I have update the top specifications (see #262) with owl:sameAs and a another label for crm:P1_is_identified_by

**Comment by fkraeutli** [comment]
Amended and deployed to Dev

**Comment by b2d3c** [comment]
Great ! 
One littel bug, on the  layout with External Ressource : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fw%2F0582bf90-5a13-4cb6-bf88-bed74184a80e

I continue to test.

![image](https://user-images.githubusercontent.com/8588224/204987644-a470bfa1-c3fd-4c11-b33d-ac9d7bb72601.png)

**Comment by b2d3c** [comment]
Also "Genre" is not displayed on Template:Production

**Comment by fkraeutli** [comment]
Thanks for the feedback! I deployed changes to dev

**Comment by b2d3c** [comment]
It's ok! You can deploy in prod!

**Comment by fkraeutli** [comment]
Deployed
