### ISSUE TITLE
Update clover to latest release

### ISSUE THREAD

**Issue by bardocuteam** [sapa/performing-arts-ch-templates#616]
Salut @fkraeutli,

Could you update Clover IIIF to the latest release? It adds useful features that we need.

Cheers!
Raphaël

**Comment by fkraeutli** [comment]
Updated on Dev. @b2d3c, can you check if it still behaves correctly?

**Comment by fkraeutli** [comment]
Noted, I have to see if it is available for the Web Component already

**Comment by fkraeutli** [comment]
It's there now, but seems we lost the image with the update...

![Image](https://github.com/sapa/performing-arts-ch-templates/assets/1564625/2e682234-fbe2-4157-ada3-5ab8a8d68eb5)

**Comment by fkraeutli** [comment]
It seems to be an issue with the latest clover version itself, since it also does not display on the official site. I'll report  it and we'll have to wait for a solution on their side. 

![Image](https://github.com/sapa/performing-arts-ch-templates/assets/1564625/d09ae31c-1ef2-41ba-8692-980e84baf3e4)

**Comment by b2d3c** [comment]
Dear Florian,

the diplay bug in Clover seems resolved : https://samvera-labs.github.io/clover-iiif/docs/viewer/demo?iiif-content=https%3A%2F%2Fmedia.performing-arts.ch%2Fiiif%2Fmanifest%2F1553-FO-28-3.json

Could you update the version in DEV ?

Exemple : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F712a8e0a-4f24-4bb4-8015-392d228d60e7

Thanks in advance !

FYI : @bardocuteam

**Comment by fkraeutli** [comment]
Updated and deployed to DEV

**Comment by b2d3c** [comment]
Thanks but  
1) it lacks always the button download 
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/fb83027a-c255-49e7-b186-b2e4197253e8)

2) the thumbnail is display under the image, in demo it is over the image

![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/18fbd856-321f-405b-8a2c-b7c8e27a6ba2)

**Comment by fkraeutli** [comment]
I can see the download button. Can you try clearing your cache?

<img width="505" alt="Screenshot 2024-06-13 at 15 22 21" src="https://github.com/sapa/performing-arts-ch-templates/assets/1564625/d15b8cc0-9a21-4194-9c6c-346839cbe4db">

In my case it does not display a thumbnail at all

**Comment by b2d3c** [comment]
You have right :+1: 

It's great! You can deploy in PROD.
