### ISSUE TITLE
Bug Form:Production (crm:P1_is_identified_by)

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#634]
We can not delete values of statement ` ?Prod crm:P1_is_identified_by ?ID. ?ID rdf:value ?string; a crm:E42_Identifier.`  in Form:Production

Ex: DEV https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fw%2F1c1d89d9-81e7-4a08-9a27-6b164ba713e9

WikiSAPA : https://wiki.sapa.swiss/index.php?title=Metaphactory/Form:Production#Bug

**Comment by b2d3c** [comment]
Perfekt. You can deploy in PROD.

**Comment by fkraeutli** [comment]
Done
