### ISSUE TITLE
Bug Server ?

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#637]
Could you see : http://data.performing-arts.ch/r/51c8c456-c133-4c0a-b790-b8f1203dccb7

![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/18e14c99-0330-4473-b24b-bb6a624cd254)

**Comment by fkraeutli** [comment]
It seems the server has run out of space

**Comment by b2d3c** [comment]
Ok. It's run normally now. Thanks!
I keep the post open to spoke about it next BR.

**Comment by b2d3c** [comment]
The problem is coming back for logged people

Ex: http://data.performing-arts.ch/r/09874706-9536-4e11-b4fd-ba44c9804367

![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/e7ebe7cf-8d53-4133-8adf-2c014e60fd7d)

**Comment by fkraeutli** [comment]
I have deleted all I safely can on the server but the problem is likely to come back. I have to find out how to increase the storage.

**Comment by b2d3c** [comment]
Do it if you can. We will pay to Switch what we need. Thanks!

**Comment by b2d3c** [comment]
Wir weiter denken durch #655
