### ISSUE TITLE
Bug : display date (F25_Performance_Plan)

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#642]
After #577 

We have seen that some problems:

A) date are displayed as "invalid date". 
B) date are displayed in bloc "Performances" in a wrong form

Could you find why?

A) No problem 
Ex: http://data.performing-arts.ch/w/8409604c-c5f3-4318-af44-4d0f31ba3ff5
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/d604391c-6622-412a-ad3d-c9c634e9d9a8)

A) Invalid date 
Ex: http://data.performing-arts.ch/w/c0239aa4-0a94-4df0-b5dd-9e759bd9c8ef
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/39b933a8-738f-4bb0-9835-61fc5de3a8c3)

B) Wrong form : 06.07.1972 instead of 07.06.1972
Ex: http://data.performing-arts.ch/w/8409604c-c5f3-4318-af44-4d0f31ba3ff5
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/d604391c-6622-412a-ad3d-c9c634e9d9a8)
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/fef9fadf-665f-4490-87e2-3a9975295954)

**Comment by b2d3c** [comment]
Exemple : http://data.performing-arts.ch/x/393affe2-469b-4662-9c1f-39eac775f735

**Comment by fkraeutli** [comment]
Fixed and deployed to Dev

**Comment by b2d3c** [comment]
Perfekt. You can deploy in PROD!

**Comment by fkraeutli** [comment]
Done
