### ISSUE TITLE
Layout F25_Performance_Plan : type and date in Performances box

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#643]
Aftre #642 

We would like that informations about type of Performance and the date will be displayed only in the box "Performances" after the date already displayed, and not as now in the first column.

07.06.1972 (French language premiere)

ex: http://data.performing-arts.ch/w/8409604c-c5f3-4318-af44-4d0f31ba3ff5
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/049f1bc4-0a27-4993-a7e7-814bc1db8c6a)

**Comment by fkraeutli** [comment]
Done and deployed to Dev

**Comment by b2d3c** [comment]
Perfekt. You can deploy in Prod.
