### ISSUE TITLE
Layout F25_Performance_Plan : two Performances box

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#644]
After #577 

We want to test a Layout F25_Performance_Plan with many P31_Performance linked.

Cloud we ask you to : 
- modifed in DEV [this item](https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fw%2F823a4b10-1816-4976-8676-31a418c90fe1%2Fp):
  - replace `?item frbroo:R25_performed <http://data.performing-arts.ch/w/823a4b10-1816-4976-8676-31a418c90fe1>`
  - by `?item frbroo:R25_performed <http://data.performing-arts.ch/w/ca52da06-b0c9-4b12-9ee7-bddd8ba8c4c0>`

We would like that the Layout of [the production](https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fw%2Fca52da06-b0c9-4b12-9ee7-bddd8ba8c4c0) diplay two "Perfomances" box : 
- one with the informations of the Performances in Theatro Social at 12.5.2016
- the second one with the informations on the Performance in Castelgrande at 13.7.2016

**Comment by fkraeutli** [comment]
Not sure I understand. Is there a change I need to do in the data or in the display template?

**Comment by b2d3c** [comment]
First modify the test data and then I will see how it's displayed and ask perhaps for modifications.

**Comment by fkraeutli** [comment]
Done

**Comment by b2d3c** [comment]
Prima !

Look good. Thanks

ex: https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fw%2Fca52da06-b0c9-4b12-9ee7-bddd8ba8c4c0
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/e4c6cfd1-e676-4415-b483-d5b69afa543d)
