### ISSUE TITLE
Bug : PDF Viewer

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#668]
Dear @fkraeutli 

After #555

We succed to display PDF : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2Fbe794e5e-a22a-47cd-9483-f5f5280e4568

But something go wrong with this one : http://data.performing-arts.ch/r/b3602099-7b51-4742-a0ad-12c8df7c2f9e

Cloud you help us to find why?

**Comment by fkraeutli** [comment]
Hi Baptiste, it seems I need to update the image on the prod server (the dev server is more current). It involves a short downtime. When would be a good time to do it?

**Comment by fkraeutli** [comment]
Sorry, the Metaphactory Docker Image, it's basically the version of the platform.

**Comment by b2d3c** [comment]
Ok ! You can do the update between 12:30 and 13:00. It's ok ? I will inform the crew.

**Comment by fkraeutli** [comment]
Will do!

**Comment by fkraeutli** [comment]
Works now! Might be necessary to clear local cache though.

<img width="1766" alt="Screenshot 2024-08-15 at 12 39 27" src="https://github.com/user-attachments/assets/cca85842-c61d-4cf8-9376-fb932199b5e9">

**Comment by b2d3c** [comment]
Super! Thanks a lot Florian.
