### ISSUE TITLE
Bug : Remplaced by

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#669]
Schauspielhaus Düsseldorf (http://data.performing-arts.ch/a/6aec46b8-2ffa-4a35-9ab7-874229afdab5)

must be "Replaced by":

Düsseldorfer Schauspielhaus (http://data.performing-arts.ch/a/efdc1080-206f-4721-b8f9-faa636471384)

But we have this error message : 

![image](https://github.com/user-attachments/assets/a18e1df1-c5ee-4fb0-8550-8690628aa3d5)

The action was be done without problem in PROD, but we can access to the past URL https://www.dev.performing-arts.ch/resource/?uri=%28http%3A%2F%2Fdata.performing-arts.ch%2Fa%2F6aec46b8-2ffa-4a35-9ab7-874229afdab5

Thanks in advance !

**Comment by fkraeutli** [comment]
The difference is that on DEV both entities are type "Group" while on PROD "Düsseldorfer Schauspielhaus" is a "Group" and "Schauspielhaus Düsseldorf" is an "artistic professional producer". The "replaced by" field expects the new entity to be of the same type. 

We can either temporarily remove this restriction or add a matching type to one of the entities. What would you prefer?

**Comment by b2d3c** [comment]
Thanks Florian !

It's fine like this. We will change the type manualy !
