### ISSUE TITLE
Feasability to use RDFS inference in the SPARQL endpoint ?

### ISSUE THREAD

**Issue by tfrancart** [sapa/performing-arts-ch-templates#673]
Dear @fkraeutli 

We were wondering with @b2d3c whether it would be feasible to have RDFS inference in the SPARQL endpoint ?

Because we are working on query forms that are issuing queries on the `rico:RecordResource` type, with the expected outcome that the query would return Records, RecordSets and RecordParts.

Is the activation of RDFS inference technically feasible in Metaphactory ? Would it have side effects ?

Thanks !

**Comment by fkraeutli** [comment]
I believe this needs to be done on the [Blazegraph](https://github.com/blazegraph/database/wiki/InferenceAndTruthMaintenance) instance. However I don't have any experience in this so would be hesitant to try it.

**Comment by b2d3c** [comment]
Dear @tfrancart, see answer Florian above. Do you know people with expertise in Blazegraph ?

**Comment by tfrancart** [comment]
No. This is not a blocking issue and I will show you how we worked around it. So I suggest to put this task on hold.
