### ISSUE TITLE
TLS : external link

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#681]
Dear Florian,

We don't understand why it's not possible to add a external link (owl:sameAs) with this URL.

See also : #307 

-  https://tls.theaterwissenschaft.ch/wiki/Piccolo/Piccolissimo/Pochettli,_Basel_BS in http://data.performing-arts.ch/a/b7196a1f-cf04-4f51-b9a1-0ddb6c828178
-  https://tls.theaterwissenschaft.ch/wiki/Il_Soggetto,_St%C3%A4fa/Z%C3%BCrich_ZH in in http://data.performing-arts.ch/a/59fa3f5c-0b95-4e25-a181-db7d92f8482a

Thanks in advance

**Comment by fkraeutli** [comment]
I changed the verification query and deployed to Dev. Can you check?

**Comment by b2d3c** [comment]
In Form, it's ok 
![image](https://github.com/user-attachments/assets/0e2cdcfc-d154-4f90-acec-228eb06714c6)
But if I save the change. The statement is there but no infromations is dispalyed.
![image](https://github.com/user-attachments/assets/756144fe-8398-443e-8ef4-6d2dce775bfa)
![image](https://github.com/user-attachments/assets/bf7d8510-4fd5-406a-b47e-39cbb2f2a4eb)

Exemple : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fa%2F59fa3f5c-0b95-4e25-a181-db7d92f8482a

**Comment by fkraeutli** [comment]
Ah I see, the visualisation part contains a query that matches a list of sources with the given URL. However, this particular URL didn't match it because it contains a slash. I changed the pattern so that the matching works, but it would be good if you also look at some other entries, to see if it did not inadvertently change the display of those.

**Comment by b2d3c** [comment]
It's OK! I have a look on 
* https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fa%2Fbe675da1-ac4d-4d80-8269-50000d6dc832
* https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fa%2F2d559100-555d-4139-a51b-0a2655b7bbb0

You can publish on PROD. Thanks!

**Comment by b2d3c** [comment]
Thanks a lot !
