### ISSUE TITLE
IIIF image simple (without Manifest) : display bug?

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#684]
Apparently, it's a bug on the display of IIIF images (without Manifest)

See : 
* https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F00ffe851-4111-4066-be3f-70b4050ec75a
* https://www.dev.performing-arts.ch/resource/sapa:MediaSearch?semanticSearch=N4IgziBcoNZQTAX0UA

Thanks in advance

**Comment by fkraeutli** [comment]
Appears to be cleared with #688

**Comment by b2d3c** [comment]
Thanks a lot!
