### ISSUE TITLE
Form:Person : TLS External Link (bug)

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#690]
We can not insert this link in Form:Person : 

https://www.tls.theaterwissenschaft.ch/wiki/Urs_Troller in 

DEV : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fa%2F0ced7f55-1012-44a3-a1ff-eae04eed571e

Could you fix it ?

See also : #681

**Comment by fkraeutli** [comment]
The form was expecting the link without www. However, TLS appears to provide it with www so I added support for it. Deployed in Dev and Prod.

**Comment by b2d3c** [comment]
Thanks a lot !
