### ISSUE TITLE
login Session extend

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#72]

**Comment by olyanicolaeva** [comment]
up to 1 hr

**Comment by b2d3c** [comment]
up to 4 hr.

**Comment by b2d3c** [comment]
@fkraeutli apparently the change was not done on the prod plateform. The login is always 30 minutes.

**Comment by fkraeutli** [comment]
@b2d3c My bad, the change requires a restart of the platform to be active. When we do that on Thursday it should be active

**Comment by b2d3c** [comment]
@fkraeutli 👍
