### ISSUE TITLE
New Field : rico:hasOrHadIdentifier

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#75]
1. Creation Properties
2. Add: Form:Record Set, Record, Instantation
3. Display : Template:Record Set, Record, Instantation

## Class of **Properties** zu erstellen
- rico:hasOrHadIdentifier
-- URI : https://www.ica.org/standards/RiC/ontology#hasOrHadIdentifier
-- rdf:type : ?owl:ObjectProperty
-- rdfs:label : has or had identifier@en
- rico:isIdentifierTypeOf
-- URI : https://www.ica.org/standards/RiC/ontology#isIdentifierTypeOf
-- rdf.type : ?owl:ObjectProperty
-- rdfs:label : is Identifier Type of @en

## Class of **Entities** zu erstellen
- rico:Identifier mit properties:
-- URI : https://www.ica.org/standards/RiC/ontology#Identifier
-- rdf:type ?owl:Class
-- rdfs:label Identifier@en
- rico:IdentifierType mit proterties:
-- URI : https://www.ica.org/standards/RiC/ontology#IdentifierType
-- rdf:type ?owl:Class
-- rdfs:label : Identifier Type@en

## Vocabulary zu erstellen
- New Identifier vocabulary URI : http://vocab.performing-arts.ch/id
-- Entity: **old identifier**
--- rdf:type rico:IdentifierTyp
--- URI : http://vocab.performing-arts.ch/idold
--- rdfs:label : old identifier@en ancien identifiant@fr alt Signatur@de
-- Entity : **Unique ID**
--- rdfs:label : Unique ID@en Cote d'identification@fr Identifizierung Signatur@de
--- URI : http://vocab.performing-arts.ch/iduni
-- Entity: **technical Identifier**
--- rdf:type rico:IdentifierTyp
--- URI : http://vocab.performing-arts.ch/idtec
--- rdfs:label : Technical Identifier@en Identifiant technique@fr (à définir)@de
-- Entity: **contextual Identifier**
--- rdf:type rico:IdentifierTyp
--- URI : http://vocab.performing-arts.ch/idcon
--- rdfs:label : Contextual Identifier@en Cote de contexte@fr (à définir)@de

## Form zu modifizieren: Record Set, Record (and RecordPart), Instantation
- Hinzufügen (wie Add Daten oder Add Extent) module "Add Identifier" (add property rico:hasOrHadIdentifier and create a rico:Identifier Entity URI: http://data.performing-arts.ch/x/UUID)  mit : 
-- Wahl zwischen vorerstellen vocabulary von rico:IdentifierType Entities (ex: Old Identifier, Cote d'individualisation)->rico:isIdentifierTypeOf
-- string value ->rdf:value
## Template
Display the value of rico:hasOrHadIdentifier In Record Set, Record and Instantation Template under the existing label "Identifier" with the type between brackets.
## to do after
rico:identifier #166 -> #165-> #167->#168->#168
spao:legacyidentifier #170
RecordPart Order : #177

**Comment by fkraeutli** [comment]
Example RDF for adding a 'old identifier' to `subject`.

```ttl
@prefix crm: <http://www.cidoc-crm.org/cidoc-crm/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rico: <https://www.ica.org/standards/RiC/ontology#> .

<subject> rico:hasOrHadIdentifier <http://data.performing-arts.ch/x/1234-5678-ABCD-EFGH> .
<http://data.performing-arts.ch/x/1234-5678-ABCD-EFGH> a rico:Identifier ;
    rdf:value "old identifier" ;
    crm:P2_has_type <http://vocab.performing-arts.ch/idold> .

<http://vocab.performing-arts.ch/idold> a rico:IdentifierType .
```

@b2d3c can you verify if this is what you expect? In particular:
1. Identifier type added to identifier via `crm:P2_has_type`
2. Identifier to be added passed as a string ("old identifier") via rdf:value

**Comment by fkraeutli** [comment]
Proposed vocabulary for identifier type:

```ttl
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix : <http://vocab.performing-arts.ch/id> .

: a skos:ConceptScheme .

:old a skos:Concept ;
    rdfs:label "old identifier"@en, "ancien identifiant"@fr, "alt Signatur"@de ;
    skos:inScheme : .

:uni a skos:Concept ;
    rdfs:label "Unique ID"@en, "Code d'identification"@fr, "Identifizierung Signatur"@de ;
    skos:inScheme : .

:tec a skos:Concept ;
    rdfs:label "Technical identifier"@en, "Identifiant technique"@fr, "..."@de ;
    skos:inScheme : .

:con a skos:Concept ;
    rdfs:label "Conceptual Identifier"@en, "Cote de contexte"@fr, "..."@de ;
    skos:inScheme : .
```

<img width="509" alt="Screenshot 2022-08-25 at 15 34 41" src="https://user-images.githubusercontent.com/1564625/186678839-c9960654-71e9-4dd6-b699-5751448dda77.png">

@b2d3c can you verify that this is correct? In particular:
1. Do you want the namespace to be without trailing `/`. (resulting in URI e.g. `http://vocab.performing-arts.ch/idold` and not `http://vocab.performing-arts.ch/id/old`)

**Comment by b2d3c** [comment]
@fkraeutli, Example RDF for adding a 'old identifier' to `subject` : 
```ttl
 @prefix crm: <http://www.cidoc-crm.org/cidoc-crm/> .
 @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
 @prefix rico: <https://www.ica.org/standards/RiC/ontology#> .

 <subject> rico:hasOrHadIdentifier <http://data.performing-arts.ch/x/1234-5678-ABCD-EFGH> .
 <http://data.performing-arts.ch/x/1234-5678-ABCD-EFGH> a rico:Identifier ;
    rdf:value "GT-8765" ;
    crm:P2_has_type <http://vocab.performing-arts.ch/idold> .

 <http://vocab.performing-arts.ch/idold> a rico:IdentifierType;
      rdf:value "old identifier@en" ;
```
I just add "GT-8765" as rdf:value of /x/1234-5678-ABCD-EFGH and "old identifier@en" as rdf:value of idold. 

For the rest, it's allright. I look now on the vocabulary proposition.

**Comment by b2d3c** [comment]
@fkraeutli 

Allright for the vocabulary.

I confirm the form : http://vocab.performing-arts.ch/idold like the other vocabulary until now (ex:http://vocab.performing-arts.ch/goctm), but if there is a special avantage to change, we can choose your proposition.

only "Contextual Identifier" not "Conceptual Identifier".

**Comment by fkraeutli** [comment]
Thanks @b2d3c . I copy it below with the typo fixed. No particular advantage of adding the trailing slash. Just wanted to confirm.

```ttl
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix : <http://vocab.performing-arts.ch/id> .

: a skos:ConceptScheme .

:old a skos:Concept ;
    rdfs:label "old identifier"@en, "ancien identifiant"@fr, "alt Signatur"@de ;
    skos:inScheme : .

:uni a skos:Concept ;
    rdfs:label "Unique ID"@en, "Code d'identification"@fr, "Identifizierung Signatur"@de ;
    skos:inScheme : .

:tec a skos:Concept ;
    rdfs:label "Technical identifier"@en, "Identifiant technique"@fr, "..."@de ;
    skos:inScheme : .

:con a skos:Concept ;
    rdfs:label "Contextual Identifier"@en, "Cote de contexte"@fr, "..."@de ;
    skos:inScheme : .
```

**Comment by fkraeutli** [comment]
Todo:

- [ ] Add new vocabulary terms, ideally through [mechanism in](https://github.com/sapa/spa-vocabulary)
- [ ] Add field definitions for new fields
- [ ] Add form definition

**Comment by fkraeutli** [comment]
Another question @b2d3c : https://github.com/sapa/spa-vocabulary/blob/master/README.md mentions that the original `ControlledTerms.xlsx` is hosted on SharePoint. Is this still the case and, if yes, can you give me access?

**Comment by b2d3c** [comment]
Link given by mail

**Comment by fkraeutli** [comment]
Updated https://github.com/sapa/spa-vocabulary with new terms and generated TTL/NQuad outputs

**Comment by fkraeutli** [comment]
Added display

<img width="1273" alt="Screenshot 2022-09-22 at 12 38 58" src="https://user-images.githubusercontent.com/1564625/191725914-9f012d25-cb9b-4783-9824-2c1982673a5a.png">

**Comment by fkraeutli** [comment]
Deployed to staging

@b2d3c can you check?

**Comment by b2d3c** [comment]
Thanks @fkraeutli !

My suggestions : 

1. Identifier with type "Technical" must not be displayed on the Templates. Only visibile on the Statement.
2. For RDF structure of vocabulary, you suggest : 

![image](https://user-images.githubusercontent.com/8588224/194025403-1d3e71f4-2e1d-48a8-849e-77423a0c7a8c.png)
It's seem are confusion on the languages and we will better something like this : 
![image](https://user-images.githubusercontent.com/8588224/194025497-6e124653-23a1-43db-b238-9a9b531a4938.png)

I will send you all traduction of the concepts.

**Comment by fkraeutli** [comment]
Template display should exclude the technical identifier.

**Comment by fkraeutli** [comment]
For now, deploy both old and new identifier.

Todo: Keep old identifier in forms but mark as _deprecated_

**Comment by fkraeutli** [comment]
Thanks!
1. Yes just temporary (is working again)
2. The identifier itself is not mandatory. But when one adds an identifier it is mandatory to give both a value and an identifier type. Is this ok?
3. I can change the label accordingly. However, it will show up as deprecated in every form it is used. Is this ok?

**Comment by b2d3c** [comment]
Perfect!
1. Ok
2. OK
3. OK but the Fields "identifier (depricated)" and "legacy identifier (depricated)" have to be displayed in the Forms close to the new "Identifier"

**Comment by fkraeutli** [comment]
Added the _deprecated_ markers

**Comment by b2d3c** [comment]
Hello @fkraeutli 

1. The terme "deprecated" muss only on the Form displayed be. Not in the template 
![image](https://user-images.githubusercontent.com/8588224/195523208-2370526f-84de-48db-ad6a-2b40523c11cd.png)
2. in the form : Field "Identifier (deprecated)" und "Legacy identifier (deprecated)" muss not be displayed in the bottom but at the top in the "Identification" Zone, narrow of new "Identifier" Field.
![image](https://user-images.githubusercontent.com/8588224/195524040-cb360e41-bc4f-49ce-a8d0-f54dbdfe8dc2.png)
![image](https://user-images.githubusercontent.com/8588224/195523913-b6f00563-36e0-42fa-8baa-756c24000243.png)

**Comment by b2d3c** [comment]
In Template Record, RecordSet and Instantation, we would like that the ordering of identifier follow this rule:

Identifier
* **Unique ID** (in bold)
* Contextual
* Old
* Technical (only for loged people)

**Comment by fkraeutli** [comment]
Deployed to dev:
- moved legacy identifier to identifier section
- changed order of identifier
- show techincal id for logged in users
- display unique id in bold

**Comment by b2d3c** [comment]
Perfekt!

Three points only:

ex: [https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2Fd6f3122e-9282-40ce-9c9d-6c4c48d5a680]

1. In Template New "Identifier" area have to be displayed up to "Signatur" area.
2. The traduction of the terme must be also be displayed. Ex: "old identifier"->"ancien identifiant"
3. The general label of the "Identifier" area must also be translate:
 - @en Identifier
 - @fr Identifiants
 - @it identificativi 
 - @de Bezeichner

**Comment by fkraeutli** [comment]
Cool, I think I got everything (on dev)

**Comment by b2d3c** [comment]
Top!

**Comment by b2d3c** [comment]
The new Fonctionnality "add Identifier" must also be add in Form:Record but for the entities "RecordPart".

![image](https://user-images.githubusercontent.com/8588224/197962345-0c791777-b843-426f-a7ee-1c50d8d20e38.png)

**Comment by b2d3c** [comment]
In Form on Prod, Labels of the old "identifier" und "legacy identifier" must be modified with "(deprecated)"

ex: http://data.performing-arts.ch/r/0def18bb-3cfd-489c-ba2b-c93170bcb618
![image](https://user-images.githubusercontent.com/8588224/198240570-1cedd32a-abe6-44dc-b268-e3ef62288129.png)

As in Dev in the 4 languages : 

![image](https://user-images.githubusercontent.com/8588224/198241267-712bc981-6351-4058-8aa9-b3e8ad47b0aa.png)
![image](https://user-images.githubusercontent.com/8588224/198241370-d4267df3-8cd2-44df-a73d-f728323de948.png)
![image](https://user-images.githubusercontent.com/8588224/198241442-f676d336-d128-4eb0-9ee7-081de6c52fbe.png)
![image](https://user-images.githubusercontent.com/8588224/198241551-4ccc3317-b129-423d-8b32-b2a3af4bebe4.png)

**Comment by fkraeutli** [comment]
Hi @b2d3c , can you try emptying your browser cache? The _deprecated_ labels are added via CSS, so might be a local issue that they are missing at your end.

<img width="424" alt="Screenshot 2022-11-03 at 11 13 17" src="https://user-images.githubusercontent.com/1564625/199695257-0ddf9265-156f-45ce-93f7-93fc25fc1c8e.png">

**Comment by b2d3c** [comment]
* layout It's ok now! 
* RecordPart : ok!
Thanks!
