### ISSUE TITLE
Treeview : Order Record Set and Record by identifier

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#76]
Property to order by : rico:identifier
- Template:Person (Lapsezon) : http://data.performing-arts.ch/a/51cbc2c1-8969-4bdf-8c66-a120c0bf1c34
![image](https://user-images.githubusercontent.com/8588224/171811403-00c6c509-cfc1-439b-a128-2473eebc9e30.png)
- Template:Group : http://data.performing-arts.ch/a/517a8791-a84c-423e-9914-b42d77b75f0c
![image](https://user-images.githubusercontent.com/8588224/171811528-eaf9b773-1704-4550-b104-91ee7137c6ca.png)
- ArchivePlan : https://www.performing-arts.ch/resource/sapa:ArchivePlan
![image](https://user-images.githubusercontent.com/8588224/171811779-6c319a54-f4c8-4de8-85fc-976ac4f5bb84.png)

**Comment by fkraeutli** [comment]
Deployed to staging. @b2d3c can you check?
Note that the sorting is alphabetical, e.g.
101-1
101-10
101-100
...
101-2
Is this an issue? If yes, we might have to add some magic.

**Comment by b2d3c** [comment]
Hello @fkraeutli !

I have tested it on the dev plateforme :

- Template:Person https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fa%2F51cbc2c1-8969-4bdf-8c66-a120c0bf1c34
- Template:Group https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fa%2F517a8791-a84c-423e-9914-b42d77b75f0c
- ArchivPlan : https://www.dev.performing-arts.ch/resource/sapa:ArchivePlan

It's sound already better! It's ok for me.

I have notice the alphabetic sorting. We need to open a new issue for it. We have to chose between computing magic or manualy change. The choice is depend form the importance time to put magic on it. I would think that manualy change are more economic but I am also listing to you. 

Thanks!

**Comment by fkraeutli** [comment]
Great, I'll deploy to prod.

Re the alphabetic sorting: if we apply magic, we have to do it everywhere where the identifier is queried. I don't know the platform well enough yet to know where it appears. Probably better to adjust it in the data.

However, we don't need to do it completely manually. We can run a query that changes the format (e.g. from 101-2 to 101-002). If you open an issue we can continue there.

**Comment by b2d3c** [comment]
Thanks @fkraeutli !

I will resolve the question of magic through the strategic and priority #75 with a new Identifier Typ -> technical identifier.

The right form (ex: 101-002) will be write here and we can write what we will on the regular Identifier (ex: 101-2).

The regular Identifier will continue to be display on the treeview but the ordering will be done on the technical Identifier.
