### ISSUE TITLE
spao:legacyIdentifier in Form and Template

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#79]
- Add the property spao:legacyIdentifier in
--  Form:Instantation (physical)
--   Form:Instantation (virtual)
- Display on Template :Instantation mit label : Alte Signatur @de Ancienne cote@fr LegacyIdentifer@en

**Comment by fkraeutli** [comment]
@b2d3c I implemented the changes and deployed to dev.

There was already a Legacy Identifier field, which I reused. However the labels for this are:

en: Legacy identifier
de: Fühere Signatur (sic, I will fix the typo)
fr: Ancienne cote
it: Segnatura precedente

Do you want to change them?

**Comment by b2d3c** [comment]
Thanks @fkraeutli !

I have check on : 
* virtual : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fo%2Fba9996dd-a75f-447d-bd55-5def3a0185f3
* physical : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fo%2Fdebcb9d2-76bb-4ba6-b774-a72621d0eb5d

Perfect! You can deployed on prod.

I notice only a typographic mistake on the Template:Instantation : label "**P**epresentation type" instead of "**R**epresentation type".

P.S. on the next Sprint we will transfert the value of this Property on the new Property rico:hasOrHadIdentifier
(see #75 ) under the IdentifierType "old identifier".

**Comment by fkraeutli** [comment]
Great, I fixed the typo
