### ISSUE TITLE
spao:hasInternalNote in Form and Template

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#82]
- Add in:
--  Form:Instantation [(virtual)]
<img width="1395" alt="Virtual Instantiation" src="https://user-images.githubusercontent.com/36266394/177341275-3a16abf7-fe88-49bc-99c4-41256d2e0fc4.png">
--  Form:Instantation (physical)
<img width="1452" alt="Physical Instantiation" src="https://user-images.githubusercontent.com/36266394/177342554-0a2cc2cb-e049-46c5-b514-761a061a931e.png">
- Display in Template:Instantation (only for logged people)
<img width="1451" alt="Template Instantiation" src="https://user-images.githubusercontent.com/36266394/177343169-f9b25690-23d2-40aa-b1cb-eaa39fcfbe2f.png">

**Comment by fkraeutli** [comment]
Deployed to staging. Please check @b2d3c

**Comment by b2d3c** [comment]
Hello @fkraeutli !

I have tested on dev plateforme : 
- virtual Instantation : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fo%2F17c8aa74-7802-4d30-9624-d6d2dcbc09e5
- physical Instantation : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fo%2Fac31420c-ed98-4cd6-bcb7-315fa720696d

Perfekt !

Thanks.
