### ISSUE TITLE
spao:hasInternalNote in Template:Record, RecordSet

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#83]
Display spao:hasInternalNote values only for logged people:
in Template:Record . ex: http://data.performing-arts.ch/r/9b54e5c0-de2a-465a-9609-b3909375a41b
in Template:RecordSet .ex: http://data.performing-arts.ch/r/0def18bb-3cfd-489c-ba2b-c93170bcb618

See also #96

**Comment by fkraeutli** [comment]
Deployed to prod for @b2d3c to check

**Comment by b2d3c** [comment]
You might said "deployed in Dev" ;-)

RecordSet: [exemple](https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F85400b86-6cbe-40c3-ad2d-ef72437fd276)
Record: [exemple](https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2Fd6f3122e-9282-40ce-9c9d-6c4c48d5a680)

It's alright! You can deployed in prod!

**Comment by fkraeutli** [comment]
Ha! Yes Dev, I'll put it on Prod
