### ISSUE TITLE
dev.performing-arts.ch (Make strong difference with prod)

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#95]
Make strong difference with prod:
- Change titel dev.perfoming.arts.ch -> DEVELOPPEMENT (perfoming-arts.ch)
- Change color

**Comment by b2d3c** [comment]
Hello @fkraeutli @olyanicolaeva, It's possible to fix this issue quickly. Some Collegue have already done the mistake between prod und dev. Thanks in advance!

**Comment by fkraeutli** [comment]
dev now has a striped title bar

<img width="946" alt="Screenshot 2022-08-29 at 15 15 05" src="https://user-images.githubusercontent.com/1564625/187209706-d4c41f11-353e-498d-80e7-e35f53696e2d.png">

**Comment by b2d3c** [comment]
Thanks @fkraeutli ! 
I will check with collegue if the difference is adequate and then close the Issue.

**Comment by fkraeutli** [comment]
<img width="1505" alt="Screenshot 2022-08-30 at 17 18 16" src="https://user-images.githubusercontent.com/1564625/187475686-b576ecc0-0530-4245-8ccb-fac91e3391a4.png">
<img width="1509" alt="Screenshot 2022-08-30 at 17 14 37" src="https://user-images.githubusercontent.com/1564625/187475697-85df6540-d936-46db-86f5-308abc18560d.png">

If not, we can make the change a bit less subtle

**Comment by b2d3c** [comment]
Thanks @fkraeutli : the stronger difference is better ! The first one von 30.08 will be fine.

**Comment by fkraeutli** [comment]
Updated dev with red version
