### ISSUE TITLE
Template:Record (layout change)

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#96]
column 1 : All Declarations
column 2 : Record Part + Instantation
colume 3 : Record hierarchy

e.g. : http://data.performing-arts.ch/r/5d3deead-f3a0-420d-961e-1d83592d18f3

![TemplateRecord drawio](https://user-images.githubusercontent.com/8588224/172373935-e9d69e1e-da75-487e-91bf-97202499657b.png)

**Comment by fkraeutli** [comment]
Changed and deployed to dev @b2d3c

**Comment by b2d3c** [comment]
I don't see the modification. 

ex: https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F0012ef5b-b15b-4213-9c30-c2909db0e083

**Comment by fkraeutli** [comment]
The content elements moved

![Image](https://user-images.githubusercontent.com/1564625/236205671-5b245c3b-8bee-4dcd-b7ac-3fd360d313df.png)

**Comment by b2d3c** [comment]
Perfekt! You can deploy in prod.

I document only the changes here : 
## Record + Instantiation
- prod : http://data.performing-arts.ch/r/889960be-34b6-4ae7-bf82-bd241115520d
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/0411ef3d-a7fd-4a1e-9f1f-f4e824c543c4)
 - dev : https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F889960be-34b6-4ae7-bf82-bd241115520d
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/a114622b-f665-46a7-a52f-863309ff2e64)
## Record + RecordPart + Instantiation
- prod : http://data.performing-arts.ch/r/2569e956-da12-439b-877b-12593ab40f46
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/537f5376-3920-4a33-85d4-1fbaa2334dbf)
- dev: https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fr%2F2569e956-da12-439b-877b-12593ab40f46
![image](https://github.com/sapa/performing-arts-ch-templates/assets/8588224/4fdef694-37c3-488a-93a5-c345e0439255)
