### ISSUE TITLE
Height/Width (Title Change)

### ISSUE THREAD

**Issue by b2d3c** [sapa/performing-arts-ch-templates#97]
- Field:Wight (ebucore:width). Title "Wight"->"Frame Wight"
- Field:Height (ebucore:height). Title "Height"->Frame Height"
In :
- Form:Physical Instantation
- Form:Virtual Instantation
- Template:Instantation

**Comment by fkraeutli** [comment]
Change labels in forms and template

**Comment by fkraeutli** [comment]
Deployed to Dev

**Comment by b2d3c** [comment]
Perfekt in Form!

But it lack in Template:Instantation

ex: https://www.dev.performing-arts.ch/resource/?uri=http%3A%2F%2Fdata.performing-arts.ch%2Fo%2Fc63c80d0-0cf9-4057-99df-add8a7d98e25

![image](https://user-images.githubusercontent.com/8588224/203553516-c65d8e55-6480-4fb0-aa09-266bf5dd4902.png)

**Comment by fkraeutli** [comment]
Fixed it

**Comment by b2d3c** [comment]
Perfekt! You can deploy in prod. Thanks!

**Comment by fkraeutli** [comment]
Deployed to prod
